### ISSUE TITLE
Entering leading decimal results in integer

### ISSUE THREAD

**Issue by tygriffin** [s-yadav/react-number-format#101]
When I type ".99" the result looks like this:
![not desired](https://user-images.githubusercontent.com/4317136/31693892-caa7f1bc-b3ec-11e7-8ba7-b7827e2648bf.png)

... whereas, I'd expect this:
![desired](https://user-images.githubusercontent.com/4317136/31693901-d8f84564-b3ec-11e7-8acf-a240edff8c64.png)

Happy to attempt a PR, if you'd like.

**Comment by s-yadav** [comment]
In 3.0.0  it should be $.99 while your typing and should become $0.99 onBlur. Let me fix this. I know which part is causing this issue.

**Comment by lutchobandeira** [comment]
@tygriffin I was wondering if you came up with a solution, I am trying to achieve the same behavior.
