### ISSUE TITLE
onBlur isn't called when format prop is provided

### ISSUE THREAD

**Issue by jth0024** [s-yadav/react-number-format#103]
Hey, I've noticed an odd behavior since upgrading to the version 3 beta. The onBlur prop is only called when format isn't provided as a prop. In your source code you have the following class method: 

```
  onBlur(e: SyntheticInputEvent) {
    const {props, state} = this;
    const {format, onBlur} = props;
    let {numAsString} = state;
    const lastValue = state.value;
    if (!format) {
      numAsString = fixLeadingZero(numAsString);
      const formattedValue = this.formatNumString(numAsString);
      const valueObj = {
        formattedValue,
        value: numAsString,
        floatValue: parseFloat(numAsString)
      };

      //change the state
      if (formattedValue !== lastValue) {
        this.setState({value : formattedValue, numAsString}, () => {
          props.onValueChange(valueObj);
          onBlur(e);
        });
      } else {
        onBlur(e);
      }
    }
  }
```

Should the onBlur prop really be invoked inside that **if** statement? I think I should always be able to handle the onBlur event as a consumer of the library. This change actually breaks functionality in my existing app, because I can't tell when the inputs have blurred, and I need that hook to show animations.

**Comment by s-yadav** [comment]
Yes it should be outside of that if condition. Will fix that.

**Comment by jth0024** [comment]
@s-yadav Awesome, I went ahead and made a pull request

**Comment by jth0024** [comment]
@s-yadav Thanks for the super quick turnaround on this fix.
