### ISSUE TITLE
customInput

### ISSUE THREAD

**Issue by nanocreaator** [s-yadav/react-number-format#107]
Hi!
I am trying to use NumberFormat with **customInput** and AutoComplete as its component instead the TextField mentioned in the example.
It works for the mask and so on, however the events **onNewRequest** and/or **onUpdateInput** from AutoComplete never fires. 
Am I missing something?

Thank you

Code ex.:
<NumberFormat
             autoFocus
              hintText={I18n.pt.relative.field.doc}
              floatingLabelText={I18n.pt.relative.field.doc}
              fullWidth={true}
              name="doc"
              errorText={this.state.errors.doc}
              underlineFocusStyle={{borderBottom: 'solid 1px'}}
              disabled={this.props.loading}
              **onNewRequest={this.reachSelectedOption}
              onUpdateInput={this.resetAutoCompleteFields}**
              filter={AutoComplete.caseInsensitiveFilter}
              dataSource={this.state.search.items || []}
              dataSourceConfig={dataSourceConfig}
              maxSearchResults={10}
              openOnFocus={true}
              format="###.###.###-##"
              customInput={AutoComplete}
           />

**Comment by s-yadav** [comment]
Can you set up a fiddle/codepen? Can help you better with that.

**Comment by nanocreaator** [comment]
Yes, please check:
https://codesandbox.io/s/9zm1xz16m4

The first one is simple example with TextField and NumberFormat. Working fine.
The second one is a simple AutoComplete.
The third one is NumberFormat with AutoComplete. This is not working at all, if I did not missing something, of course.

Thanks

**Comment by s-yadav** [comment]
Looks like AutoComplete component override onChange prop (https://github.com/callemall/material-ui/blob/master/src/AutoComplete/AutoComplete.js#L542), in which NumberFormat is depended. 
You can create an issue on material-ui AutoComplete component. I think this they have already fixed on beta.

**Comment by nanocreaator** [comment]
Isn't possible use NumberFormat with onKeyUp or onKeyDown alternatively instead onChange?

**Comment by s-yadav** [comment]
As we do formatting on the input text and also modify the caret position, onChange event is best to do this, as till that time browser is done with all of it works. Also, key events are not very reliable on android chrome. Because of which there are some patches are done in onChange event.

**Comment by SATHISH357** [comment]
Hi Sudhanshu Yadav,

I am using NumberFormat  component for credit card masking.

I want to mask the values based on the request like

#### XXXX XXXX XX## - 3434 XXXX XXXX XX89

But the format only accepts # code

Is there any way to customize the format other than using separate function

Thanks in advance
