### ISSUE TITLE
type='text' generates <input type="text">

### ISSUE THREAD

**Issue by svlaev** [s-yadav/react-number-format#109]
Hey guys!

We are using `react-number-format` to format a currency field in our project.
However the default `type` is set to `text` and it generates `<input type='text'>`. 
On mobile that's an inconvenience because the default alphabetic keyboard is shown. 
I switched to `type='tel'` and it generates `<input type='tel'>`. Keyboard on mobile is fine, but semantically it doesn't make sense to have currency field masked as phone field: `<input type='tel'>` 

Here comes my question: Why the default case is not `<input type='number'>`? After all we are formatting numbers.

Thanks in advance!

**Comment by s-yadav** [comment]
`<input type='number'>` does not allow adding non-numeric character in the input, which we need to show formatted text.

**Comment by svlaev** [comment]
@s-yadav thank you!
