### ISSUE TITLE
Non formatted value in onChange

### ISSUE THREAD

**Issue by nmartinezb3** [s-yadav/react-number-format#11]
Hi, 
How do I get the original non-formatted value on the onChange callback?, because I'm getting the $231,231,454,345 value in event.target.value

**Comment by s-yadav** [comment]
First parameter on onChange handler will be event object and second parameter will be nonFormatted value. Will add this on doc. 
```js
<NumberFormat thousandSeparator={true} prefix={'$'} onChange={(e, value) => {
//value is non formatted value
}}/>
```

**Comment by Tommy10802** [comment]
dont you think it is better returning non formatted value as number or float when inputed value is number and string when inputed value is not number. Because now non formatted value is still string even input value is number or float
