### ISSUE TITLE
Deleting formatting character moves caret instead of deleting value character

### ISSUE THREAD

**Issue by lopno** [s-yadav/react-number-format#113]
First of all I would like to thank you for this amazing library!

I have a small issue. I have created an input field for numbers and I am using the thousand separator `.`. If I have the cursor after a `.` and press backspace I would assume that the previous number character would be deleted. Instead the caret is moved once to the left.

In this example the caret is `|`

Actual behaviour:
`1.000.|000` -> `1.000|.000`

Expected behaviour:
`1.000.|000` -> `100|.000`

I am using the following props in my input component:
```
thousandSeparator="."
decimalSeparator=","
allowNegative={false}
displayType="input"
type="tel"
```

**Comment by s-yadav** [comment]
I think the current behaviour is ok. The other valid argument can be deleting something, not on cursor position can feel wrong. And also its just a matter of one more backspace/delete. 
Also changing it to the behaviour you mentioned can break other cases.

**Comment by kirkegaard** [comment]
@lopno did you ever find a way to do this?
I was actually looking for the same thing here https://github.com/s-yadav/react-number-format/issues/492

**Comment by sampurcell** [comment]
@kirkegaard Did you find a solution to your issue in #492 
Was hoping for the same behavior
