### ISSUE TITLE
decimalSeparator does not seem to update with the new value

### ISSUE THREAD

**Issue by alonsodiaz** [s-yadav/react-number-format#114]
Hello!

First of all, thank you for a really great product. Keep up the good work. This saved my behind some time :)

I live in Sweden and I'm trying to number format a couple of numbers according to Swedish standard. It all works fine, until the decimalSeparator disapears for no good reason once a new value is updated from the state. I've tried this with and without a customInput and I get the same result.

`<NumberFormat value={this.state.value} thousandSeparator=" " decimalSeparator="," suffix={' kr'} />`
**Note** that the first render is OK, it's when the state.value is updated, where the problem appears.

Can you please advice?

Thank you in advance!

**Comment by s-yadav** [comment]
If you make the NumberFormat controlled, then you should also pass onValueChange . See https://github.com/s-yadav/react-number-format#maintaining-change-value-on-state

**Comment by alonsodiaz** [comment]
Thank you @s-yadav. I did sent the onValueChange into the customInput. Do I connect the onValueChange to the onChange function on a HTML Input or is the onValueChange a stand alone thing?

**Comment by alonsodiaz** [comment]
Aaaha, now I get how that works! :) This is my first fue month with React - thick headed still :)

**Comment by alonsodiaz** [comment]
Okej, I've tried it with and without onValueChange, and different types, both Input and as text, the problem persists.
First render:
3,58 %
Second render (new state value feeded):
359 % (it should say: 3,59 %)

I'll try to make an example instead. Might be easier to understand where I could be wrong.

**Comment by s-yadav** [comment]
Yes if you can set up an example. That will help.

**Comment by s-yadav** [comment]
Also check if you making state to a string '3.59' . If thats the case you to pass isNumericString = {true}.

**Comment by s-yadav** [comment]
This was probably because of incorrect documentation. Fixed it.
