### ISSUE TITLE
Component should be able to accept multiple decimal separator inputs

### ISSUE THREAD

**Issue by hristod** [s-yadav/react-number-format#115]
First, I'd like to say that this component saved me sooo much time! I very thankful for your work!

A short description of my problem, and maybe some other people's:

I have a field which is configured to use ',' (comma) as a decimal separator. When set the component to work this way by doing `<NumberFormat decimalSeparator={','} .... />`, it all works as expected, except it doesn't accept entering a dot instead.

What I think it should do is it'd accept both a "." and any custom decimal separator and convert to the custom one. Example in my case:

If I enter 4,0 it shoud show 4,0 and if I enter 4.0 it should show the same - 4,0. Right now, when I enter 4.0 it just becomes 40.

**Comment by apoca** [comment]
I think this component should support locale number format by country... In Europe (most of countries) comma is decimal separator. 12.000,00 euros or € 12 000,00

**Comment by s-yadav** [comment]
@hristod In some cases '.' can be thousand separator, if we allow '.' to be typed (when thousandSeparator is '.' and decimalSeparator is ',') it will be hard to distinguish between the typed . and thousand separator. I don't see a problem that user has to type ',' if decimalSeprator is ',' .

@apoca It does provide decimalSeprator prop, finding a valid thousandSeparator and decimalSeparator based on locale is left on the app.

**Comment by apoca** [comment]
@s-yadav Doesn't work... I think that in another issue i saw another user with same problem. But, I think we can provide this automatically using locale (intl).

**Comment by hristod** [comment]
@s-yadav I am working for a French client. In France, the decimal separator is "," but people are used to working on US websites too much and try to use the "." too. Another thing is that if you use a french keyboard that has a numpad, the dot under the numbers always sends "." so it wouldn't work... And that - in my opinion - is a big deal...

**Comment by hristod** [comment]
I am trying to capture the onKeyDown event before it reaches the component and change any '.' to a ','which will fix my problem, but I am struggling on how to do that. Any ideas?

**Comment by s-yadav** [comment]
You can't change the keyCode onKeyDown, what you can do is get selectionStart from the input and manually insert ',' there. Something like

```jsx
<NumberFormat thousandSeperator="." decimalSeperator="," onKeyDown = {(e) => {
  const {key, target} = e;
  const {selectionStart, value} = target;
  if (key === '.') {
     e.preventDefault();
     target.value = `${value.substr(0, selectionStart)},${value.substr(selectionStart, value.length)}`; 
  }
}}/>
```
But do note onKeyDown is not reliable on mobile browsers. In android chrome keycode is always 229.

**Comment by hristod** [comment]
Thank you so much! I will try this, hopefully it will resolve my problem :)

**Comment by s-yadav** [comment]
It's complicated to find the difference between a decimal separator and thousand separator when '.' is used as thousand separator and allowing '.' to be considered as decimal separator while typing. 
Also as onKeyDown is not reliable will not support this. This is how most of the formatting modules behave so we will continue the existing behaviour.

**Comment by apoca** [comment]
It’s a huge difference between “.” And “,” I’m not agree with this conclusion. I have two options make a pull request with some profound changes or I leave this repository... 

In Europe we have different way to represent currency formats, this is obviously described on intl iso paper.

**Comment by hristod** [comment]
@apoca If you have an alternative, I will be happy to switch, as I am also in Europe and this doesn't work for me.
