### ISSUE TITLE
Getting error on gulp build

### ISSUE THREAD

**Issue by dkaus1** [s-yadav/react-number-format#117]
![build-error](https://user-images.githubusercontent.com/20293103/32459724-96101866-c356-11e7-8081-b8c418741376.PNG)

I was prior using version 2.0.4 and build was getting successful. Now it is failing and giving above error.  I am blocked due to this.  configuration in .babelrc is as below

{
  "presets": ["react", "es2015"],
  "plugins": ["transform-object-assign", "transform-flow-strip-types"],
  "env": {
    "development": {
      "plugins": [["react-transform", {
        "transforms": [{
          "transform": "react-transform-hmr",
          "imports": ["react"],
          "locals": ["module"]
        }]
      }]]
    }
  }
}

Please provide solution to get rid of this error.

**Comment by s-yadav** [comment]
It looks like some issue with your .babelrc. Can you show that one? 
Also, node modules generally have transpiled version of the lib which should not be parsed again from babel. You should exclude node modules in your webpack / gulp configuration.
