### ISSUE TITLE
Negative number?

### ISSUE THREAD

**Issue by Rixuel** [s-yadav/react-number-format#12]
Does react-number-format allow negative number?

Why negative number is converted into positive number?

**Comment by s-yadav** [comment]
Write now only positive numbers are supported. This needs to be fixed. Will keep it on milestone 1.3.0

**Comment by s-yadav** [comment]
Done

**Comment by SopanGhogare** [comment]
Hi Sudhanshu,
I used your react-number-format library , but after entering negative value , i am not able to remove "-" (Negative sign) from amount by pressing backspace or delete.
I notice it only happen when i use prefix for ex i use "$".
Below is the my code look like.Any idea how should get ride of it Thanks in Adv.

<NumberFormat
                            name="amount"
                            style={{fontSize: getFontSize()}}
                            customInput={TextField}
                            allowNegative={true}
                            thousandSeparator={true}
                            decimalSeparator={'.'}
                            decimalScale={2}
                            fixedDecimalScale={true}                            
                            autoComplete="off"
                            fullWidth={true}
/>

**Comment by SopanGhogare** [comment]
Hi Sudhanshu,
I used your react-number-format library , but after entering negative value , i am not able to remove "-" (Negative sign) from amount by pressing backspace or delete.
I notice it only happen when i use prefix for ex i use "$".
Below is the my code look like.Any idea how should get ride of it Thanks in Adv.

<NumberFormat
                            name="amount"
                            style={{fontSize: getFontSize()}}
                            customInput={TextField}
                            allowNegative={true}
                            thousandSeparator={true}
                            decimalSeparator={'.'}
                            decimalScale={2}
                            fixedDecimalScale={true}                            
                            autoComplete="off"
                            fullWidth={true}
/>
