### ISSUE TITLE
user can able to enter nothing in text field in edit form where i have pass some value from db

### ISSUE THREAD

**Issue by mglrahul** [s-yadav/react-number-format#120]
Hi, 

First thanks for providing this library.

I am facing a issue, my issue is i have used your library to add number value in my application, it works good on add form, but it doesn't work properly on edit form, on edit form i have passed some value from database. On edit form it gives error and print the NaN in text field.

i try many options but nothing works. I am attaching the code below.

[<NumberFormat thousandSeparator={true}  
                                        decimalScale={0} 
                                        className="form-control input-txt-alginment"
                                        id="goal-amount"
                                        name="annualAmount"
                                        value={someValueFromState}
                                        allowNegative={false}
                                        onValueChange={(values) => {
                                            const { floatValue } = values;
                                            onChangeAmountVal("annualAmount", floatValue)
                                        }} />](url)

Please take a look and let me know your thoughts.

**Comment by s-yadav** [comment]
I hope you have figured out the issue. If not the issue might be on `onChangeAmountVal` where its not setting the state which is passed as value prop.
Let me know if you still have the issue. Closing this one.
