### ISSUE TITLE
In number input if to press Ctrl+A and then type `.`, nothing happens 

### ISSUE THREAD

**Issue by khmelevskii** [s-yadav/react-number-format#121]
My input with following props
```
            thousandSeparator: true,
            prefix: '$',
            decimalScale: 2,
```
Where there is a value in input and I press ctrl-a and then I want to type decimal number, I need to press `.` two times as it doesn't work from the first time.

Also you can check it on your demo page

**Comment by 6degreeshealth** [comment]
I have this problem as well. I expect that selected text is overwritten on keypress. But, when decimalScale is set, it isn't overwritten.
