### ISSUE TITLE
IE Unspecified Error With Large Data Set

### ISSUE THREAD

**Issue by elijah1210** [s-yadav/react-number-format#127]
Hi,

I am receiving a strange error in IE. I use an enterprise level grid application that allows users to enter numeric values.

I traced it to setCaretPosition and it seems to occur after range.select is called.

This is what the range looks like.
![range](https://user-images.githubusercontent.com/23367979/33384922-4b88807a-d4f5-11e7-9f81-1bc23b74f35d.png)

However, the input is not empty. I am wondering if IE is having slowdown with the range.move?

The input looks like this when the error occurs.
![input](https://user-images.githubusercontent.com/23367979/33385086-c3f1d1b0-d4f5-11e7-86b0-ca4979ae37ba.png)

Regards.

**Comment by s-yadav** [comment]
I do not get what error exactly you are getting. Is it not setting proper caret position?
Also can show code, how you have used NumberFormat
and browser version.

**Comment by elijah1210** [comment]
Hi,

All I know is that IE throws an error saying "SCRIPT16389: Unspecified error"
I think it is attempting to call select before the cursor position has moved?

Browser version is IE 11.64.16299.0.

I am unable to show code, but I can attempt to explain it. It is being used inside a custom cell renderer framework in ag-grid. When there is a large number of rows in the table, there is a bit of delay upon entering the cell and selecting the contents of the cell. When doing quick data entry, at some point, it throws the IE exception shown above.

**Comment by nikhil-varma** [comment]
Closing this issue considering the inactivity. Please feel free to open this up or post any questions related to this. 🙂
