### ISSUE TITLE
setTimeout call on onFocus performance issue

### ISSUE THREAD

**Issue by Tasemu** [s-yadav/react-number-format#130]
The setTimeout call in onFocus() takes a while to go through. This is causing exponential lag issues on certain actions:

E.G:

quickly tabbing through multiple fields and adding values to each.

**Comment by s-yadav** [comment]
I don't think setTimeout with 0ms will be causing any lag. I can not reproduce it. Can you share more information regarding how you are using it? A screencast will also be helpful.
