### ISSUE TITLE
fixedDecimalScale=true & decimalScale=2 breaks overwriting selection

### ISSUE THREAD

**Issue by trbarrett** [s-yadav/react-number-format#134]
Hi there,

Version 3.1.0

I just ran into this issue were users were unable to select the text and type in (or paste) a new one. Either the number just appears in-font of the existing number, or nothing happens. After trying a few different options I nailed it down to "fixedDecimalScale={true}"  combined with "decimalScale={2}" causing the issue. 

To reproduce:

1. Go to https://codepen.io/lendinvesttristian/pen/eyOEvm
2. Type in a number in the first input box
3. Select the number (double click or drag and select)
4. Type a number, or paste a number

If you try that in the second or third input in https://codepen.io/lendinvesttristian/pen/eyOEvm, then typing or pasting a number works fine.

Cheers,
Tristian Barrett

**Comment by drinkwater99** [comment]
I have the same issue, is there any workaround ?

**Comment by pavelKozlov** [comment]
Possible soltuion: https://github.com/s-yadav/react-number-format/pull/152.

**Comment by s-yadav** [comment]
Fixed in the latest release. 3.1.4

**Comment by starcraft0429** [comment]
Thanks for update.
Btw, still issue is .
when I insert 50.42( %)
and select all number.

if I insert all different number, it works well.
but I start with same number(for example I was gonna 53.42) it was same issue with previous.

Hope to fix this soon
Thanks again.
