### ISSUE TITLE
isNumericString=true breaks decimal places

### ISSUE THREAD

**Issue by trbarrett** [s-yadav/react-number-format#137]
> If you are saving the value key on state make sure to pass isNumericString prop to true.

Version 3.1.0

Setting isNumericString to true stops decimal places from working. When you type a "." (full stop/period) the input swallows it and pretends it never happened.

Compare tying a number with a decimal in the first and second input of the following:

https://codepen.io/lendinvesttristian/pen/QaWGmN

As a work around, setting isNumericString to false fixes the issue.

**Comment by s-yadav** [comment]
Fixed on v3.1.2
