### ISSUE TITLE
Returns NaN0 with negative numbers between -9.5 and -9.9

### ISSUE THREAD

**Issue by LuciRebecca** [s-yadav/react-number-format#140]
**Version**: 3.1.2
Will always get NaN zero for numbers mentioned above. Problem seems to stem from this block of code in utils.js:
`const intPart = numberParts[0].split('').reverse().reduce((roundedStr, current, idx) => {
    if (roundedStr.length > idx) {
      return (Number(roundedStr[0]) + Number(current)).toString() + roundedStr.substring(1, roundedStr.length);
    }
    return current + roundedStr;
  }, roundedDecimalParts[0]);`

**Comment by ilyamerman** [comment]
+1

**Comment by s-yadav** [comment]
Fixed on v3.1.3
