### ISSUE TITLE
Value input and internal state issue

### ISSUE THREAD

**Issue by AvronNet** [s-yadav/react-number-format#141]
Hi,
I have a need to validate the value entered into this component, for example the user can only input integer numbers from 0 to 255 and I am doing a validation on the onChange event, if the value is out of this range I do not update my store state and thus the value input into the NumberFormat component stays the same but as you use internal state for the input, the invalid entered value is still visible to the user.

Expected behavior should be that the users sees the value that is passed to the component, when that value does not change the user should not see any change.

The only workaround I have for this at the moment is to forceUpdate my parent component so that the NumberFormat get updated with the old value.

**Comment by s-yadav** [comment]
You should use isAllowed prop to do such validation. As the component hijack onChange event to do formatting, if you have custom logic onChange event it may not work as intended. 
isAllowed prop with combination of onValueChange

**Comment by AvronNet** [comment]
Works great, thank you.
