### ISSUE TITLE
getting unformatted value

### ISSUE THREAD

**Issue by jonathan-chin** [s-yadav/react-number-format#146]
according to #11 

> First parameter on onChange handler will be event object and second parameter will be nonFormatted value. Will add this on doc.

I can't reproduce this. in my testing, the second parameter is always undefined. instead, the onchange handler fires twice in quick succession. the first time with value = unformatted and the second time with value = formatted.

this is what I'm getting:
```
1
$1
12
$12
123
$123
1234
$1,234
12345
$12,345
```

I'm using 3.1.3

**Comment by s-yadav** [comment]
The api has changed a lot since. Check onValueChange prop and https://github.com/s-yadav/react-number-format#values-object
