### ISSUE TITLE
Bootstrap Support

### ISSUE THREAD

**Issue by andrralv** [s-yadav/react-number-format#147]
First of all congrats on the project, love this.

It would be great if it could be used along with Bootstrap, when you have to use FormatNumber as a component you rule out using the FormGroup component for styling input fields, I'm guessing the same happens for any other styling framework.

**Comment by s-yadav** [comment]
Check custom input example https://github.com/s-yadav/react-number-format#custom-inputs

**Comment by s-yadav** [comment]
Or just passing proper className will help you
