### ISSUE TITLE
Select all value chars doesn't work while focused in currency input

### ISSUE THREAD

**Issue by khmelevskii** [s-yadav/react-number-format#149]
Select all value chars doesn't work while focused in currency input (with the help of Tab)

https://codepen.io/s-yadav/pen/bpKNMa

**Comment by mmacaula** [comment]
@khmelevskii not sure if you're still interested in this but I had the same problem.  We're using a custom input and so I was able to work around the issue by not passing `react-number-format`'s `onBlur` to the child input.  What you give up is any attempt by the library at caret preservation for focus events I believe.

**Comment by s-yadav** [comment]
Fixed in v3.6.0
