### ISSUE TITLE
Replace 0 in start of value

### ISSUE THREAD

**Issue by Fi1osof** [s-yadav/react-number-format#150]
My input field must allow type "0010", but NumberFormat clean value.

![_056](https://user-images.githubusercontent.com/2550668/35362016-afa98c2e-0174-11e8-8618-82a3b586985a.jpg)

**Comment by Fi1osof** [comment]
Set format="####" solve mu issue.

**Comment by s-yadav** [comment]
Thats expected behaviour. Yes for your case defining format pattern make more sense.
