### ISSUE TITLE
First keystroke after selecting all input contents is ignored

### ISSUE THREAD

**Issue by arpl** [s-yadav/react-number-format#151]
Hi @s-yadav,

The issue is reproducible either by adding a `prefix` with length greater than 
one or a `suffix` of any length. A common scenario such as tabbing into the component
will select all and surface the issue.

Thanks in advance, 
I'll also dig into it but it's best you're also aware of it.

**Comment by jakubzloczewski** [comment]
the same behaviour for decimalScale={2} when tabbing into not empty input

**Comment by s-yadav** [comment]
Related to #134

**Comment by s-yadav** [comment]
Fixed in v3.1.4
