### ISSUE TITLE
Field type password

### ISSUE THREAD

**Issue by Fi1osof** [s-yadav/react-number-format#156]
Failed prop type: Invalid prop `type` of value `password` supplied to `NumberFormat`, expected one of ["text","tel"]

Want to <NumberFormat
    type="password"
    ...
/>

User may type only masked password, for example, 5 letters.

**Comment by s-yadav** [comment]
Why you need this for password? It will not allow to type characters other then number. You should use password input with maxlength attribute

**Comment by Fi1osof** [comment]
I want prevent not allowed chars, for example, allow only a-z0-9 and toggle view state (type= text or password)

**Comment by s-yadav** [comment]
React number format is just for number formatting. You should apply custom validation on a normal password input.
