### ISSUE TITLE
in 3.1.4 version still issue: fixedDecimalScale=true & decimalScale=2 breaks overwriting selection 

### ISSUE THREAD

**Issue by starcraft0429** [s-yadav/react-number-format#157]
Thanks for update to new version 3.1.4.
Btw, still issue is .
when I insert 50.42( %)
and select all number.

if I insert all different number, it works well.(for example 11.11)
but I start with same number(for example I was gonna insert 53.42) it was same issue with previous version.

Hope to fix this soon
Thanks again.

**Comment by s-yadav** [comment]
Fixed in v3.1.5

**Comment by starcraft0429** [comment]
Perfect
Good work
