### ISSUE TITLE
Decimal rounding

### ISSUE THREAD

**Issue by elyswanson** [s-yadav/react-number-format#158]
In V2, if I passed a value of let's say 12345.019 and set decimalPrecision={2} it would format to 12345.02

V3 doesn't round up as expected, it formats it as 12345.01 when setting decimalScale={2}

**Comment by s-yadav** [comment]
I tried this on latest build and it do give `12345.02`. Can you check this on codepen

**Comment by midnightcodr** [comment]
@elyswanson, I think you should check the data type of `value` passed to NumberFormat. For example, `"12345.019"` (as a string) would result in 12345.01 while `12345.019` (as a number) would be converted to 12345.02 if `decimalScale` is set to 2.
