### ISSUE TITLE
When you highlight text inside input and type, text is not replaced with new input 

### ISSUE THREAD

**Issue by MattBoatman** [s-yadav/react-number-format#159]
![screen shot 2018-02-13 at 5 12 45 pm](https://user-images.githubusercontent.com/3319285/36176608-2c6159c4-10e1-11e8-8545-9e0aef1188b4.png)
hitting `22` gives this instead of 22
![screen shot 2018-02-13 at 5 12 54 pm](https://user-images.githubusercontent.com/3319285/36176610-2d91754a-10e1-11e8-9cb3-3c4b0625554f.png)

This only happens when fixedDecimalScale is true.

**Comment by andreawyss** [comment]
It is independent of the value of fixedDecimalScale, it happens when decimalScale is different than 0.

**Comment by s-yadav** [comment]
@MattBoatman Are you trying this on the latest version v3.1.5. I think this has already been fixed.

**Comment by MattBoatman** [comment]
I was on the latest version. Still seeing the problem.

**Comment by Elliot128** [comment]
I run into a similar issue when selected a char and entering a decimal. The char is deleted but decimal is not added.

**Comment by s-yadav** [comment]
This one is sloved.
