### ISSUE TITLE
Nothing gets populated if parent uses setState to set a field

### ISSUE THREAD

**Issue by tommytcchan** [s-yadav/react-number-format#16]
I have a use case where I'm formatting a field, but I want to disable the button to continue unless the field is valid:

```
  handlePhoneChange(value) {
    console.log(value);
    this.setState({valid: value && value.length >= 10});
  }

...
                    <NumberFormat format="(###) ###-####"
                                  onChange={(e, value) => {this.handlePhoneChange(value)}}
                                  className="main-input"/>
```

However, whenever I call `setState` in my component, the field gets blanked out and user can't type anything in. I debugged it a bit and it turns out that `componentWillReceiveProps` is called and the `newProps.value` is null, which means it shows only an empty string.

Line 60 of `number-format.js`:
```        
value: this.formatInput(newProps.value).formattedValue
```

Any ideas here? Thanks

**Comment by s-yadav** [comment]
Because you have not passed value prop to NumberFormat.
