### ISSUE TITLE
Doesn't work with redux field

### ISSUE THREAD

**Issue by nourahassan** [s-yadav/react-number-format#164]
I tried to wrap the NumberFormat in redux-form/field but it doesn't get the value initialized or set although the inner input contains the correct value.

Here's the code: 

`       <Field name={this.props.fieldName} component={NumberFormat} customInput={TextField} 
                 hintText={this.props.title}
                 thousandSeparator={true} prefix={'$'}/>  
`

**Comment by Elliot128** [comment]
I think redux-form uses the onChange handler to modify form state. You will need to wrap the NumberFormat component to call props.onChange when NumberFormat.onValueChange occurs.

**Comment by BryceLarkin** [comment]
You pass the events object to onChange. Just in case anyone needed more clarification.
```javascript    
export default ({ inputRef, onChange, ...other }) => (
  <NumberFormat
    {...other}
    getInputRef={inputRef}
    onValueChange={(_, e) => onChange(e)}
    suffix="%"
  />
);
```

**Comment by JChiquin** [comment]
> You pass the events object to onChange. Just in case anyone needed more clarification.
> 
> ```js
> export default ({ inputRef, onChange, ...other }) => (
>   <NumberFormat
>     {...other}
>     getInputRef={inputRef}
>     onValueChange={(_, e) => onChange(e)}
>     suffix="%"
>   />
> );
> ```

Hi man, I tried using this Field component:
`function MyNumberFormat(props) {
  const { inputRef, onChange, ...other } = props;
  return (
    <NumberFormat
    {...other}
    getInputRef={inputRef}
    onValueChange={(_, e) => onChange(e)}
    suffix="%"
    />
  );
}

...

<Field
                name="liquidation_fee"
                component={MyNumberFormat} 
                customInput={TextField}
                style={{ width: '76%' }}
              />`

When I write in the input it returns the next error: Uncaught TypeError: onChange is not a function

PD: <Field/> is in a form decorated with redux-form
Sorry my english

**Comment by JChiquin** [comment]
> > You pass the events object to onChange. Just in case anyone needed more clarification.
> > ```js
> > export default ({ inputRef, onChange, ...other }) => (
> >   <NumberFormat
> >     {...other}
> >     getInputRef={inputRef}
> >     onValueChange={(_, e) => onChange(e)}
> >     suffix="%"
> >   />
> > );
> > ```
> 
> Hi man, I tried using this Field component:
> 
> ```js
> function MyNumberFormat(props) {
>   const { inputRef, onChange, ...other } = props;
>   return (
>     <NumberFormat
>     {...other}
>     getInputRef={inputRef}
>     onValueChange={(_, e) => onChange(e)}
>     suffix="%"
>     />
>   );
> }
> 
> ...
> 
> <Field
>    name="liquidation_fee"
>    component={MyNumberFormat} 
>    customInput={TextField}
>    />
> ```
> 
> When I write in the input it returns the next error: `Uncaught TypeError: onChange is not a function`
> 
> PD: `<Field/>` is in a form decorated with redux-form
> Sorry my english

I think I solved with this: `const { inputRef, input: {onChange}, ...other } = props;`

**Comment by davepacifico** [comment]
> > > You pass the events object to onChange. Just in case anyone needed more clarification.
> > > ```js
> > > export default ({ inputRef, onChange, ...other }) => (
> > >   <NumberFormat
> > >     {...other}
> > >     getInputRef={inputRef}
> > >     onValueChange={(_, e) => onChange(e)}
> > >     suffix="%"
> > >   />
> > > );
> > > ```
> > 
> > 
> > Hi man, I tried using this Field component:
> > ```js
> > function MyNumberFormat(props) {
> >   const { inputRef, onChange, ...other } = props;
> >   return (
> >     <NumberFormat
> >     {...other}
> >     getInputRef={inputRef}
> >     onValueChange={(_, e) => onChange(e)}
> >     suffix="%"
> >     />
> >   );
> > }
> > 
> > ...
> > 
> > <Field
> >    name="liquidation_fee"
> >    component={MyNumberFormat} 
> >    customInput={TextField}
> >    />
> > ```
> > 
> > 
> > When I write in the input it returns the next error: `Uncaught TypeError: onChange is not a function`
> > PD: `<Field/>` is in a form decorated with redux-form
> > Sorry my english
> 
> I think I solved with this: `const { inputRef, input: {onChange}, ...other } = props;`

You saved me a ton of time. Thanks!
