### ISSUE TITLE
Partial deletion of formatted data doesn't work

### ISSUE THREAD

**Issue by lexanth** [s-yadav/react-number-format#167]
With a NumberInput using a hash based format, you can't highlight part of the formatted string and delete it.

Example is in https://codesandbox.io/s/r7yw5lnvmp?module=%2Fsrc%2FFormattedNumber.js

e.g. format = "##-##-##"
value={123456}

If I highlight 4-56 and hit delete, I'd expect the formatted value to end up as 12-3. Instead nothing happens (whether controlled or uncontrolled).

**Comment by s-yadav** [comment]
This is implemented that way as custom format can have numbers in the format pattern, and after a partial deletion its hard to figure out that a number is a input number or a number from the format pattern.
