### ISSUE TITLE
Selected index varies on top/bottom half of input clicked

### ISSUE THREAD

**Issue by Elliot128** [s-yadav/react-number-format#173]
Click in an open area in the input to the right of the entered text.

If you click on the top half, the selected index is at the beginning.

Click on the bottom half, the selected index is at the end.

Example: https://codepen.io/elliotatRetireup/pen/mxXeJZ

**Comment by s-yadav** [comment]
If you are talking about vertical top and bottom, I guess its behaviour on all inputs, you can try it on any other input.

**Comment by Elliot128** [comment]
It only happens with this library. Happens with Firefox and Chrome. 

Click inside the box near the top, cursor is at input start. Click inside the box near the bottom, cursor is at input end.
