### ISSUE TITLE
number keyboard not display on mobile app

### ISSUE THREAD

**Issue by mahendrancse88** [s-yadav/react-number-format#176]

**Comment by s-yadav** [comment]
Can you give example how you are using it, input type should be tel to get the number keyboard

**Comment by mykhaliuk** [comment]
With an input type set to "tel" there's no opportunity to put negative (-) number. Would be nice to have the same effect like with an input within type='number' on mobile devices, but at the same time escape the regular expression -?(\d+|\d+\.\d+|\.\d+)([eE][-+]?\d+)? check.

**Comment by s-yadav** [comment]
Input type number does not allow to insert other characters which are required for formatting.
