### ISSUE TITLE
Documentation includes support for Typescript, but there are no type definitions

### ISSUE THREAD

**Issue by robbyemmert** [s-yadav/react-number-format#177]
The readme has instructions on how to import the library in Typescript. However, most Typescript compiler configurations will throw an error, because no type definitions are available.

There are no type definitions in package.json
There are no type definitions at @types/react-number-format

I would suggest one of the following
1. Remove the instructions for importing with Typescript
2. Add a quick disclaimer, telling people to create their own type definitions
3. Provide a type definition file

**Comment by s-yadav** [comment]
Its added now on v3.4.4
