### ISSUE TITLE
build fails - unknown plugin - "transform-runtime" - 3.3.3  version

### ISSUE THREAD

**Issue by amak07** [s-yadav/react-number-format#181]
Unknown plugin "**transform-runtime**" specified in "... node_modules\\react-number-format\\.babelrc" at 2, attempted to resolve relative to "... node_modules\\react-number-format"

**Comment by koswarabilly** [comment]
+1

**Comment by LeXuanTien** [comment]
+1

adding transform-runtime from https://babeljs.io/docs/plugins/transform-runtime/ appear new issue

![screen shot 2018-05-08 at 11 44 55 am](https://user-images.githubusercontent.com/3906860/39738431-5217dfd8-52b5-11e8-9e98-59f0dd33843d.png)

**Comment by emilkarl** [comment]
Anyone got a solution for this?

**Comment by svicalifornia** [comment]
I'm also getting a similar message, but in my case, it's:

    Unknown plugin "transform-object-assign"...

**Comment by svicalifornia** [comment]
@s-yadav Adding those Babel transforms to our own package.json files is not an acceptable workaround, as it would affect Babel compilation in our app code, causing any number of undesriable side effects.

Yours is the only library that is triggering these messages. You should either move the required transforms from `devDependencies` to `dependencies`, or add them in .babelrc only in the `development` environment.

**Comment by svicalifornia** [comment]
To those affected by this issue while using webpack, be sure to `exclude: /node_modules/` in your webpack rules for JS, JSX, TS, and TSX files. If not using webpack, configure your app build process similarly to avoid building the files inside node_modules, which should already be built when you run `npm install` or `yarn`.

**Comment by Kaushaljsathwara** [comment]
I'm getting the same issue. anyone finding the solutions of this error?

**Comment by s-yadav** [comment]
This has been fixed. babel-runtime is no longer a dependency
