### ISSUE TITLE
Prefix and format at the same time

### ISSUE THREAD

**Issue by hyposlasher** [s-yadav/react-number-format#186]
Cannot use prefix and format at the same time like:

`<NumberFormat prefix='+7' format='### ### ####' />`
// +7 123 456 7890

**Comment by s-yadav** [comment]
Prefix doesn't work with format pattern. But you can keep prefix added on format pattern itself. 
```jsx
<NumberFormat format='+7 ### ### ####' />
```

**Comment by Dictory** [comment]
But we have some problem: before printing we can\`t see prefix and start from 7123 but in input we get +7 712 3 ...

**Comment by s-yadav** [comment]
I am not sure, I understood what before printing means. Can you elaborate and give some examples to show what you are trying to achieve and with what code.
