### ISSUE TITLE
Allow removing minus sign with backspace key

### ISSUE THREAD

**Issue by Liooo** [s-yadav/react-number-format#187]
Currently pressing minus key in input field toggles negative/positive of the number which is the only way to remove once typed minus sign. While this feature is quite handy once get used to, it is not very intuitive for most of users to not be able to remove minus sign with backspace key.

It'd be nice if we could backspace-remove minus sign.

**Comment by s-yadav** [comment]
This happens when there is prefix or some formatting on the start. Will fix this.
