### ISSUE TITLE
Cannot write decimals. (with live demo)

### ISSUE THREAD

**Issue by janhoeck** [s-yadav/react-number-format#188]
Hello,

with this live demo (https://codesandbox.io/s/xr381184zo) it is not possible to write decimals. 

For example:
I want to write 10,45
When I have wrote 10 and then add a comma, then the new string "10," will be passes as value and will be converted back to 10.

Is there a workaround to get this fixed? 
It would be fixed for me, when you add a new onBlur event that will have the same props as onValueChange.

**Comment by s-yadav** [comment]
As mentioned in documentation if you are using `values.value` to set your state you should pass isNumericString={true}. And also make sure the initial value is converted to string. Otherwise use `values.formattedValue`

**Comment by janhoeck** [comment]
Thank you isNumericString works for me. Sorry that i have skipped this when I read the documentation
