### ISSUE TITLE
[onValueChange] Not called when last negative number is being deleted using backspace

### ISSUE THREAD

**Issue by racingrebel** [s-yadav/react-number-format#190]
From the 3.4.0 release notes:
> Will not call onValueChange if float value does not change. This will prevent calling onValueChange when intermediate character is input like decimal separator.

When typing the following:
'3' then '5' then '-',
It would display as '-35'.
Entering backspace will fire onValueChange for removing 5.
Entering backspace again will not fire onValueChange for removing 3 because the new floatValue will be undefined.

The component now cannot let the rest of the app know that its value changed. Also a problem if you wanted to tie this value to a Redux state.

This is a big problem for functions listening to this field for displaying error messaging, doing calculations, etc.

Not sure why we wouldn't want onValueChange to be called with intermediate characters. 
I believe that's the purpose of the isAllowed function.

**Comment by s-yadav** [comment]
But rethinking on this, that we might want to show the typed value as it is on some different element, in which case onValueChange trigger is required. I will see if there is any other fix for the initial issue `can't type decimal separator if using floatValue`.

**Comment by s-yadav** [comment]
Fixed this on v3.4.1. Let me know if there is any abnormal behaviour on the latest release.

**Comment by racingrebel** [comment]
Sounds great! Looking forward to testing it out. I will let you know if there are any issues. Thank you for addressing this issue so quickly!

**Comment by racingrebel** [comment]
So I finally have the chance to revisit this issue, and I noticed that this patch has not been published to npm yet. Could you please do that whenever you get a chance :)

**Comment by s-yadav** [comment]
Aaaahhh.. Missed. Published now.

**Comment by racingrebel** [comment]
Thank you! :+1:
