### ISSUE TITLE
How to use event handler properly

### ISSUE THREAD

**Issue by thewholuver94** [s-yadav/react-number-format#195]
Hi, I'm sure this is a problem with my understanding, but I can't figure out how to properly handle a change to the NumberFormat component (basically how to use my handler). I'm completely new to Reactjs, please play nicely with me :-)

The below works fine with an <input> component: 
`
return (
        <fieldset>
          <legend> Enter Phone Number </legend>
          <input
            value={this.props.number}
            onChange={this.handleChange}
            />
          <ValueField number={this.props.number} />
        </fieldset>
      );

`
But I can't figure out how to do the same with the <NumberFormat> component:

`
return (
      <fieldset>
        <legend> Enter Phone Number </legend>
        <NumberFormat
          isNumericString={true}
          format="(###) ###-####"
          mask=" "
          value={this.props.number}
          onValueChange={(values, e) => {
              const {formattedValue, value} = values;
              {handleChange(value)}
              }
          }
          />
        <ValueField number={this.props.number} />
      </fieldset>
    );`

**Comment by racingrebel** [comment]
It maybe a problem with how you are assigning the value of the component. If this.props.number never changes, then the value will never change. You might want to use this.state.number, and use handleChange to call setState with the new value.
Also, handleChange(value) should not have curly braces around it.

**Comment by thewholuver94** [comment]
Thank you so much for your response. Here is a [link to my full code](https://gist.github.com/thewholuver94/41ade43f2815d1a5f867919324d1766f) 

The handleChange function doesn't have access to setState because the state was "lifted" to the next common component ( <PhoneInputForm> ). I did this so that the <ValueField> and <InputBox> components will be updated synchronously, but I can't get the <NumberFormat> field to somehow pass flow of control/update to the handleChange function.

Thanks again for your help.

**Comment by racingrebel** [comment]
You were using this function:
`onValueChange={(values, e) => this.handleChange(values, e)}`
To call this function:
`  handleChange(e) {
    this.props.onNumberChange(e.target.value);
  }
`

As you can see the arguments do not line up. You are giving handleChange 2 arguments. As written, you are only using the first one 'values', but you are trying to read it as 'e' and event.

Here is a working version:
```javascript
class PhoneInputForm extends React.Component {
  constructor(props) {
    super(props);
    this.handleNumberChange = this.handleNumberChange.bind(this);
    this.state = {
      number: '222'
    }
  }
  handleNumberChange(number) {
    this.setState({number: number}); 
  }
  render() {
    
    return (
    <div> 
      <h1>
        My Phone App
      </h1>
      <h2>
        <InputBox 
          number={this.state.number}
          onNumberChange = {this.handleNumberChange} />
        <ValueField number={this.state.number}/>
      </h2>
    </div>
    );
  }
}
class InputBox extends React.Component {
  constructor(props){
    super(props);
    this.handleChange = this.handleChange.bind(this);
  }
  handleChange(value) {
    this.props.onNumberChange(value);
  }
  render() {
    
    const number=this.props.number;
    
    if(number.length > 10) {
      return (
        <fieldset>
          <legend> Enter Phone Number </legend>
          <input
            value={this.props.number}
            onChange={this.handleChange}
            />
          <ValueField number={this.props.number} />
        </fieldset>
      );
    } else {
      return (
      <fieldset>
        <legend> Enter Phone Number </legend>
        <NumberFormat
          isNumericString={true}
          format="(###) ###-####"
          mask=" "
          value={this.props.number}
          onValueChange={values => this.handleChange(values.value)}
          />
        <ValueField number={this.props.number} />
      </fieldset>
    );
    }
  }
}
function ValueField(props) {
  
  if(isNaN(props.number) || props.number == '') {
    return <p> </p>;
  }
  
  return <p> +1{props.number} </p>;
  
}
ReactDOM.render(
  <PhoneInputForm />,
  document.getElementById('root')
);
```

**Comment by thewholuver94** [comment]
That did the trick! Thanks for pointing out my mismatched number of arguments. Seriously appreciate you taking the time for that.

**Comment by racingrebel** [comment]
No problem!

**Comment by thewholuver94** [comment]
If you have time, maybe you can help me with another question I have about this library...

I'm trying to implement a feature that would allow me to type too many numbers but would would then remove the formatting. \<NumberFormat\> component doesn't allow the user to add more than 10 numbers.

I tried implementing this with a custom function passed through the format prop (instead of # hashes), but it breaks compatibility with the handleChange function for some reason. I saw the removeFormatting prop,  but I'm not sure if I can even use this to achieve my goal because of the previous problem. Any quick advice?

**Comment by racingrebel** [comment]
You can add an isAllowed prop like this:
`isAllowed={values => {return values.value.length <= 15;}}`

This will prevent you from entering more than 15 characters for example.

**Comment by thewholuver94** [comment]
That doesn't work, because the format prop
format="(###) ###-####"
seems to enforce only as many numbers as hashes.

I feel like the only way around this is passing a custom format function to the format prop.

**Comment by s-yadav** [comment]
_the format prop
format="(###) ###-####"
seems to enforce only as many numbers as hashes._
This is by design.
Yes you need to pass a custom format function for your case. Regarding `removeFormatting` prop you need it only when you want some number to be part of formatting. 

Check the custom formatter https://github.com/s-yadav/react-number-format/blob/master/custom_formatters/card_expiry.js for reference.

**Comment by thewholuver94** [comment]
Thanks for your help. I managed the custom format function. Here's the final product if you're interested.

https://gist.github.com/thewholuver94/ef43d718bf4e83104d08b46676d35756
