### ISSUE TITLE
Fill the input from right to left

### ISSUE THREAD

**Issue by TheoneLucas** [s-yadav/react-number-format#197]
Hi, I didn't see anything on the documentation about reversing the order of the component to start filling from right to left, so I'm leaving it here: In some countries, like Brazil, currency is typically filled from right to left, so is there a way to accomplish this or it would be a new feature? Thanks!

**Comment by s-yadav** [comment]
Just give `text-align: right;` to your input. You can pass className as prop and you can define that rule.

**Comment by chelsearoman-ca** [comment]
If I may clarify for @TheoneLucas, we would like to see the input filled in the reverse order. 
For example, I'd like to input `$ 12.34` but I would like the numbers to enter the input right to left as you write them like so: 
`$ 0.00` --`$ 0.01`--`$ 0.12`-- `$ 1.23`--`$ 12.34`

If I attempt to change the direction of the input from left to right, to `rtl` I lose the ability to use the decimal.

**Comment by TheoneLucas** [comment]
Yes, as stated by @chelsearoman-ca, I would like the numbers to fill from right to left, not align them.

**Comment by lutchobandeira** [comment]
Hey guys! I am interested in this feature as well. Did you find a solution?

**Comment by TheoneLucas** [comment]
@lutchobandeira Nope, I still think that it is responsability of the react-number-format to give an API to change it's own behavior, in this case the text direction. Given the number of thumbs up in this thread I stiil don't know why this thread was ignored and closed. I do think that this is an issue worth looking at and would love to hear from @s-yadav about a possible opening for implementation by the community, me included if needed.

**Comment by marlonmleite** [comment]
@s-yadav any position for this? I need this feature

**Comment by GabrielF9** [comment]
@s-yadav any update for this issue? @theonelucas you resolved this with another way?

**Comment by NicolasZim** [comment]
For everyone here(mainly if you are brazilian), check #366, there you will find the awnser.

**Comment by SanjivG10** [comment]
I did this. 
`<NumberFormat
            placeholder="0.00"
             decimalSeparator="."
             decimalScale={2}
            maxLength={8}
           format={rightToLeftFormatter}`

` const rightToLeftFormatter = (value: string) => {
    if (!Number(value)) return '';

    let amount = '';
    if (amount.length > 2) {
      amount = parseInt(value).toFixed(2);
    } else {
      amount = (parseInt(value) / 100).toFixed(2);
    }
    return `${amount}`;
  };
`

**Comment by AjinkyaBansode** [comment]
> If I may clarify for @theonelucas, we would like to see the input filled in the reverse order. For example, I'd like to input `$ 12.34` but I would like the numbers to enter right to left as you write them like so with padded leading zeros: `$ 0.00` --`$ 0.01`--`$ 0.12`-- `$ 1.23`--`$ 12.34`
> 
> If I attempt to change the direction of the input from left to right, to `rtl` I lose the ability to use the decimal.

import { useState } from "react";

const useCurrencyInput = (initialValue = "0.00") => {
  const [value, setValue] = useState(initialValue);

  const handleChange = (e) => {
    const { value } = e.target;

    let val = value.replace(/[^\d]/g, "");

    if (val === "") {
      setValue("0.00");
      return;
    }

    val = val.replace(/^0+/, "");

    while (val.length < 3) {
      val = "0" + val;
    }

    const integerPart = val.slice(0, val.length - 2);
    const decimalPart = val.slice(val.length - 2);
    const formattedValue = `${integerPart}.${decimalPart}`;

    setValue(formattedValue);
  };
  return [value, handleChange];
};

export default useCurrencyInput;
