### ISSUE TITLE
Extend Input props

### ISSUE THREAD

**Issue by mquandalle** [s-yadav/react-number-format#20]
Hello,

It seems to me that the only input prop that is support on `NumberFormat` is the `value` prop. I think it would be better to support any input prop (`placeholder`, `onFocus`, etc.) by extending the input props instead of replacing it — as it is done by `react-text-mask` for instance.

**Comment by s-yadav** [comment]
It do support all other input props as well.

**Comment by mquandalle** [comment]
I couldn't try because #19 was sort of blocking me. I got that impression only by reading the documentation, so maybe there is an opportunity to make that clear in the documentation.

Also, slightly tangential question, have you considered an API that would allow a `NumberFormat` user to provide its own `Input` component, for instance to integrate NumberFormat rules on a Material UI input such as http://react-toolbox.com/#/components/input ?
