### ISSUE TITLE
Delete key not working

### ISSUE THREAD

**Issue by mquandalle** [s-yadav/react-number-format#21]
Hello,

I've noticed a bug with the <kbd>Delete</kbd> key handling. Let's say I have an input field with the number `USD 1,000` in it. Let's use `|` to represent the cursor position.

Current State | Key pressed | Expected | Resulting state
----|-----|----|----
 `USD 1,|000` | <kbd>Backspace</kbd> |  `USD 1|,000` |  `USD 1|,000` (Correct)
 `USD 1|,000` | <kbd>Delete</kbd> |  `USD 1,|000` | `USD 1|,000` (Bug)

Does that make sense?

**Comment by s-yadav** [comment]
Its a bug. I will fix this. Thanks

**Comment by mquandalle** [comment]
Well actually on second though, I would say that the expected behavior is to delete a digit every time <kbd>Detete</kbd> or <kbd>Nackspace</kbd> is pressed, like so:

Current State | Key pressed | Expected
----|-----|----
 `USD 1|,500` | <kbd>Backspace</kbd> |  `USD |500` 
 `USD 1,|500` | <kbd>Backspace</kbd> |  `USD |500` 
 `USD |500` | <kbd>Backspace</kbd> |  `USD |500` 
 `USD 1|,500` | <kbd>Delete</kbd> |  `USD 1|00` 
 `USD 1,|500` | <kbd>Delete</kbd> |  `USD 1|00` 


This could be implemented by registering an handler `onKeyDown` to handle `event.keyCode` 8 (for <kbd>Backspace</kbd>) and 46 (for <kbd>Delete</kbd>).

What do you think @s-yadav?

**Comment by s-yadav** [comment]
Yes I a have done the same fix. Will push it with some other changes.

**Comment by s-yadav** [comment]
Somehow I feel, it's better to have your first case (that is just changing the cursor position). The second case seems visually wrong and confuses (at least to me).

**Comment by s-yadav** [comment]
@mquandalle  Can you cross check version 1.1.0-alpha or branch 1.1.0-alpha.

**Comment by mquandalle** [comment]
Version 1.1.0-alpha looks good to me (I've just read to code, not tested yet).

About my second suggestion, maybe this could be an option? At least in French, when the group delimiter is a blank space, moving the cursors doesn't make much sense.

**Comment by s-yadav** [comment]
Moving cursor does not feel very odd, but deleting a character not near to cursor feels odd, mainly when doing backspace, and behaviour of backspace and delete should be same just on other direction.
Lets keep the first case. Anyway as long user is able to delete we are ok.
