### ISSUE TITLE
Allow caret to be set to last position

### ISSUE THREAD

**Issue by JustWalters** [s-yadav/react-number-format#211]
I have an input with a prefx of "$" and a default value of "0". When users tab in, the caret is placed before the 0, and they have to manually delete it.

I would like the default caret position to be at the last position, before any suffix, or for everything in the field to be selected. Could that be added as an option? Alternatively, is there another way you can recommend to work around this?

**Comment by CodingDutchman** [comment]
I have a similar issue with prefix. When tabbing into a field with a prefix the auto-selection gets lost because the caret is moved to be after the prefix.

**Comment by Krappt** [comment]
Yes, i agree with that. The same problem

**Comment by s-yadav** [comment]
Fixed in v3.6.0
