### ISSUE TITLE
How do you turn off rounding?

### ISSUE THREAD

**Issue by milesalex** [s-yadav/react-number-format#212]
I dont want rounding. How do I turn it off?

**Comment by s-yadav** [comment]
Rounding only happens if you pass a initial value whose decimal scale is greater than the passed decimalScale prop. If you don't want rounding you can just trim the number to given decimal scale and pass it as value.

**Comment by SimonHausdorf** [comment]
@s-yadav I assume it's not something you plan to support in the future? Maybe as a prop like `roundDown`?

We use the library for financial numbers. Let's assume the user balance is 10.019, but we only allow to withdraw to 2 decimal places.

The number would now be round up and display the user 10.02 resulting in an error from the backend as 10.01 is the allowed amount.

**Comment by rahulgolwalkar** [comment]
Agree to @SimonHausdorf - we are having the same problem ..

The title of this issue might be wrong - however, the numbers are not being rounded .. instead they are just being trimmed to the x decimal places - kinda a bug in the library

**Comment by MylesWardell** [comment]
By default it should be a floor over round no? If there is going to be no option?
