### ISSUE TITLE
return wrong formatted value when use rederText

### ISSUE THREAD

**Issue by xyy94813** [s-yadav/react-number-format#215]
### use
```
<NumberFormatter
    thousandSeparator={true}
    allowNegative={false}
    renderText={formattedValue => (
      <span>{formattedValue || '--.--'}</span>
    )}
    value="A123"
    displayType="text"
/>
```

### except
```
<span>--.--</span>
```

### Received
```
<span>123</span>
```

### ENV
* react-number-format's version: 3.5.1

is it a bug？

**Comment by s-yadav** [comment]
You are passing `value="A123"` So it will just pick the numeric part of it. And your condition `<span>{formattedValue || '--.--'}</span>` adds 123 inside the span

**Comment by xyy94813** [comment]
Isn't this an invalid value? Why take the numeric part of the invalid string?

**Comment by s-yadav** [comment]
Because prefix / suffix or other formatting part can be a character. Which can be passed as value

**Comment by xyy94813** [comment]
Providing a transform API might be a better choice.

**Comment by xyy94813** [comment]
```
class NumberFormatter extends React.Component {

    defaultProps: {
        transform: global.parseFloat,
        // ...
    }
    // ...

    render () {
        // const formattedValue =  formatterValue(transform(value))...
    }
    
}
```
example:
```
<NumberFormatter transform={(vlaue) => {
 // do something
return value
}}  />
```

**Comment by s-yadav** [comment]
For your case transform method can be used on the parent component as well. I can't see much use case of this to be a API. If you have some word use case, we can brainstorm on this.
