### ISSUE TITLE
Update state from blur event

### ISSUE THREAD

**Issue by robaguilera** [s-yadav/react-number-format#216]
I have a slightly odd use-case.  What I'm trying to achieve is when a user blurs out of the component, I need to format their values to currency.  So if they type `100` or `100.7` and tab out, I need to format it to `100.00` or `100.70`.  

The issue I have is that even though I am changing the state of the component via the `onBlurHandler` and that value is correctly being passed in as a value to the `value` property on the `<NumberFormat>` component, the internal state of the `<NumberFormat>` component does not update.

Side note: I'm using the library `numeral` for the formatting.

```
  onBlurHandler = () => {
    const { value } = this.state;
    const formattedValue = numeral(value).format('0,0.00');

    this.setState({ value: formattedValue });
  }

  handleChange = ({ formattedValue }) => {
    this.setState({
      value: formattedValue
    });
  };

  render() {
    const { value } = this.state;
    return (
        <NumberFormat
          value={value}
          thousandSeparator
          disabled={disabled}
          decimalScale={2}
          allowNegative={false}
          onValueChange={this.handleChange}
          onBlur={this.onBlurHandler}
          isNumericString
        />
    );
  }
```
Is there something I'm missing?

**Comment by s-yadav** [comment]
So the reason is the float value doesn't change only the formatting. And here we check that 
https://github.com/s-yadav/react-number-format/blob/master/src/number_format.js#L137. 

You could just use fixedDecimalScale={true} to get expected behaviour.
