### ISSUE TITLE
Support "'" (single quote) as a valid thousandSeparator

### ISSUE THREAD

**Issue by gido** [s-yadav/react-number-format#22]
In locale `FR_CH` we use `'` as a thousands separator:

`1500250` -> `1'500'250`

**Comment by mquandalle** [comment]
@s-yadav, this feature request is somehow similar to #18, do you have any objection about allowing an arbitrary string instead of restricting this parameter to a white list?

**Comment by s-yadav** [comment]
No. I have worked on it. I will test and push it.

**Comment by s-yadav** [comment]
@gido @mquandalle  Lets track this on #18 .
