### ISSUE TITLE
Format "###.##" displays "." as soon as user enters input

### ISSUE THREAD

**Issue by sumit-meshmd** [s-yadav/react-number-format#226]
I have to display the user input as feet, inches. so i apply the format "**#ft ##.## in**". As i need inches to allow two decimals, i have the "**##.##in**". But as soon as user starts to input the textbox displays 

"**5ft .in**". 

How can i not display the decimal but allowing user to input decimal for inches.

**Comment by s-yadav** [comment]
The format pattern does not allow basic numeric formatting  (decimal separator) etc. One way is you can have two different input box and onEnter of first input focus on second input. 
You can also pass custom format method where you can handle this case. But you will have to write logic for format function and removeFormat function.

**Comment by nikhil-varma** [comment]
Closing this issue in consideration of the resolution provided. Please feel free to open this in case of any concerns or questions
