### ISSUE TITLE
Best way to reject a value

### ISSUE THREAD

**Issue by alanrubin** [s-yadav/react-number-format#23]
First, let me thank you for this great component.

One question I couldn't find an answer anywhere : I have a requirement to reject certain values - for example I have a maximum value I allow users to type in - if user tries to type more then that amount I should prevent them from doing it (by not accepting the value - i.e. - the user won't be able to enter that in the input). What is the best to way to implement that in your component?

I was expecting your component to behave as a controlled component but I see that even if don't trigger the onChange (and don't modify the "value" state), the component shows the new amount entered. Any suggestions on how to implement that behaviour? Thanks!

**Comment by s-yadav** [comment]
You can use custom format method. 
See example https://github.com/s-yadav/react-number-format#custom-format-method---format-credit-card-expiry-time

**Comment by alanrubin** [comment]
Not really, by using the custom format method I end with the following issues:

1. I lose the nice formatting you are doing above the number, I have to do the format by myself (in the way the component is written today I need to copy and paste your code to reproduce it)
2. There is no way to reject a value and returning the input to the previous value - when executing the format method, I have only the current value, not the previous value so I cannot set it back to how it was.

I think the best idea would be modifying the onChangeHandler method to run a custom function (maybe called "reject" ?) passing the new values, if that is true then you ignore the changes and do not set the new state. What do you think ?

**Comment by alanrubin** [comment]
You can see a sample implementation at https://github.com/alanrubin/react-number-format/tree/reject-implementation (still without tests). I can submit a PR if you think you want that in.

**Comment by s-yadav** [comment]
Yes, that will good to have. Can you add test, doc and example in the PR.

**Comment by ErwinLee10** [comment]
bumping this issue. I have a requirement to specify max value as well.

p.s : thanks for this great library.

**Comment by s-yadav** [comment]
Added this on 2.0.0 alpha version using isAllowed check. Closing this.

**Comment by Shivu08** [comment]
how can I give minimum value?
