### ISSUE TITLE
npm WARN react-number-format@3.6.1 requires a peer of @types/react@...

### ISSUE THREAD

**Issue by maullerz** [s-yadav/react-number-format#230]
Full text of warning:
`npm WARN react-number-format@3.6.1 requires a peer of @types/react@^0.14 || ^15.0.0-rc || ^15.0.0 || ^16.0.0-rc || ^16.0.0 but none is installed. You must install peer dependencies yourself.`

Added in this commit - https://github.com/s-yadav/react-number-format/commit/70e1a070209bb012c84aa32b2fee644445f5d082#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

No need to have this dependency in peerDeps. Typings required only on compile time.
Projects using `react-number-format` lib probably not use TypeScript, so they see that annoying warning.

**Comment by s-yadav** [comment]
Yes, that make sense. Will remove it.
