### ISSUE TITLE
[Request] Allow suffix to be a component

### ISSUE THREAD

**Issue by bernatfortet** [s-yadav/react-number-format#232]
I'd love to be able to pass use a custom component for the suffix. eg:

```jsx
suffix={<span style={{color: 'red'}}>USD</span>}
```

**Comment by s-yadav** [comment]
You can not add an element inside an input tag (Which NumberFormat renders). If you need custom theming for prefix/suffix you can always keep it outside of the element.
```jsx
<NumberFormat {...inputProps}/><span style={{color: 'red'}}>USD</span>
```

**Comment by bernatfortet** [comment]
FYI, 
I ended up using **[AutosizeInput](https://github.com/JedWatson/react-input-autosize)**  in order to have the suffix be just right to the growing number.
