### ISSUE TITLE
Default value not being passed to material.io TextField

### ISSUE THREAD

**Issue by gnikeht** [s-yadav/react-number-format#235]
Setting the defaultValue property to Number Format with a customInput does not displays the value on the Textfield.
function App() {
  const fax='(123)123-4567';
  return (
    <div className="App">
      <NumberFormat format="(###)###-####" customInput={TextField} margin="dense"
        name="fax" id="fax" label="Fax" type="tel"
        variant="outlined" 
        defaultValue={fax} isNumericString />
    </div>
  );
}

Here's a sandbox demo: https://codesandbox.io/s/j46rok801v

**Comment by gnikeht** [comment]
Note:  quoted complete code..
Setting the defaultValue property to Number Format with a customInput does not displays the value on the Textfield.

`
function App() {
  const fax='(123)123-4567';
  return (
    <div className="App">
      <NumberFormat format="(###)###-####" customInput={TextField} margin="dense"
        name="fax" id="fax" label="Fax" type="tel"
        variant="outlined" 
        defaultValue={fax} isNumericString />
    </div>
  );
}
`
Here's a sandbox demo: https://codesandbox.io/s/j46rok801v

**Comment by gnikeht** [comment]
Thank you, I was able to make it work by changing the state on KeyUp but will prefer to just use defaultValue like most other input components.  BTW I figured later on that it didn't matter if it was a customInput, like you mentioned it's just because  "there is no defaultValue support".

Again, thank you for you answer..

**Comment by s-yadav** [comment]
Added it on v4. Let me know if it works.
