### ISSUE TITLE
Using text instead of numbers

### ISSUE THREAD

**Issue by matheusml** [s-yadav/react-number-format#236]
One of the features of the lib, according to the README is:
"Formatting a input or a **simple text**."

I'm trying to use it with text, instead of just numbers, but I'm not getting it right. Is that a way to do it or the README is outdated?

Thanks!

**Comment by s-yadav** [comment]
Thanks for bringing attention. The module does not support formatting text. The line in the readme should have been `Format number in an input or as a text`. Will fix this.
