### ISSUE TITLE
want to remove previous zero

### ISSUE THREAD

**Issue by ninpeng0** [s-yadav/react-number-format#240]
I type 0003214 number at react-number-format.

but during change value on 'onChangeValue' event 002134 to 2134.

don't change value.

then occur to 'focus out' event
input text 002134=>2134

how to remove previous zero value in changeValue?

**Comment by s-yadav** [comment]
Not remove leading 0 while onChange is design decision as user might want to add non zero number before leading zero. 
One common use case is let say number is 100234. If user want to change it to 200234, and for that he will remove 1 from start causing leading zeros. In that case if we remove leading zero in onChange, the number will go 234 and user has to to type 200 again in the starting.

**Comment by ninpeng0** [comment]
OK. I got it. Thank you very much.
