### ISSUE TITLE
Value not change while select all value in input

### ISSUE THREAD

**Issue by gangwar1** [s-yadav/react-number-format#241]
Hi,
I am using  "react-number-format": "3.0.0".
while we select all value in input and press any number key, it not replace selected test with recent press key value.

Steps-
1.type value in input field like 12515441.
2. select all value either from mouse or Ctrl +A.
3. Now press any number like 9

Expected : it display only 9 value in test box.

Actual: it set the cursor position in start.
[https://codesandbox.io/s/qlrppr9z7w](url)

**Comment by s-yadav** [comment]
This is being fixed on the later versions. Try out the latest version.

**Comment by Vanderslice** [comment]
If you're using a customInput you may want to double-check that your custom input is passing the onKeydown through or calling it in its handleKeyDown.

**Comment by nikhil-varma** [comment]
Please try out our latest version for the fix. If it still doesn't fix the issue please feel free to open up this issue again or post your questions out here. Thanks!
