### ISSUE TITLE
ThousandSeparator issue

### ISSUE THREAD

**Issue by 4zuko** [s-yadav/react-number-format#243]
Hi guys,

With a new build (`v4.0.0`), following line fails:

https://github.com/s-yadav/react-number-format/blob/4b288cf521b8ccfeab403bb91047e8c15f1a405e/src/number_format.js#L473

It seems that is `webpack` issue:
```javascript
if (thousandSeparator) {
   var thousandsGroupRegex = (0, _utils.getThousandsGroupRegex)(thousandsGroupStyle); // --> This line fails
   beforeDecimal = beforeDecimal.replace(thousandsGroupRegex, '$1' + thousandSeparator);
} //add prefix and suffix
```

Error:
```javascript
TypeError: (0 , _utils.getThousandsGroupRegex) is not a function
```

I integrated `MaterialUI` [TextField](https://material-ui.com/demos/text-fields/) with NumberFormat:
```javascript
const NumberFormatCustom = (props: *): NumberFormat => {
  const { inputRef, onChange, unit, ...other } = props;

  return (
    <NumberFormat
      {...other}
      getInputRef={inputRef}
      onValueChange={values => {
        onChange({
          target: {
            value: values.value,
            name: other.name,
          },
        });
      }}
      suffix={unit}
      isNumericString
      thousandSeparator
    />
  );
};
```

**Comment by s-yadav** [comment]
This would happen only if your node_modules are not completely synced. Tested it on 4.0.0 and there is no build issue on that. 
- Can you try installing react-number-format again.
- Also make sure your build is not caching files

**Comment by 4zuko** [comment]
You're right. Thanks.
