### ISSUE TITLE
Field value is rendered as negative number (for even amount of digits) when suffix set as "-".

### ISSUE THREAD

**Issue by voogieJames** [s-yadav/react-number-format#245]
Hi,

We're using the NumberFormat component with the suffix prop as "-", like so:

`<NumberFormat suffix="-" />`

Every time the number of digits in the field is "even", the value is rendered as negative number.
See the snapshot of value printed out on field value change, below:

![screenshot_2018-10-31_at_15_02_51](https://user-images.githubusercontent.com/2909356/47793380-6c44b680-dd1e-11e8-9174-4f99ed118f71.png)

![screenshot 2018-10-31 at 15 10 16](https://user-images.githubusercontent.com/2909356/47793706-2cca9a00-dd1f-11e8-9e33-70718ff5203a.png)

**Comment by s-yadav** [comment]
That's weird. I will check this.
