### ISSUE TITLE
Add support for using parentheses instead of '-' for negative numbers

### ISSUE THREAD

**Issue by philbrowndotcom** [s-yadav/react-number-format#252]
It's very common in financial applications to express a negative number as ($111,222) as opposed to -$111,222.  Could we add a prop for this?

**Comment by s-yadav** [comment]
Will keep this as a low priority. But I will be happy to get a PR for this.

**Comment by hyperd** [comment]
@SamKirkland is there a reason not to submit a PR for the work you have already done?

**Comment by SamKirkland** [comment]
@hyperd I have a pull request already (see [PR291](https://github.com/s-yadav/react-number-format/pull/291))
Sudhanshu and I have been working on getting it merged, I'll take another look at his latest comments.

**Comment by kelvin1794** [comment]
hi @SamKirkland, did the PR get merged in the end?

**Comment by knguyen1794** [comment]
hi @SamKirkland and @s-yadav , may I ask if this has been merged?

**Comment by joelpoloney** [comment]
+1 can we get this merged as well? Thank you!

**Comment by archanapandiri** [comment]
Can we this PR merged please

**Comment by JoeySelahJr** [comment]
Would also like this merged

**Comment by briandelancey** [comment]
This'd sure be nice... sad to see it abandoned.

**Comment by s-yadav** [comment]
@briandelancey Since v5 this can be done outside of the lib. Added an example here.
https://codesandbox.io/s/parentheses-for-negation-forked-jn42cp

Also, update the customization doc to list this: https://s-yadav.github.io/react-number-format/docs/customization/#using-parentheses-to-express-negative-numbers
