### ISSUE TITLE
Malicious library flatmap-stream is a dependency because of nodemon

### ISSUE THREAD

**Issue by jpamarohorta** [s-yadav/react-number-format#253]
Malicious library `flatmap-stream` is a dependency. This library is malicious and it's not completely clear what it does as it is explained [here](https://github.com/dominictarr/event-stream/issues/116).

The problem lies with `nodemon` that is dependecy of this project. It has then the following nested dependencies: `pstree.remy` -> `ps-tree` -> `event-stream` -> `flatmap-stream`.

Given that nobody knows yet what this code really does, this can be problematic.

**Comment by s-yadav** [comment]
We can remove nodemon safely from dependency as it's no longer required.

**Comment by jpamarohorta** [comment]
Ok thanks. Created a PR that removes it.

**Comment by s-yadav** [comment]
Pushed the fix on 4.0.5
