### ISSUE TITLE
disabled/ readOnly props cannot be set on input fields as expected (typescript)

### ISSUE THREAD

**Issue by jamessimone** [s-yadav/react-number-format#257]
If I have a NumberFormat component like such:

`<NumberFormat decimalSeparator={props.decimalSeparator} displayType={"input"} disabled= {props.isDisabled}>`

I get a typescript compilation error: 

> Property 'disabled' does not exist on type 'InstrinsicAttributes & InstrinsicClassAttributes(NumberFormat)  

Same thing with readOnly.

I tried to get around this by using `getInputRef` but I can't override the existing input because this component is being constructed in a render() method and if I use `getInputRef` to replace the underlying input, I get another error: 

> Lambdas are forbidden in JSX attributes due to their rendering performance impact

Is there any way to set the the NumberFormat component to disabled / readOnly without using getInputRef?

**Comment by s-yadav** [comment]
I do extend the NumberFormat props from InputAttributes
https://github.com/s-yadav/react-number-format/blob/master/typings/number_format.d.ts#L30

**Comment by pabtab** [comment]
Hello, So Was the issue fixed?

**Comment by mmnavarr** [comment]
I am having a similar issue when trying to disable the input field. I made a PR to add the disabled prop into the project to allow for this functionality.

https://github.com/s-yadav/react-number-format/pull/285

**Comment by nathanshelly** [comment]
I can confirm that I experience the same issue in a large codebase I'm working in, though passing disabled works in a simple `create-react-app` example. Unfortunately not sure exactly what in the larger codebase is breaking this behavior.

I know that's not particularly actionable just wanted to clarify that it seems to be more complicated than completely broken or completely fine.
