### ISSUE TITLE
Cb value can return a non-number

### ISSUE THREAD

**Issue by Elliot128** [s-yadav/react-number-format#26]
Not sure if this is expected/wanted, but I find it complicates my use case.

If you insert just '.' to the `NumberFormat`, you get as a response value '.'. Trying to convert to a number with `Number()` yields `NaN`. 

I would expect to get back 0 in this case. Makes handling the response simpler as we can always expect a number.

**Comment by s-yadav** [comment]
Yes, it should. There are couple of issues related to this. Will fix this on 1.2.0. This requires standardising input value and callback value.

**Comment by s-yadav** [comment]
This been standarized on 2.0.0 beta version. Closing this
