### ISSUE TITLE
Custom decimal separator is not working (european style)

### ISSUE THREAD

**Issue by Lysander** [s-yadav/react-number-format#261]
When I define the component like this I don't get decimal separator to work at all. It is invisible, gone after typing:

```
      return (
        <NumberFormat
          {...other}
          getInputRef={inputRef}
          onValueChange={values => {
            onChange({
              target: {
                value: values.value
              }
            });
          }}
          allowNegative={false}
          decimalSeparator={","}
          decimalPrecision={2}
          thousandSeparator={"."}
          suffix={"€"}
        />
      );
```

Also I got this warning
React does not recognize the decimalPrecision prop on a DOM element.

But the main thing is that decimal separator does not work.

I want to be able to enter 12,25€ value but at the moment it is formatted to 1.225€

_Originally posted by @atipi in https://github.com/s-yadav/react-number-format/issues/191#issuecomment-448151521_

You can try yourself: https://codesandbox.io/s/5x490556vk

Just enter a value and you will get an error!

    The above error occurred in the <NumberFormat> component:
        in NumberFormat (created by NumberFormatCustom)
        in NumberFormatCustom (created by InputBase)
        in div (created by InputBase)
        in InputBase (created by Context.Consumer)
        in WithFormControlContext(InputBase) (created by WithStyles(WithFormControlContext(InputBase)))
        in WithStyles(WithFormControlContext(InputBase)) (created by Input)
        in Input (created by WithStyles(Input))
        in WithStyles(Input) (created by TextField)
        in div (created by FormControl)
        in FormControl (created by WithStyles(FormControl))
        in WithStyles(FormControl) (created by TextField)
        in TextField (created by FormattedInputs)
        in div (created by FormattedInputs)
        in FormattedInputs (created by WithStyles(FormattedInputs))
        in WithStyles(FormattedInputs)

    Consider adding an error boundary to your tree to customize error handling behavior.

    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

**Comment by apuntovanini** [comment]
Bug is confirmed, just can't use the "," as decimal separator

**Comment by s-yadav** [comment]
As mentioned in doc
https://github.com/s-yadav/react-number-format#values-object
and Notes (6th point)
https://github.com/s-yadav/react-number-format#notes-and-quirks
values.value will be numeric string, if you are passing numeric string as value, you should set isNumericString={true} on the number format, so module can identify it's a formatted value or numeric string.

Here is the modified example of NumberFormat with Material UI for following case
https://codesandbox.io/s/2wr80zwlxy

**Comment by s-yadav** [comment]
@Lysander, @apuntovanini let me know if that solves your problem.

@Lysander, I was also not able to reproduce the error you posted on the codesandbox link you sent.

**Comment by apuntovanini** [comment]
@s-yadav you're right, sorry for not going through the docs well, it works with `isNumericString={true}`
FYI I can't reproduce @Lysander error too
