### ISSUE TITLE
On mobile input sequence with thousand separator messes up

### ISSUE THREAD

**Issue by nadzimo** [s-yadav/react-number-format#27]
When on mobile device with thousand separator set as comma, if I enter '12345' in that order the sequence becomes '12,354'. Should be '12,345'

**Comment by nadzimo** [comment]
just confirming that I've tried it on the codepen demo of this component and it's the same issue
http://codepen.io/s-yadav/pen/bpKNMa

**Comment by s-yadav** [comment]
Yes I can reproduce it. I will fix this.

**Comment by nadzimo** [comment]
thanks!
Do you have an estimate on when you plan to release the next version?

**Comment by s-yadav** [comment]
@nadzimo can you try and confirm 1.1.0 branch / 1.1.0-alpha2 release?

**Comment by nadzimo** [comment]
works fine now. Thanks!

**Comment by nadzimo** [comment]
it no longer works again. I tried v1.1.0, v1.2.0, they both have the same initial issue as reported.

**Comment by s-yadav** [comment]
@nadzimo have you tried 2.0.0-alpha

**Comment by nadzimo** [comment]
yes also tried it, same issue.
