### ISSUE TITLE
Allow value prop to set value always, not just initially

### ISSUE THREAD

**Issue by Elliot128** [s-yadav/react-number-format#28]
This would be useful as I pass a different value into this component than persists on the dom. For instance, this component's input can hold 00001, but I would pass this as a value=1 to prevent leading zeroes.

**Comment by s-yadav** [comment]
It is allowed to change value later on. See https://github.com/s-yadav/react-number-format/blob/master/src/number_format.js#L41
Is this not working ?

**Comment by Elliot128** [comment]
Here is an example where I'm passing in a value prop that isn't being displayed. This behaves as expected, since your readme specifies that the `value` prop only sets the initial value.

![screen shot 2017-02-08 at 8 55 35 am](https://cloud.githubusercontent.com/assets/14080426/22742510/9b7d8c7a-eddc-11e6-9f45-ec3c302db3e0.png)

**Comment by s-yadav** [comment]
Strange I tried this, and it works. Can you try with latest build

**Comment by Elliot128** [comment]
On 1.1.1 and this is still occurring

**Comment by s-yadav** [comment]
Can you setup a codepen / jsfiddle for it. ? Cant reproduce.

**Comment by s-yadav** [comment]
There is a possible fix on 2.0.0 alpha as now it block adding leading 0s.
