### ISSUE TITLE
I feel its ok to have a custom definition for the onChange API (Most of input component do this) instead of having another method to get values.

### ISSUE THREAD

**Issue by Ashish1857** [s-yadav/react-number-format#282]
I feel its ok to have a custom definition for the onChange API (Most of input component do this) instead of having another method to get values. 
The onChange will get a values object which have three different format of values
```js
{
  formattedValue: '$23,234,235.56', //value after applying formatting
  value: '23234235.56', //non formatted value as string, but it maintains the decimalSeparator provided, so if , is decimal separator then value will be 23234235,56
  floatValue: 23234235.56 //floating point representation. For big numbers it can have exponential syntax
}
```
Also this issue has been fixed so closing the issue

_Originally posted by @s-yadav in https://github.com/s-yadav/react-number-format/issues/45#issuecomment-315559265_

when there is change in any other props, this onChangeValue is getting called everytime. and the parameter "value" don't have the correct data, it lacks the understanding of separators 

Please help me out of this

**Comment by s-yadav** [comment]
@Ashish1857 That was my orignial comment, but later on decided to have different method, as the onValueChange can be triggered from multiple place, formatting props change, onChange, onBlur etc. 

Regarding the issue can you show some example code. Also if you can setup a codepen/ codesandbox . It will be much helpful to debug.
