### ISSUE TITLE
When set amount from ajax response, we dont have the amoun.. Any solution?? 

### ISSUE THREAD

**Issue by novayadi85** [s-yadav/react-number-format#283]
I have set state in **componentDidMount** after ajax success.
In render function outside we got the right value but inside **NumberFormat** it always get old state

**Comment by novayadi85** [comment]
I have set state in componentDidMount after ajax success.
In render function outside <NumberFormat/> we  got the right value but inside NumberFormat it always get old state

**Comment by s-yadav** [comment]
Can you show how you are using the NumberFormat component?

**Comment by novayadi85** [comment]
import React, { Component } from 'react';
import NumberFormat from 'react-number-format';
import axios from 'axios';
class Edit extends Component {
    constructor(props) {
        super(props);
        this.state = {
            post : {},
            alert: false,
            amountTest : 0,
            successs: []
        }
        this.componentDidMount = this.componentDidMount.bind(this)
    }

    componentDidMount(){
        const id = this.props;
        if(id){
            const { handle } = (this.props.match.params["slug"])
            var slug = (this.props.match.params["slug"]);
            var path = (this.props.location.pathname);
            if(slug){
                axios.post("/campagne/view",{
                    slug : slug,
                    method : path
                })
                .then(res => {
                    this.setState({
                        post: res.data.posts,
                        amountTest: 2000 // I tried make static number but still got 0 in display 
                    })

                    /* I get amount with "target" from from response  "post.target" should get float data from ajax response
                    // I have tried to update state amountTest with  this.setState({amountTest: 2000}); but still get 0
                    // but if I set amountTest = 2000 in construct , then e got right amount in render
                    */
                })    
            }
        }
    }
    render(){
        const {post , categories , amountTest} = this.state;
        // If I console.log(this.state) I got right amount but still 0 in NumberFormat
        return(
            <div className="row">
                <div className="col-xs-12 text-center">
                    <NumberFormat id="amount" thousandSeparator={'.'} decimalSeparator={','} onChange={this.onFieldChanged} name="amount" aria-label="Amount (to the nearest dollar)" allowNegative={false} className="form-control" defaultValue={this.state.post.target}/>
                    <NumberFormat id="amount" thousandSeparator={'.'} decimalSeparator={','} onChange={this.onFieldChanged} name="amount" aria-label="Amount (to the nearest dollar)" allowNegative={false} className="form-control" defaultValue={amountTest}/>
                </div>
            </div>
        );
    }

}

export default Edit

**Comment by thatbraxguy** [comment]
I believe the problem is you are passing `defaultValue`. If you want to change the value when you get the ajax response then try passing as `value`

**Comment by novayadi85** [comment]
Yup... Good Analize. thanks
