### ISSUE TITLE
Remove declare from number format typings

### ISSUE THREAD

**Issue by hexmar** [s-yadav/react-number-format#305]
https://github.com/s-yadav/react-number-format/blob/6a1113ff90ba69e479ec2b9902799f1ab2e69082/typings/number_format.d.ts#L4
Because of this `declare` I can use `value` variable anywhere in my project and typescript compiles it. But in runtime it fails with `Uncaught ReferenceError: value is not defined`.

**Comment by s-yadav** [comment]
Agree. A type definition should not affect global types. Happy to recieve a PR for this.
