### ISSUE TITLE
Half integer (i.e. 0.5, 1.5) rounding doesn't match `Math.round` when decimalScale is specified

### ISSUE THREAD

**Issue by daryl0313** [s-yadav/react-number-format#319]
Rounding half integer values is inconsistent from `Math.round` and also between when decimalScale === 0 and when decimalScale >= 1. Expectation is that rounding should match the output when using `Math.round`, which rounds up.

Currently it seems that negative rounding is broken when decimalScale is 0.  Instead of rounding up, it is rounding down or away from 0.  When value is positive it is correctly rounding up or also away from 0.

Alternatively, when decimalScale is 1 or more, this component is rounding half to the odd number.

### Current Behaviour

Value | `Math.round` | `decimalScale` === 0 | Expected When 0 | `decimalScale` === 1|Expected when 1 or `Math.round(x * 10) / 10`
 ----: | -------------: | ---------------------: | ------------------: | ---------------------:| -------:
-1.5    |                 -1 |                           -2 | `-1` |                                                        | 
-0.5    |                 -0 |                           -1 | `-0` |                                                        |
-0.15  |                     |                                | |                             -0.1                            | -0.1
-0.05  |                     |                                | |                             -0.1                            | `-0`
0.05   |                     |                                | |                              0.1                             | 0.1
0.15   |                     |                                | |                             0.1                              | `0.2`
0.5     |                  1 |                             1 |  1 |                                                            |
1.5     |                  2 |                             2 |  2 |                                                            |

**Comment by s-yadav** [comment]
the module uses .toFixed method.
Math.round and .toFixed are not always the same, its inconsistent across browser.
Check this out
https://stackoverflow.com/questions/566564/math-roundnum-vs-num-tofixed0-and-browser-inconsistencies 

Now the question is. Which one to use
.toFixed is used to give a fixed point notation which is what we want when the decimal scale is provided. 
Math.round is used for rounding, which is not what literally we are doing but it's more consistent.

**Comment by daryl0313** [comment]
Actually I'm thinking that maybe this library shouldn't be responsible for handling rounding/truncation and should only focus on formatting.

To get around my issue, I am just rounding before handing the value off to this component for formatting.  That way I can control floating point round issues and set the desired [rounding method](https://en.wikipedia.org/wiki/Rounding#Rounding_to_integer).
