### ISSUE TITLE
Feature suffix prefix ($ / € / %...)

### ISSUE THREAD

**Issue by Lyks-tech** [s-yadav/react-number-format#332]
Hey,

Thanks for the cool package.
I didn't find any possibility to let the component figure out whether it should use the prefix or the suffix according to the unit.

For instance, it would be cool that for this given input { value: "10", unit: "%" }
it detects the unit as a suffix, and for { value: "234", unit: "$" }, as a prefix.

```jsx
<NumberFormat
	value={data.value}
	suffix={data.unit}
	displayType={'text'}
	thousandSeparator={' '}
	decimalSeparator={','}
	isNumericString={true}
/>
```
So I get `10%` and not `%10`, or `5€` then `$5`

**Comment by s-yadav** [comment]
You will have to add that logic on the props.
Something like
```jsx
<NumberFormat
	value={data.value}
	suffix={shoudBeSuffix(data.unit) ? data.unit : ''}
        prefix={shoudBeSuffix(data.unit) ? '': data.unit}
	displayType={'text'}
	thousandSeparator={' '}
	decimalSeparator={','}
	isNumericString={true}
/>
```
