### ISSUE TITLE
How to format currency Brazil ?

### ISSUE THREAD

**Issue by cgarrotti** [s-yadav/react-number-format#333]
How to format currency Brazil ? Ex: 1.500,00 ?

**Comment by s-yadav** [comment]
@cgarrotti Can you provide more information on what is breaking? 
Custom thousand separator and decimal separator do work.

**Comment by s-yadav** [comment]
You have to pass `isNumericString={true}` to number format if you are saving `values.value`. Or use `values.formattedValue`

Its mentioned here. 
https://github.com/s-yadav/react-number-format#values-object

A corrected version of your code.
https://codesandbox.io/s/suspicious-lehmann-t7gr7
