### ISSUE TITLE
Losing React Material UI CSS

### ISSUE THREAD

**Issue by markcaplin** [s-yadav/react-number-format#335]
When using NumberFormat with React Material, none of the CSS classes of Material UI got applied. I had to manually add the class names. This mostly worked but the Material CSS class when focused still did not change the color of the Input Label or the underline to the focused color.  

<NumberFormat
        getInputRef={this.props.inputRef}
        className="MuiInputBase-input MuiInputBase-label MuiInputBase-root MuiLabelBase-root MuiInputLabel-animated "
        style={{ border: "none" }}
        value={this.props.value}
        onValueChange={input => {
          this.onChange({
            target: {
              value: input.value,
              name: this.props.name
            }
          });
        }}
        thousandSeparator
        prefix="$"
        decimalScale={2}
      />
    );

**Comment by s-yadav** [comment]
On such cases should use customInput prop.
