### ISSUE TITLE
Text strings must be rendered within a <Text> component.

### ISSUE THREAD

**Issue by isohanvanani** [s-yadav/react-number-format#344]
I am new to react-native and I installed `react-number-format` via npm.

When I used `<NumberFormat displayType="text" thousandSeparator={true} thousandsGroupStyle="lakh" prefix={'₹'} value={123456789}/>` component I got error as Invariant Violation Text strings must be rendered within a <Text> component.
Please refer screenshot.

![Screenshot 2019-09-19 at 4 24 53 PM](https://user-images.githubusercontent.com/43265432/65238320-0dd12400-dafa-11e9-87e8-0fecf7655ec8.png)

**Comment by s-yadav** [comment]
By default uses span tag to render string. You can use renderText prop to handle it in your way for react-native.

```jsx
<NumberFormat 
   value={123344}
  refix="$"
  thousandSeparator=","
 renderText={(value) =>  <Text>{value}</Text>}
/>
```
