### ISSUE TITLE
Phone number format is broken

### ISSUE THREAD

**Issue by umarashfaq** [s-yadav/react-number-format#346]
**Steps to reproduce:**

```
<NumberFormat format="+1 (###) ###-####" mask="_" value="+16155550162" />
```
**Expected output:**
```
+1 (615) 555-0162
```
**Actual output:**
```
+1 (161) 555-5016
```
[Click here for code sandbox](https://codesandbox.io/s/competent-architecture-f6x55?fontsize=14).

**Comment by s-yadav** [comment]
It's not broken. Partial formatting is not supported. With partial format it's hard to identify weather a numeric character is part of format or actual value. You should either remove +1 from the value or pass fully formatted value.
Remember to pass `isNumericString = {true}` prop to the NumberFormat when you remove `+1` from value.
