### ISSUE TITLE
Changing value with `fixedDecimalScale` causes Maximum update depth exceeded error

### ISSUE THREAD

**Issue by gabrielnaoto** [s-yadav/react-number-format#362]
I have a custom component that presets the default config for my project.

```js
import React from "react";
import NumberFormat from "react-number-format";

const CurrencyInput = ({
  value,
  onChange
}) => (
  <NumberFormat
    thousandSeparator="."
    decimalSeparator=","
    className="form-control"
    placeholder="R$"
    prefix="R$ "
    decimalScale={2}
    fixedDecimalScale
    onValueChange={({ value: rawValue }) => onChange(rawValue)}
    value={value}
  />
);

export default CurrencyInput;
```

But whenever I use it, with something like this. It does not work.
```js
 <CurrencyInput
    value={this.state.productValue}
    onChange={this.onChangeInput("productValue")}
/>
```

The issue occurs if I set the properties `value` and `fixedDecimalScale`. The component tries to format the scale, triggers `onValueChange` and then repeat.

Edit: If I don't provide a `value` to the component, it works just fine. But then, I can't set an initial value for editing purposes, for example.

Should `fixedDecimalScale` trigger `onChange`?

**Comment by gabrielnaoto** [comment]
It turns out the problem was not with the value, nor the fixedDecimalScale.

The problem was that I was defining `thousandSeparator="."`, `decimalSeparator=","`, which makes me parse the `value` before call `onChange`.

**Comment by jmcruzmanalo** [comment]
I'm having this same issue. Changing `decimalSeparator` to any character will cause this issue.

**Comment by annemacena** [comment]
> It turns out the problem was not with the value, nor the fixedDecimalScale.
> 
> The problem was that I was defining `thousandSeparator="."`, `decimalSeparator=","`, which makes me parse the `value` before call `onChange`.

What did you do to resolve?

**Comment by MatteoGauthier** [comment]
Does someone resolved this issue ?
