### ISSUE TITLE
allowLeadingZeros prop is not working

### ISSUE THREAD

**Issue by iloveip** [s-yadav/react-number-format#368]
As far as I understand, if `allowLeadingZeros` is not set to `true` it should not allow zeros at the beginning of the number. But it doesn't work. I even tried to set it to `false` explicitly, but I still can get a value like `00099999.00`.

Here is my code:
```
function App() {
  return (
    <div className="App">
      <NumberFormat
        thousandSeparator=" "
        decimalScale="2"
        isNumericString={true}
        fixedDecimalScale={true}
        allowNegative={false}
        //allowLeadingZeros={false}
        autoComplete="off"
      />
    </div>
  );
}
```

And here is a link to my [codesandbox](https://codesandbox.io/s/react-final-form-wcleave-test-4kmpy?fontsize=14).

How can I turn leading zeros off completely or limit it to only one zero before the decimal separator?

**Comment by redblue9771** [comment]
I found that it was not updated to dom in real time, unless it is focused outside the input component.

**Comment by s-yadav** [comment]
This is expected behaviour to not remove leading 0s while you are typing. 
On blur it gets fixed. People might 50002, and then to change it 20002 they have to delete 5 in which case removing leading 0 will be abrupt.

**Comment by iloveip** [comment]
Hi @s-yadav,

Thank you very much for your reply. I'm using `react-number-format` with `react-final-from`. I have added the following code to my component:

```
onBlur={props.input.onBlur}
onFocus={props.input.onFocus}
onChange={value => props.input.onChange(value)}
```
And now on blur leading zeros are removed from the input, but not from the values. Here is the link to the [example](https://codesandbox.io/s/react-final-form-wreact-number-format-4kmpy?fontsize=14). Is there any way to fix it?

**Comment by iloveip** [comment]
I have added `onValueChange={({ floatValue }) => props.input.onChange(floatValue)}` to the component based on this SO [answer](https://stackoverflow.com/questions/58774343/update-the-value-on-input-blur-in-react-final-form), and everything is working fine now.

Thank you!
