### ISSUE TITLE
Show mask after focusing the input

### ISSUE THREAD

**Issue by everlasting-neverness** [s-yadav/react-number-format#369]
Hello, can you help me please?

Is there a way to show mask (and put the caret to right position) when we just focus on input? And then if we focus out the input, hide the mask? Or the is an option just to always show mask?

I need to format phone number with '+7 (###) ###-####' mask, but when i focus on the input it shows no mask and only after user starts typing the mask appears and put user's value in the (###) field. 

My goal is to achieve the next: always show the user that "+7" is already set, and he will start his input inside (###), when he is focusing the input.

**Comment by s-yadav** [comment]
Humm, the requirement makes sense. I will see if we can incorporate this in the library.

**Comment by iloveip** [comment]
This feature is really needed. That's the only reason I have to use [another library](https://github.com/sanniassin/react-input-mask) for phone masks.

**Comment by s-yadav** [comment]
@iloveip @everlasting-neverness 
I forgot. This prop is already present. Set `allowEmptyFormatting` to true.

**Comment by iloveip** [comment]
@s-yadav Thank you. But then the mask is always displayed. Is there any way to show it only on focus?

**Comment by LeComptoirDesPharmacies** [comment]
Hi @s-yadav and @iloveip,

Same request here, being able to display mask only when input focused or have value would be really user friendly.

Yours faithfully,
LCDP

**Comment by iloveip** [comment]
Hi @s-yadav,

Could you please reopen the issue?

**Comment by ca11ado** [comment]
On current moment I have to show one input before focus (without mask) and replace it with second input on focus (with mask). A little bit frustrating :(

**Comment by giulianok** [comment]
here's my solution that works so far:

```jsx
const [showMask, setShowMask] = useState(false);

  return (
    <NumberFormat
      {...props}
      style={STYLES}
      allowEmptyFormatting={showMask}
      onFocus={() => {
        setShowMask(true);
      }}
      onBlur={() => {
        setShowMask(false);
      }}
    />
  );
```
