### ISSUE TITLE
DecimalPrecision not working with custom decimal separator

### ISSUE THREAD

**Issue by alexandrapersea** [s-yadav/react-number-format#37]
When having an input with custom decimal separator such as comma and decimalPrecision, the decimals are returned undefined or inaccurate.

### Example

 <NumberFormat thousandSeparator={'.'} decimalSeparator={','} decimalPrecision={2} />
 would return 
![screen shot 2017-02-28 at 11 36 40](https://cloud.githubusercontent.com/assets/17921522/23399823/5c0ce8dc-fdaa-11e6-9900-7d641e4fb94e.png)

This is mainly because the .toFixed js function doesnt work with comma as a decimal separator.

**Comment by atipi** [comment]
Hi,
When I define the component like this I don't get decimal separator to work at all:
```
      return (
        <NumberFormat
          {...other}
          getInputRef={inputRef}
          onValueChange={values => {
            onChange({
              target: {
                value: values.value
              }
            });
          }}
          allowNegative={false}
          decimalSeparator={","}
          decimalPrecision={2}
          thousandSeparator={"."}
          suffix={"€"}
        />
      );
```
Also I got this warning
React does not recognize the `decimalPrecision` prop on a DOM element.

But the main thing is that decimal separator does not work.
