### ISSUE TITLE
`floatValue` type should include `undefined` in TypeScript type definitions

### ISSUE THREAD

**Issue by nmalancea** [s-yadav/react-number-format#377]
When you delete the value (e.g. by using the `Backspace` key) `floatValue` is `undefined`. The type definition, however, says it can only be `number`.

The type definition needs to be updated to include `undefined` (`floatValue?: number` or `floatValue: number | undefined`), so that when strict mode is enabled in TypeScript, workarounds are not required.

**Comment by s-yadav** [comment]
This is already present `floatValue: number | undefined`
