### ISSUE TITLE
propTypes warning when RefObject assigned to getInputRef

### ISSUE THREAD

**Issue by Reeywhaar** [s-yadav/react-number-format#384]
When passing refObject (object created either by `react.createRef` or `react.useRef`) to `getInputRef`, propTypes spawn warning:
```
Warning: Failed prop type: Invalid prop `getInputRef` of type `object` supplied to `NumberFormat`, expected `function`.
```

Solution is to amend [propType](https://github.com/s-yadav/react-number-format/blob/ab97de9090997034da10d5b9d2794be1f0ea35d5/src/number_format.js#L61) to something  like described here https://github.com/facebook/prop-types/issues/240

Thank you!

**Comment by s-yadav** [comment]
Fixed.

**Comment by Reeywhaar** [comment]
Thank you so much!
