### ISSUE TITLE
onBlur should sanitize input accordingly.

### ISSUE THREAD

**Issue by lucianenache** [s-yadav/react-number-format#386]
**Usecase:** input field with only `-` typed gets rendered as `-0` expected is either `empty` or `default value`.

I have created a codepen to illustrate the issue:

https://codepen.io/cccccccccc/pen/LYVGmJK

**Usage:** 

1. Type `-` in the input field
2. unfocus the input field
3. The field gets rendered as `-0`, expected `empty` or `defaultValue` 

![image](https://user-images.githubusercontent.com/2980550/74544685-d733f400-4f47-11ea-9a42-dace2dbee0fa.png)

![image](https://user-images.githubusercontent.com/2980550/74544668-cdaa8c00-4f47-11ea-9fbf-df23ce74e299.png)

**Comment by s-yadav** [comment]
It should leave it as empty. I will check this.

**Comment by lucianenache** [comment]
super, thanks.
