### ISSUE TITLE
-Infinity formatted incorrectly

### ISSUE THREAD

**Issue by WPaczula** [s-yadav/react-number-format#388]
Hi,
-Infinity value with `decimalScale` prop causes input format to `-NaNNaNNaNNaN` instead of `-The solution would be not to use that prop in that case, but at the same time `-Infinity` value is changed to `-0` on blur.

Steps to reproduce:
1. Use `-Infinity` as a value with `decimalScale` prop for example equal to 2.
   - Input displays `-NaNNaNNaNNaN`.
2. Set `decimalScale` to false.
3. Focus the input.
4. Blur the input
   - Input displays `-0` instead of `-Infinity`

I'd be grateful if there was a way to display that value consistently. Cheers 👋

[![Edit mystifying-meadow-3o6lo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-meadow-3o6lo?fontsize=14&hidenavigation=1&theme=dark)

**Comment by s-yadav** [comment]
We can probably check for Infinity before adding that value in NumberFormat. NumberFormat doesn't support infinity. This is a very rare case where you end up as Infinity on the value.
