### ISSUE TITLE
decimalPrecision={false} allows decimals

### ISSUE THREAD

**Issue by cezar-gradinariu** [s-yadav/react-number-format#39]
Whenever I have decimalPrecision={false} as per doc, it still allows me to input decimals in, and in fact it allows to put huge number of them. 

It looks like a bug, Is this intended?

Cheers,
Cezar.

**Comment by alexandrapersea** [comment]
If decimalPrecision is set to false  it does not limit decimal place meaning it doesn't have a limit to how many decimals a user can type. If set to true/number if will limit to 2/the number specified. 

I think decimalSeparator is what you are meaning to use. If set to false it won't allow decimals in input.

Hope this helps!

**Comment by cezar-gradinariu** [comment]
Awesome! Thank you very much for clearing this out.

**Comment by s-yadav** [comment]
Decimal precision now only allow numeric value to make it less ambiguous. Updated it 2.0.0 alpha
