### ISSUE TITLE
type="password" with format; removeFormatting for Social Security component 

### ISSUE THREAD

**Issue by piperchester** [s-yadav/react-number-format#392]
Hello! I think `react-number-format` is an amazing lib and appreciate all the work maintainers have invested int it. 

I'd like to get maintainers' thoughts on using `format` in conjunction with `type="password"`.

### Problem Context
I'm working on building a SSN component, where I'd like to have both `mask`, and `format` being used. On each entry, I'd like to reformat the inputted number as a black password dot, **`•`**. So it might look something like:

```
// Initial mask and placeholder
000 - 00 - 0000
```

```
// First entry
•  -  -    
```

```
// Second entry
•• -  -    
```

and so on.

___

From my findings I'm evaluating a few different approaches:
1. Using `type="password"` with a custom `format` string
1. Leveraging the `removeFormatting` prop
1. Custom formatting logic (not use `react-number-format`)

### Approach 1: `type="password"` with `format="### - ## - ####"`

This doesn't seem to work as we can't set `type="password` explicitly, or that will make the formatted `-`s also the black password dots. For example,

```
// With type="password", the masked 'hypens' would just become
•••••••••••
```

Is this expected behavior? 

See this GIF for an example:

![ssn-format](https://user-images.githubusercontent.com/1530684/75806111-eaacd080-5d37-11ea-9e8f-9c91a9faebc3.gif)

### Approach 2: `removeFormatting`

I might be using this prop incorrectly, but it doesn't seem like the function that I'm passing to it is actually being invoked. 

```jsx
// Reproduction case
<NumberFormat
	removeFormatting={val => {
       debugger;
    }}
/>
```

### Approach 3: Custom formatting logic

I'm trying to avoid this approach as we lose all of the hugely valuable masking and cursor positioning logic.

Thank you!

### Details
- react-number-format@4.4.1

**Comment by s-yadav** [comment]
As format characters are also part of input character, if you define type="password" it will hide all the character. 
As far as I know there is no way of hiding partial characters with input tag.
