### ISSUE TITLE
Input loses focus when using a custom input

### ISSUE THREAD

**Issue by codemang** [s-yadav/react-number-format#400]
First I want to say thanks for all the hard work you guys put in!

I just started using this library, and I have a slightly complicated use case. I'm using Formik to generate my inputs, so I tried using the `customInput` option to specify how to render the input. I ultimately made an example that is very similar to this one: https://codesandbox.io/s/ppo1kvlwpx.

In that example, you'll notice that if you try to type in the input with placeholder `this doesn't work because you can't use onValueChange and customInput`, you actually can type a number, but the input loses focus after every keypress. I'm experiencing the exact same issue, so I was hoping you could shed light on what is causing that.

Thanks!

**Comment by s-yadav** [comment]
The problem is you are passing new Component reference on every render as customInput prop.
So react thinks its a new component and unmounts the previous input due to which it looses focus.

```jsx
customInput={inputProps =>
        console.log(inputProps) || <input type="number" {...inputProps} />
      }
```

Instead of this define the customInput outside of render method.
```js
const CustomInput = inputProps =>
  console.log(inputProps) || <input type="number" {...inputProps} />;
```

And then in jsx
```jsx
customInput={CustomInput}
```
Here's the fixed version https://codesandbox.io/s/formik-x-react-number-format-knn69

Keep in mind never create a new component inside a component, that breaks reconciliation condition in react.

**Comment by bryantee** [comment]
This just saved me a world of headache. Thanks @s-yadav! 🎉

**Comment by r-jalali** [comment]
import classes from "./ContactUsForm.module.scss";
import vars from "assets/styles/share.scss";

//pac:
import { useFormik } from "formik";
import { useTranslation } from "react-i18next";
import { Container } from "@mui/material";

//cmp:
import {
  CustomButton,
  SelectDropDown,
  CustomTextField,
} from "../../components";

//form:
import { validationSchema } from "./validationSchema";
import {
  clientDetails,
  companyDetails,
  request,
  request2,
} from "./contactUsList";

import { Fragment } from "react";

// Apis
import Contacts from "services/api/contacts";
import { NumericFormatCustom } from "components/common/NumericFormatCustom";

const ContactUsForm = () => {
  const { t } = useTranslation();

  const formik = useFormik({
    initialValues: {
      companyId: "",
      companyName: "",
      companyEmail: "",
      companyPhone: "",
      firstName: "",
      lastName: "",
      email: "",
      phone: "",
      subject: "",
      environment: "",
      apiVersion: "",
      message: "",
    },
    validationSchema: validationSchema,
    onSubmit: async (values, actions) => {
      try {
        await Contacts.createContact(values);
        actions.resetForm();
        actions.setStatus({ success: true });
      } catch (error) {
        actions.setStatus({ error: true });
      }
    },
  });

  const formFields = (
    item: IClientDetails | IRequest | ICompanyDetails,
    isSubjectReq: boolean
  ) => {
    const hasError =
      item.id in formik.touched &&
      item.id in formik.errors &&
      Boolean(formik.errors[item.id as keyof typeof formik.errors]);

    const errorMessage =
      formik.touched[item.id as keyof typeof formik.touched] &&
      formik.errors[item.id as keyof typeof formik.errors];

    switch (item.type) {
      case "text":
        return (
          <CustomTextField
            label={item?.placeholder}
            placeholder={item?.placeholder}
            name={item?.id}
            onChange={({ target: { name, value } }) => {
              formik.setFieldValue(name, value);
            }}
            value={
              item.id in formik.values
                ? formik.values[item.id as keyof typeof formik.values]
                : ""
            }
            error={hasError}
            helperText={errorMessage}
            {...{
              InputProps: {
                inputComponent: NumericFormatCustom as any,
              },
            }}
          />
        );
      case "select":
        return (
          <SelectDropDown
            id={item?.id}
            title={item?.placeholder}
            data={item?.data ?? null}
            onChange={selectOnChange}
            disabled={item?.disabled ?? false}
            isFullSize={isSubjectReq}
            hasError={hasError}
            errorMessage={errorMessage}
          />
        );
    }
  };

  const selectOnChange = (item: string, id: string) => {
    formik.setFieldValue(id, item);
  };

  console.count("render");

  return (
    <>
      <Container maxWidth="sm" className={classes.contact_us_form_wrapper}>
        {formik.status?.error ? (
          <span className={classes.error}>{t("contactUs.error")}</span>
        ) : formik.status?.success ? (
          <span className={classes.thanks}>{t("contactUs.success")}</span>
        ) : (
          <form
            onSubmit={formik.handleSubmit}
            className={classes.contact_us_form}
          >
            {/* Company Details */}
            <div className={`${classes.form_title}`}>
              {t("contactUs.formTitle.1")}
            </div>
            <div className={classes.form_group}>
              {companyDetails.map((item: any, idx: number) => (
                <Fragment key={idx}>{formFields(item, false)} </Fragment>
              ))}
            </div>
            {/* Client Details */}
            <div className={`${classes.form_title}`}>
              {t("contactUs.formTitle.2")}
            </div>
            <div className={classes.form_group}>
              {clientDetails.map((item: any, idx: number) => (
                <Fragment key={idx}>{formFields(item, false)} </Fragment>
              ))}
            </div>
            {/* req Details */}
            <div className={`${classes.form_title}`}>
              {t("contactUs.formTitle.3")}
            </div>
            {request.map((item: any, idx: number) => (
              <div
                key={idx}
                className={`${idx === 0 ? classes.subject_req_form : ""}`}
              >
                {formFields(item, idx === 0 ? true : false)}
              </div>
            ))}
            <div className={`${classes.form_group} ${classes.form_group_1}`}>
              {request2.map((item: any, idx: number) => (
                <div
                  key={idx}
                  className={`${idx === 0 ? classes.subject_req_form : ""}`}
                >
                  {formFields(item, true)}
                </div>
              ))}
            </div>
            <CustomTextField
              fullWidth
              sx={{ my: "20px" }}
              placeholder="תוכן הפניה"
              label="תוכן הפניה"
              multiline
              rows={4}
              name="message"
              value={formik.values.message}
              onChange={formik.handleChange}
              error={formik.touched.message && Boolean(formik.errors.message)}
              helperText={formik.touched.message && formik.errors.message}
            />
            <div className={classes.form_btn_wrapper}>
              <CustomButton
                type="submit"
                title={t("contactUs.submit")}
                height={48}
                disabled={formik.isSubmitting}
                backgroundColor={vars?.secondaryColor}
              />
            </div>
          </form>
        )}
      </Container>
    </>
  );
};

export default ContactUsForm;


Hey guys, focus looses when I type a char. I defined the custom componnet outside as a component but it does not work
