### ISSUE TITLE
avoid dist in the repo

### ISSUE THREAD

**Issue by sibelius** [s-yadav/react-number-format#411]
dist causes a lot of noise when reviewing pull requests

can we have a `prepublish` script to build the package when publishing to `npm`?

**Comment by s-yadav** [comment]
Yes, make sense. Will remove.

**Comment by s-yadav** [comment]
Note: We will have to update the cdn url in codepen demo. Currently it uses the dist file. Update it to use a distribution file from https://unpkg.com/

**Comment by nikhil-varma** [comment]
Closing this PR since we have removed the dist files as a part of PR #538
