### ISSUE TITLE
Cmd + Delete does not delete value when use decimalScale fixedDecimalScale and prefix props

### ISSUE THREAD

**Issue by xiaoyu-tamu** [s-yadav/react-number-format#420]
https://codepen.io/michael-li/pen/YzwGxJE

How to reproduce

1. type 123
2. delete all use `cmd + delete` or `ctrl + delete`
3. the cursor goes to first place but value didn't change

![image](https://user-images.githubusercontent.com/33362998/84721867-49910100-af47-11ea-80da-eeec82ade999.png)

when the cursor in the blue area, `cmd + delete` or `ctrl + delete` does not trigger onValueChange.

but `option + delete` works.

**Comment by s-yadav** [comment]
Not able to reproduce the issue. Seems it's no longer there on the latest release. Please reopen if the issue persists.
