### ISSUE TITLE
License Renaming

### ISSUE THREAD

**Issue by gyto23** [s-yadav/react-number-format#425]
I mention that License file is weird naming convention and might now follow the directory standards. I would suggest to consider this to be changed as:
```
MIT-LICENSE.txt > LICENSE
```

Let me know if you want me to contribute to changing the file name (of course if you dont have time to do it)

**Comment by s-yadav** [comment]
Make sense.  Will update. Thanks.

**Comment by s-yadav** [comment]
Done.
