### ISSUE TITLE
If I pass a float value the displayed value is incorrect

### ISSUE THREAD

**Issue by achimkoellner** [s-yadav/react-number-format#43]
Hi s-yadav, 
first of all: Thanks for sharing this npm module with the community!

I found a weird behavior, maybe I misuse the module? Added a Codepen below.
`
<NumberFormat 
            value={1255.123}
            decimalPrecision={2}
            thousandSeparator={'.'}
            decimalSeparator={','} />
`

rendered ouput "1.255.123,00"
exptected output: "1255,12"

http://codepen.io/achimkoellner/pen/YZemJZ

**Comment by psalchow** [comment]
I have the same problem when using '.' as thousand separator and ',' as decimal separator. My workaround is to use a string value. But this is not convenient.

**Comment by s-yadav** [comment]
Fixed in 2.0.0 alpha. Closing it. Open it again if it issue still exists.
