### ISSUE TITLE
If value doesn't change because it doesn't pass isAllowed condition, onChange still fires when onValueChange doesn't.

### ISSUE THREAD

**Issue by curtisburns** [s-yadav/react-number-format#435]
Since the event object isn't provided by the onValueChange handler, I need to use this in conjunction with onChange. Unfortunately one is firing when the other isn't which is causing issues. My thought was that as the value is not changing when not passing isAllowed, onChange shouldn't fire. What's the intended behaviour?

**Comment by s-yadav** [comment]
Humm, onChange shouldn't be called if isAllowed returning false. Looks like a bug.
Also, will be adding second parameter on onValueChange which will give event object based on where it is triggered from.

**Comment by nikhil-varma** [comment]
Hey, this issue is now fixed and merged. Thanks for reporting! Closing this issue!

**Comment by nikhil-varma** [comment]
This issue is nor fixed and released as a patch! Thanks for reporting! Closing this issue.
