### ISSUE TITLE
No way to round floats to integers

### ISSUE THREAD

**Issue by amaschas** [s-yadav/react-number-format#44]
I want to round off any decimal places to get the integer values of floats, and I've tried both of these options:

```
<NumberFormat value={15124.704000000258} displayType={'text'} thousandSeparator={true} decimalPrecision={0} />
<NumberFormat value={15124.704000000258} displayType={'text'} thousandSeparator={true} decimalSeparator={false} />
```

The results are:

```
15124.undefined
15,124,704,000,000,258
```

We should have some way to round the result off to `15124`.

**Comment by AvronNet** [comment]
This is the line (in number_format.js)  that is crucial to this:
beforeDecimal = parts[0];
afterDecimal = parts[1];
There should be a check here whether parts[1] exists and if it doesn't then don't add the decimal separator to the formatted value and no afterDecimal.

**Comment by s-yadav** [comment]
This is fixed now. Check 2.0.0 beta version
