### ISSUE TITLE
Setting max limit in currency?

### ISSUE THREAD

**Issue by c0d3x** [s-yadav/react-number-format#442]
I want to limit the number-input to allow the max amount of:
max={100000000000} so it cannot go higher.
How can I do this?

**Comment by c0d3x** [comment]
Think i found out using this:
https://codesandbox.io/s/react-hook-form-normalize-field-1jumn?file=/src/index.js

**Comment by s-yadav** [comment]
you should be able to implement it with `isAllowed` props.

**Comment by nikhil-varma** [comment]
@c0d3x We have added an example for the same use-case in the documentation. Please visit this link: https://github.com/s-yadav/react-number-format#limit-input-value-to-a-maximum-limit just
