### ISSUE TITLE
Wanted to remove leading zeros

### ISSUE THREAD

**Issue by faizhameed** [s-yadav/react-number-format#447]
I'm just reinstating the same issue again.
https://github.com/s-yadav/react-number-format/issues/240
But there is an obvious user accessibility improvement in this, especially when entering a percentage. 

in my case what I have done is
```

formatToNumber(val) {

    
    if (val.charAt(0) === '0' && val.charAt(1) !== '.' && val.length > 1) {
      console.log('replacing zero')
      val = val.replace(/^0+/, '')
    }

    return val + ' %'
  }
...
...
<TextField
                          label="management Fee"
                          id="managePrctgFee"
                          name="managePrctgFee"
                          value={props.managementFee}
                          onChange={this.props.handleChange('managePrctgFee')}
                          InputProps={{
                            inputComponent: NumberFormatCustom,
                          }}
                          inputProps={{
                            format: this.formatToNumber,
                            placeholder: '0 %',
                          }}
                        />

```
you can see i am replacing the zeros. It's working fine, but I am unable to add decimal point values. without this `format` prop I can add decimals, but now I cant. Can you suggest what to do

**Comment by s-yadav** [comment]
On blur does remove leading zero right? Can you be detailed on what the actual issue is on user accessibility?

**Comment by faizhameed** [comment]
Ok nevermind, it was a private repo, I changed my organisation recently. so Im closing this

**Comment by syed-yawar** [comment]
@s-yadav in my case I wanted to save value by clicking the **enter** key. but on pressing enter onBlur is not triggering. So I'd have to use onKeyDown and then I capture enter the key event. and by doing so I'm getting values with the leading zeros. Any way to call onBlur on pressing enter key?
