### ISSUE TITLE
onChange(event, value) value is incorrect

### ISSUE THREAD

**Issue by pablooneto** [s-yadav/react-number-format#45]
When i get the value argument, its a string, not a float. I used this: 
 ```<NumberFormat suffix=" &euro;" decimalSeparator="," thousandSeparator="." className="form-control"  value={2500.55} onChange={this.onNumberChange} />```

i think the value should be 2500.55 but it returns this string: "2500,55"

using an american format returns he same issue:
``` <NumberFormat prefix="$" className="form-control"  value={2500.55} onChange={this.onNumberChange} />``` ... returns string "2500.55"

**Comment by mquandalle** [comment]
Indeed, `react-number-format` returns the formatted string and not the expected value, see here: https://github.com/s-yadav/react-number-format/blob/7e9783eebcfa78d57a506b0de058eb718daf725e/src/number_format.js#L221

Also I think that hijacking the `onChange` callback to change it's signature is a bad API. There should be a proper method to get the number value.

**Comment by s-yadav** [comment]
I feel its ok to have a custom definition for the onChange API (Most of input component do this) instead of having another method to get values. 
The onChange will get a values object which have three different format of values
```js
{
  formattedValue: '$23,234,235.56', //value after applying formatting
  value: '23234235.56', //non formatted value as string, but it maintains the decimalSeparator provided, so if , is decimal separator then value will be 23234235,56
  floatValue: 23234235.56 //floating point representation. For big numbers it can have exponential syntax
}
```
Also this issue has been fixed so closing the issue
