### ISSUE TITLE
Safari iOS autofill with react-number-format allowEmptyFormatting

### ISSUE THREAD

**Issue by tanya94** [s-yadav/react-number-format#450]
Hello! I use ReactNumberFormat input with phone mask and `allowEmptyFormatting` prop. Safari on iOS offers to autofill value from contacts. But after autofilling input is again only with empty mask (with yellow background-color, because is was autocompleted).
Code example (a part of your live demo codepen):
```
<div className="example">
    <h3>
         Show mask on empty input (phone)
     </h3>
     <NumberFormat format="+1 (###) ###-####" mask="_" allowEmptyFormatting />
</div>
```
P.S.: If I use the same example without `allowEmptyFormatting` prop, value autofills correctly.

**Comment by olehslyniavuk** [comment]
+1 the same for google chrome autocomplete

**Comment by pavelspichonak** [comment]
Any updates?

**Comment by nikhil-varma** [comment]
The fix for this issue has been merged and released. Thanks again for reporting!

**Comment by biggieman** [comment]
Hello! the bug is still being reproduced in demo https://codepen.io/s-yadav/pen/bpKNMa

checked in chrome and yandex browser
