### ISSUE TITLE
Lose focus on input

### ISSUE THREAD

**Issue by Magofoco** [s-yadav/react-number-format#453]
I have created an input component (`InputComponent`) using `react-number-format`. This component accepts only a string numerical value with one decimal. Example: "12.5" or "12" but not "12.55". This works.

**However** when I use `InputComponent` to build another component (`BiggerComponent`), the input loses its focus on each key stroke.

https://codesandbox.io/s/festive-ishizaka-bvktl

**Comment by nikhil-varma** [comment]
@Magofoco Seems like that component is re-rendering and loosing the value. I am still working on figuring this out but looks like if I don't update the state, the value seems to be showing up just fine as the `InputComponent` does.  While debugging this, I also discovered that the value stays till the function handlers renders the `NumberFormat` component post updating the state but then it re-renders (_maybe as a new instance_) and the value vanishes with the input loosing the focus. 

I will keep you posted of any developments here. Would need sometime to figure this out! Meanwhile, if in case you happen to stumble upon any hunches/solutions, I'd be happy to hear about this. 

Hope this helps! Cheers!

**Comment by Magofoco** [comment]
@nikhil-varma 
I just solved it by moving the function that uses `NumberFormat` outside the Input function.
I think that if it is inside the Input function, the whole `NumberFormat` functions gets re-created at each key stroke. That why it looses focus.

**Not** working example: (with the function that uses `NumberFormat` **inside** the `Input` function)
https://codesandbox.io/s/festive-ishizaka-bvktl

Working example: (with the function that uses `NumberFormat` **outside** the `Input` function)
https://codesandbox.io/s/great-snow-1h3ln

**Comment by nikhil-varma** [comment]
@Magofoco Makes sense! Thanks for letting me know!

**Comment by rwb196884** [comment]
This is broken with MUI5

**Comment by imshuffling** [comment]
any joy with this?

**Comment by Volekss** [comment]
Every time the component re-renders, a new `customInput` function is created. This causes React to unmount the old input and mount a new one, which results in the input losing focus.

Wrapping the `customInput` function inside the `useMemo` made it work for me.
