### ISSUE TITLE
Result renderred with renderText function is missing className prop

### ISSUE THREAD

**Issue by fedulovivan** [s-yadav/react-number-format#456]
Since renderText receives only one argument with formatted text there is no way to pass unhandled props ("otherProps") down.
Imagine code is refactored from:
```js
<NumberFormat 
  displayType="text" 
  className="foo"
  value="123" 
/>
```
to:
```js
<NumberFormat 
  displayType="text" 
  className="foo"
  value="123" 
  renderText={formattedValue => <span>{formattedValue}</span>} 
/>
```
After refactoring class wont be renderred.

Proposal is to pass **otherProps** variable to renderText as well as **value**. (Im referring to [this line](https://github.com/s-yadav/react-number-format/blob/13e2fbb1825cf2b06ea3e209de3c55b846c2624a/src/number_format.js#L920))

**Comment by s-yadav** [comment]
Make sense. +1

I can see a usecase for this where renderText prop is provided dynamically based on some props.
But in simple case I will suggest to have those props directly on span.

**Comment by nikhil-varma** [comment]
@s-yadav Can I take this up?

**Comment by s-yadav** [comment]
Sure @nikhil-varma.

**Comment by nikhil-varma** [comment]
@s-yadav Noticing the name and keeping in mind backward compatibility, do you think keeping the name `renderText` is okay and pass another argument as `otherProps` or should we add a new Prop indicating that the method also returns the props with it?

**Comment by s-yadav** [comment]
We can use the same method and pass others props as second parameter.

**Comment by nikhil-varma** [comment]
@s-yadav Since the solution has been merged, can we close this issue?

**Comment by nikhil-varma** [comment]
@fedulovivan This issue has been fixed and merged! Closing this 🙂
