### ISSUE TITLE
Make decimal optional

### ISSUE THREAD

**Issue by ingro** [s-yadav/react-number-format#48]
Hello and thanks for this slick library! I have a request though:

I need to format a number like currency, so it should allow at the most 2 decimals but the should not be required.

So if I type, for example, `42` it should not add `.00`, but if the user begin to type decimal it should limit them to 2.

This can be achieved with the current version only with `decimalPrecision` set to `false` but in that way I can't limit the decimal to 2.

Do you think that could be a reasonable feature to add in the future?

Thank you.

**Comment by sercaninaler** [comment]
Oh please this is also what I need. +1

**Comment by s-yadav** [comment]
Coming up in v3.0.0

**Comment by s-yadav** [comment]
Code on master, will come on next release.
