### ISSUE TITLE
Issue with server-side-rendering (SSR)

### ISSUE THREAD

**Issue by rj-david** [s-yadav/react-number-format#481]
Seems like the changes in version 4.4.3 introduced this error which makes this package not compatible with SSR

```
ReferenceError: navigator is not defined
    at addInputMode (/project/node_modules/react-number-format/lib/utils.js:214:22)
    at NumberFormat.render (/project/node_modules/react-number-format/lib/number_format.js:1007:47)
```

**Comment by linhtv97** [comment]
Me too

**Comment by AbodyAmer** [comment]
Me too on version 4.3.0

**Comment by gustavocarvalho07** [comment]
Same here!

**Comment by rj-david** [comment]
@s-yadav hope you can check

**Comment by neosa** [comment]
Wtf? same problem

**Comment by s-yadav** [comment]
Shit. Will fix it soon.

**Comment by s-yadav** [comment]
@rj-david @gustavocarvalho07 Fixed on 4.4.4 

Let me know if the issue still persists.

**Comment by rj-david** [comment]
Confirming the fix. Thanks @s-yadav

**Comment by gustavocarvalho07** [comment]
It is working now! Thank you so much, @s-yadav !!!

**Comment by natterstefan** [comment]
Hi @s-yadav,

I am sorry to tell you that I have the bug still with `"react-number-format": "4.6.3"`. Can you still confirm that it's not an issue anymore?

Thanks for your time.
