### ISSUE TITLE
Externally setting state is not reflected in input value

### ISSUE THREAD

**Issue by masonforest** [s-yadav/react-number-format#482]
## Describe the issue and the actual behavior

When you call `setState` outside of the `onValueChange` callback the state is updated but the value of the input element isn't updated or displayed. You can work around this by manually setting the value using `getInputRef` and a `setTimeout`. Is this expected behavior? Is there a simpler work around?

I'm building a cryptocurrency wallet and I'm wiring up a "Enter Max" button which will save the user some typing.

## Describe the expected behavior

Clicking the "Set value to 1" under "Actual" on the following link should display "1" in the corresponding input box.

## Provide a CodeSandbox link illustrating the issue

https://codepen.io/masonforest/pen/YzGvWQR

## Provide steps to reproduce this issue

Click "Set value to 1" under "Actual" in the CodePen 

## Please check the browsers where the issue is seen
- [X] Chrome
- [ ] Chrome (Android)
- [X] Safari (OSX)
- [ ] Safari (iOS)
- [X] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
@masonforest On your codesandbox link you are passing wrong prop.
It should be value instead of state. Plus values has all the type of values.
https://github.com/s-yadav/react-number-format#values-object
```
      <NumberFormat
        value={state}
        onValueChange={(values) => setState(values.formattedValue)}
      />
```
