### ISSUE TITLE
Input should be cleared when received undefined value

### ISSUE THREAD

**Issue by LeComptoirDesPharmacies** [s-yadav/react-number-format#494]
## Describe the issue and the actual behavior
I have two input and a const base price : 
Input A => Rebate (percentage)
Input B => Price (currency)
Base price = 10.00

When I set 5.00 in input B, input A is updated to 50 (it means 50% discount from base price).
When I remove price in input B, rebate is set as 'undefined' in state.
Input B value keep the last value : 50.

## Describe the expected behavior
Input value should be blank as value is now undefined.

## Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/s/zen-jennings-zxc56?file=/src/App.js

## Provide steps to reproduce this issue
1. Write 5.00 in input B
2. Remove content of input B
3. Input A is not cleared

## Please check the browsers where the issue is seen
- [ X ] Chrome
- [ X ] Chrome (Android)
- [ X ] Safari (OSX)
- [ X ] Safari (iOS)
- [ X ] Firefox
- [ X ] Firefox (Android)

**Comment by Rey-Wang** [comment]
In earlier version, `NumberFormat` would only get cleared when set value to be null. After I upgrade to latest version `4.4.4`. it failed

**Comment by Rey-Wang** [comment]
Did a simple test, found it should be work before `4.4.2`

**Comment by nikhil-varma** [comment]
Thanks for reporting this issue. We will investigate and pick this up to provide a resolution soon. Keep an eye out for updates! :smile:

**Comment by nikhil-varma** [comment]
Hey, this doesn't seem like an issue in the library. The ideally it is not advised to pass `null` or `undefined` to clear out empty input fields when you want it to be controlled. The recommended way is to pass an empty string to clear it out. To get more information how input behaves and how React treats it please refer to this issue: #500 

Having said this, I will be closing this issue but feel free to comment in case of any question 😄
