### ISSUE TITLE
18 or more Decimal Scale

### ISSUE THREAD

**Issue by Dellybro** [s-yadav/react-number-format#495]
## Describe the issue and the actual behavior

When using a decimal scale of 18+ the decimals i input change. For example, if i am to put in the value 1.12, it fire an onValueChanged with 1.12 and then immediately fires another on Change with 1.11. 

## Describe the expected behavior

I would expect using 18 decimal scale that if i put in 1.12 the value would stay as 1.12 and not update to 1.11

## Provide a CodeSandbox link illustrating the issue

https://codesandbox.io/s/material-demo-forked-6jcgb

## Provide steps to reproduce this issue

- Use Material UI and NumberFormatField as the InputComponent
- Use isNumericString={true}

## Please check the browsers where the issue is seen
- [x ] Chrome
- [ x] Chrome (Android)
- [ x] Safari (OSX)
- [ x] Safari (iOS)
- [ x] Firefox
- [ x] Firefox (Android)

EDIT:

This only happens when isNumericString is set to true

**Comment by s-yadav** [comment]
This is some strange behavior. only happens for `.12`
@ParthS007, @nikhil-varma anyone wants to look into this.?

**Comment by nikhil-varma** [comment]
@s-yadav Sure! I can take a look at this. Shall I pick this up?

**Comment by nikhil-varma** [comment]
@s-yadav I have noticed it is happening for `.12`, `.15` and `.18`....

**Comment by nikhil-varma** [comment]
@Dellybro  @s-yadav This looks like a floating point issue with JS's `toFixed` :

In the `roundToPrecision` function, we are getting the `roundedDecimalParts`. This mis-behaves for a few cases as the video shows below:

<img src="https://im2.ezgif.com/tmp/ezgif-2-f8e1c9bad441.gif"  width="100%" />

The origination is from this line: `Math.ceil(parseFloat("0.".concat(afterDecimal || '0'))).toFixed(scale)` meaning that the `toFixed` method call has issues. This is basically a floating point issue with JS 😝 

Now for values like `.12`, `.15`, `.18` the returned outputs are `.001` less than the actual number. For eg: if the `afterDecimal` value is `12` -in our case, then the assigned value to `roundedDecimalParts[1]` would be `"119999999999999996"` and this would then be passed to `limitToScale` which will cap it to the scale provided. 

I am working on a fix for this and will keep you updated!

**Comment by Dellybro** [comment]
Thank you so much! I realized also if i take away "isNumericString" this works as expected so it has something to do with that boolean as well.

Also quick question, any way i can provide a max value for the field? I can't seem to find this in the documentation. If not is this an easy feature to implement?

Thanks so much!

**Comment by nikhil-varma** [comment]
@Dellybro This issue has now been fixed. While typing this issue shouldn't arise anymore. Closing this issue 😄

**Comment by dtp5** [comment]
In v4.5.1, the component still does not receive `onValueChange` events for `value`s exceeding ~15-17 decimals with `decimalScale={18}`.

```
<NumberFormat
    value={getValue()} // "1234.000000000001234567"
    decimalScale={18}
    thousandSeparator={true}
    onValueChange={(v: { value: string }) => { console.log(v) }}
/>
```
...produces `1,234.0000000000012`.
