### ISSUE TITLE
zero value isn't displayed

### ISSUE THREAD

**Issue by saidmoya12** [s-yadav/react-number-format#5]
Could you add prop for display zero values instance of empty?

Thanks!

**Comment by tsnolan23** [comment]
This would be useful for me as well!

**Comment by s-yadav** [comment]
@saidmoya12 @tsnolan23 What do you mean by display zero values ?

**Comment by tsnolan23** [comment]
@s-yadav If the `value` prop that is passed to the formatting component is equal to 0, it does not format the zero value.

For example, if I have this code:
```
<FormatNumber
    value={this.props.test}
    displayType={'text'} 
    thousandSeparator={true} 
    prefix={'$'} />
```

If `this.props.test` is equal to say 30000, the result would be $30,000, which is the intended functionality, however is `this.props.test` is equal to zero, it does NOT return $0, it returns nothing at all.

**Comment by abologna-r7** [comment]
Problem is with [line 127](https://github.com/s-yadav/react-number-format/blob/master/src/number_format.js#L127) since the following statement will be executed when value is 0:

`if(!val || !((val+'').match(numRegex))) return {value :'', formattedValue: (maskPattern ? '' : '')}`

**Comment by s-yadav** [comment]
@abologna-r7 Thanks for pointing it out. I will fix this.

**Comment by abologna-r7** [comment]
Thanks ;)

**Comment by krunal260299** [comment]
Is this fixed?

**Comment by FractalMind** [comment]
Any news on this? It's still an issue 9 years later
