### ISSUE TITLE
negative numbers are not working as expected

### ISSUE THREAD

**Issue by a-x-** [s-yadav/react-number-format#50]
the `-` sign is not showing

**Comment by amaschas** [comment]
Ditto on this. Seems to convert all values to positive for output.

**Comment by cidevant** [comment]
Warning: Unknown prop `allowNegative` on <span> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in span (created by NumberFormat)
    in NumberFormat (created by CurrencyFormatter)

**Comment by s-yadav** [comment]
@cidevant This warning should not come on the latest version.

**Comment by s-yadav** [comment]
@a-x- added negative number support let me know if you find any bug on that
