### ISSUE TITLE
onValueChange returns wrong values when using '.' as thousandSeparator and ',' as decimalSeparator

### ISSUE THREAD

**Issue by jafidiesel** [s-yadav/react-number-format#507]
#### Describe the issue and the actual behavior
**Issue**: onValueChange returns wrong values when using **'.'** as thousandSeparator and **','** as decimalSeparator

**Actual behavior:** externally the amount (value) of NumberFormat is set to 1.398,774 having **'.'** as  thousand separator and **','** as decimal separator but after onValueChange it returns this NumberFormatValues
`
{
floatValue: 1.398,
value: "1.398000",
formattedValue: "1,398000"
}
`

#### Describe the expected behavior
onValueChange should return
`
{
floatValue: 1.398 ,
value: "1.398,774",
formattedValue: "1.398,774"
}
`

#### Provide a CodeSandbox link illustrating the issue
https://codepen.io/jafibravin/pen/gOgamwZ?editors=0011

#### Provide steps to reproduce this issue
-set **'.'** as thousandSeparator and **','** as decimalSeparator
-update value from outside with 1.398,774 (eg.)
-check how onValueChange returns wrong values

#### Please check the browsers where the issue is seen
- [x ] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ x] Firefox
- [ ] Firefox (Android)

**Comment by nikhil-varma** [comment]
Thanks for reporting this issue. We will investigate and pick this up to provide a resolution soon. Keep an eye out for updates! 🙂

**Comment by jafidiesel** [comment]
After a lot of testing and pair programming i understood what was my error.

tl;tr be sure to update the NumberFormat value from the outside without the thousand separator if you use a different separator than the traditional one.

Despite the thousand separator being specified if you (for translation reasons like me) want to choose a different combination of decimal and thousand separators than the traditional, it will cause you trouble modifying the value from the outside (like a MAX button).

This library (as i understood) is meant to be used typing character by character and without the need to specify the thousand separator as you write (in fact as far as i tried i couldn't type it), so it makes a lot of sense to update the NumberFormat value without the thousand separator.

You may now close this issue @nikhil-varma

**Comment by nikhil-varma** [comment]
@jafidiesel Sounds good! Thanks for the update! Closing this issue 🙂
