### ISSUE TITLE
[4.5.2] With prefix, typed numbers appear with incorrect order

### ISSUE THREAD

**Issue by pandaiolo** [s-yadav/react-number-format#515]
**This bug is a regression from the latest commit, a431cd6c2091cc2fe87cabbb1803b63f54dbb49a . It addresses full selection replacement but disrupts caret placement.**

---

#### Describe the issue and the actual behavior

- When using tab to focus, or selecting all content in the input box, before typing a new value
- And when there is a prefix provided
- The caret after typing the first character is before that character instead of after, resulting in wrong values typed in
- For example:
  - "$1" is shown in the input
  - I select all the text
  - I type "10" (a "1", then a "0")
  - "$01" is displayed instead

Here is a screencast exhibiting the issue (from the code sandbox below):
![ScreenRecorderProject13](https://user-images.githubusercontent.com/1933404/112841671-abff5c00-9098-11eb-84ba-9df277dc56d9.gif)

#### Describe the expected behavior

- With the same actions, the typed number should display in the expected order
- For example:
  - "$1" is shown in the input
  - I select all the text
  - I type "10"
  - "$10" should be displayed, not "$01"
  
#### Provide a CodeSandbox link illustrating the issue

https://codesandbox.io/s/react-number-format-demo-forked-ip06e

#### Provide steps to reproduce this issue

- Use basic setup with a prefix, version 4.5.2 (4.5.1 works as expected)
- Value is 1 (shows "$1" if prefix is "$")
- Select all, or tab to focus
- Type "1"
  - Displays "$1" as expected
  - Caret is before 1 instead of after   
- Type "0"
  - Displays "$01" instead of "$10" 

#### Please check the browsers where the issue is seen
- [x] Chrome
- ? Chrome (Android)
- [x] Safari (OSX)
- ? Safari (iOS)
- [x] Firefox
- ? Firefox (Android)

**Comment by nikhil-varma** [comment]
Hey @pandaiolo! Thanks for reporting this issue.  We will investigate and pick this up to provide a resolution soon. Keep an eye out for updates!

**Comment by nikhil-varma** [comment]
Hey @pandaiolo this issue is fixed and released as a path v4.5.3. Thanks again for reporting! 🙂
