### ISSUE TITLE
Incorrect decimalScale behaviour with numbers less then e-7

### ISSUE THREAD

**Issue by AI111** [s-yadav/react-number-format#524]
with very small numbers rounding inside`decimalScale` works incorrect, it just skips the exponential part  

` <NumberFormat value={-3.1e-7}  decimalScale={2}    />`  will show `-3.00` instead of `0.00`

https://codepen.io/sasha-andreev/pen/KKaeKZP

**Comment by s-yadav** [comment]
Which version are you in. The codepen link seems to working, and the latest version has exponential number fixes

**Comment by AI111** [comment]
@s-yadav Codeepen was made from demo link
it uses the master branch 
![Screenshot 2021-04-16 at 15 09 48](https://user-images.githubusercontent.com/5594299/115022310-e43ed100-9ec5-11eb-894f-247df1f084d7.png)

**Comment by s-yadav** [comment]
I think it's picking up from cache. As the endpoint is not version managed. Can you clear cache and try. I don't get this error.

**Comment by s-yadav** [comment]
I will update it to pick from unpkg.

**Comment by AI111** [comment]
yep
you were right
it's an issue with the old version
