### ISSUE TITLE
How to reset value

### ISSUE THREAD

**Issue by doniyor2109** [s-yadav/react-number-format#528]
#### Describe the issue and the actual behavior
Currently `NumberFormat` works with `null` and `undefined` values. However when component updates with `null` or `undefined` value, it will look for previous value and preserves old value without reseting.

#### Describe the expected behavior
I have case where I use `null` as initial value and user can reset value again back to `null`. I try to set updated value as `null` however the old value still preserves. 

Is there any way to reset value back to nil value?

#### Provide a CodeSandbox link illustrating the issue
There is existing test case for this behavior. 

https://github.com/s-yadav/react-number-format/blob/3b2326a0ec026dae7f3a7fb7cf0372cf0a141570/test/library/input.spec.js#L64-L82

#### Provide steps to reproduce this issue
 - Set initial value to `null`
 - Type some numeric value
 - Reset value back to `null` programmatically
 
#### Please check the browsers where the issue is seen
- [x] Chrome
- [x] Chrome (Android)
- [x] Safari (OSX)
- [x] Safari (iOS)
- [x] Firefox
- [x] Firefox (Android)

**Comment by nikhil-varma** [comment]
Hey @doniyor2109 Thanks for reporting. A solution with the explanation of this behaviour is provided in this Issue: #500 . I would request you to please have a look at that to get an idea of how this can be achieved. I will be closing this in support of that explanation. Please feel free to add any questions/comments in case of any doubts. Thanks!

**Comment by w4t3r-45** [comment]
this is still the same even when trying the solution mentioned by @nikhil-varma  , passing a string is not resetting the value on the latest version , is there any kind of manipulation to reset the field please ?

**Comment by jnsdrssn** [comment]
Maybe this helps anyone using `react-hook-form`'s reset, this is what I ended up with:
(onValueChange and value)
```
 <Controller
      control={control}
      name={name}
      render={({ field: { onChange, onBlur, value, ref } }) => (
        <NumberInput
          aria-invalid={!!error}
          getInputRef={ref}
          onBlur={onBlur}
          onValueChange={({ formattedValue, floatValue }) => {
            onChange(formattedValue === "" ? undefined : floatValue)
          }}
          value={value ?? ""}
          {...props}
        />
      )}
    />
```
