### ISSUE TITLE
Not able to type decimal numbers when used in material ui textfield

### ISSUE THREAD

**Issue by thanmaic** [s-yadav/react-number-format#549]
#### Describe the issue and the actual behaviour
I tried to use the react number format component as inputComponent to the material ui textfield, not able to enter decimal numbers. When trying to input decimal numbers with (.) the textfield losses out focus. 

<img width="445" alt="Screenshot 2021-06-07 at 12 27 23 PM" src="https://user-images.githubusercontent.com/50735542/120973363-76f44180-c78c-11eb-83c6-cf96c89c6fc3.png">

#### Describe the expected behaviour
User should be able to type in decimal or whole numbers in the textfield

#### Provide steps to reproduce this issue
Use this library versions:
"react-number-format": "^3.6.2"
"@material-ui/core": "^4.0.0"
Use react number format component as Input component to material ui textfield and try to type in a decimal number. Once decimal(.) is typed in the textfield looses focus

#### Please check the browsers where the issue is seen
Checked on Chrome and FireFox, doesn't work.

This issue happens only when the react number format is used as input component to material ui text field,
Incase i use only material ui textfield with type number, then i am able to type in decimal numbers without any issue. I need some features like the thousand separator, currency and year format hence i am using react-number format library.

@s-yadav @nikhil-varma Could you please help to find a solution/work around to this issue at the earliest.

Thanks

**Comment by nikhil-varma** [comment]
@thanmaic Thanks for reporting. It would be helpful for the investigation if you can provide the code snippet that you're using to work with this. Thanks!

**Comment by vnd-ranga** [comment]
on iphone browse open numeric keyboard without decimal

**Comment by thanmaic** [comment]
I think this issue is with respect to the material ui textfield inside a popover component and mostly not related to react-number-format. Thanks. I will update on this soon.
