### ISSUE TITLE
How to show one value but the field value be different?

### ISSUE THREAD

**Issue by pedrohenriiz** [s-yadav/react-number-format#553]
In my form, there is some inputs for the price of a product, the discount value and the discount percentage. When a user types a value on discount value or discount percentage, a function is called calculating the discount percentage or discount value.

Example 1: Value 100 - Discount value 0 - Discount percentage 0

If the user changes the discount percentage to 10%, the discount value should change to 10. The same should happens if they change the discount value.

Example 2: Value: 100 - Discount value 10 - Discount percentage 10%

**The problem is:** 
For example, if I have the value 144 and the discount value is 11, the percentage is equal to 7.63888888889
_(11 * 100) / 144 = 7.63888888889_
But it shows only the 4 decimals (7.6389) on input, which is what I want, but I need the field value to be the complete number (7.63888888889) to verify if the discount is correct before sending it to the database. On OnValueChange function, the value has only the 4 decimals and doesn't have the complete number.

**What do I need**
So, I need to **show** only the 4 decimals but the **value** of the field should be the complete number.

This is an example of one of the components:
```jsx
<NumberFormat
  customInput={TextField}
  id="discount_percentage"
  name="discount_percentage"
  label={<IntlMessages id="order-items.discount-percentage" />}
  value={values.discount_percentage}
  displayType="input"
  inputProps={{ maxLength: 12 }}
  error={Boolean(errors.discount_percentage)}
  helperText={errors.discount_percentage}
  thousandSeparator="."
  decimalSeparator=","
  allowedDecimalSeparators=","
  isNumericString
  suffix=" %"
  allowNegative={false}
  decimalScale={4}
  fixedDecimalScale
  onFocus={event => event.target.select()}
  onBlur={() => {
    handleCalculateDiscount('discount_percentage');
  }}
  onValueChange={({ floatValue }) => {
    setFieldValue('discount_percentage', floatValue || 0);
  }}
/>
```

**More informations:**
If more information are needed, I could provide them.
- I'm using Formik and Material-UI
- My package version is 4.4.1

**Comment by s-yadav** [comment]
I don't think this would be possible, as input is dynamic people can update the number (decimal part as well).
I would suggest to show the discounted percentage in a non editable field or normal element, in which you can maintain full value in state and on visual just show the 4 decimal part.

**Comment by pedrohenriiz** [comment]
Sorry for the delay to respond you, I was busy. So, in the end, we decided to use a fixed decimal scale that matches our requirements and we didn't had to do something like you proposed, but thanks for your help anyways.
