### ISSUE TITLE
[material-ui][redux-form] When using NumberFormat with material-ui TextField in a redux-form and thousandSeparator, the field value is transformed to a string even though floatValue is passed to onChange handler

### ISSUE THREAD

**Issue by R4DIC4L** [s-yadav/react-number-format#554]
#### Describe the issue and the actual behavior
When using thousandSeparator integrated with material-ui TextField and with the control as a field in a redux-form form, after inputting a number (can be easier seen when value has more than 3 digits), the field is blurred and the value is converted to string, even though the floatValue is sent via onValueChange to the redux-form onChange handler.

#### Describe the expected behavior
The field value should not be changed to a string and should remain a number when floatValue is passed to redux-form onChange.

#### Provide a CodeSandbox link illustrating the issue
Here is a code sandbox: https://codesandbox.io/s/material-ui-number-format-e1tph?file=/numeric-format.js

#### Provide steps to reproduce this issue
1. Enter a number into the input value.
2. Un-focus the field (click outside the field)
3. Observe the console log or click the Save button (value is in formatted form with thousand separator instead of numerical form).

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [x] Firefox
- [ ] Firefox (Android)

**Comment by R4DIC4L** [comment]
Any findings about this item @nikhil-varma?

**Comment by nikhil-varma** [comment]
@R4DIC4L Hey! first of all, apologies for the delay. Due to lot of work & issues in the pipeline I am still yet to investigate this. Please allow me few days to get to this. Thanks a lot for your patience.

**Comment by R4DIC4L** [comment]
Did you have time to look into this, @nikhil-varma?

**Comment by nikhil-varma** [comment]
@R4DIC4L Apologies. Have been having very hectic days so couldn't get to this. Please allow me some more time to get this. Apologies again! Appreciate your patients and consideration.

**Comment by nikhil-varma** [comment]
@R4DIC4L Based on the investigation, it doesn't look like RNF is doing this. The type in the `onChange` in NumberFormat is number. When the form is being submitted, looks like it is picking up from `input.value` which is resulting in a formatted string text.
