### ISSUE TITLE
Access raw value in onChange event outside of component

### ISSUE THREAD

**Issue by blackfin** [s-yadav/react-number-format#555]
#### Describe the issue and the actual behavior
Access raw value in onChange event, before format applied.

#### Describe the expected behavior
Need a function which can be triggered before on

Uploading Huawei 7.3.1.mp4…

Change event fired. 
In this function need access to input raw value, before format will be applied. 
Like some preprocess on input value before passing it to onChange function call. 
It needs in case that value is pasted from clipboard to masked input.

#### Provide a CodeSandbox link illustrating the issue

https://user-images.githubusercontent.com/716735/122934935-c42e0100-d391-11eb-8caf-8b0769344b71.mp4

#### Please check the browsers where the issue is seen
- [ ] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by nikhil-varma** [comment]
@blackfin I would request you to please refer: #264  to get some ways to resolve this issue. Please let me know if you need any further help and if the discussion has helped you with a workaround. Thanks!

**Comment by nikhil-varma** [comment]
Closing this issue based on the previous reply. Please feel free to open this or post your queries in case you need any help! Thank you for your patience 🙂
