### ISSUE TITLE
IOS numeric mode not supported

### ISSUE THREAD

**Issue by itzAki07** [s-yadav/react-number-format#557]
#### Describe the issue and the actual behavior

In IOS, the Entire keyboard is shown instead of the number pad coz of type=text. It has to be number. Coz of this if we use this component for number input in a payment area, the user can enter letters and symbols. We can restrict from UI still it should show numeric keyboard instead alphanumeric. 

#### Describe the expected behavior
Show only numeric Keypad

#### Provide steps to reproduce this issue
use the component in a PWA app and open keyboard to enter. Alphanumeric keyboard is shown.

#### Please check the browsers where the issue is seen
- [ ] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [x] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by nikhil-varma** [comment]
@itzAki07 Thanks for reporting this. Input type number cannot be supported because it will not allow non-numeric characters which may be the part of a format. Hope this helps! Let me know if I can help with any other queries around it. Thanks! 🙂

**Comment by s-yadav** [comment]
This is intentional, IOS numeric mode does not allow you to enter , and . 
https://github.com/s-yadav/react-number-format/pull/409

**Comment by Findiglay** [comment]
While I understand the issue here, I feel like disabling numeric mode presents a UX issue.

**Comment by AlexandraKlein** [comment]
I believe adding ` pattern="\d*"` displays numeric keyboard.
