### ISSUE TITLE
This Package does not work for React Native 

### ISSUE THREAD

**Issue by sheggietyn** [s-yadav/react-number-format#574]
i was able to get this package installed in my react native app project but it not working when I try 

all I get is some error

does anyone know any package I can use

**Comment by theMasix** [comment]
https://github.com/s-yadav/react-number-format/issues/17

**Comment by StanislavZaborkin** [comment]
If you only need to display a value, you can just wrap it in View and use renderText prop. But I do not think you can use it like an ordinary text input.

`<View>
      <NumberFormat
        value={value}
        prefix={prefix}
        suffix={suffix}
        displayType="text"
        fixedDecimalScale={fixedDecimalScale}
        thousandSeparator={thousandSeparator}
        decimalScale={decimalScale ? 2 : undefined}
        renderText={(formattedValue) => (
          <Text style={textStyles}>{formattedValue}</Text>
        )}
      />
    </View>`

**Comment by flexbox** [comment]
Hey @sheggietyn 
I successfully created a component with `react-native`
here is an example:
```typescript
const NumberCurrency = ({ price, currency }) => {
  return (
    <NumberFormat
      value={price}
      displayType={"text"}
      isNumericString={true}
      suffix={` ${currency}`}
      renderText={(value: string) => <Text>{value}</Text>}    <--- this part if for react-native
    />
  );
};

export default NumberCurrency;
```

If your problem is solved can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by sheggietyn** [comment]
> Hey @sheggietyn I successfully created a component with `react-native` Here is an example for a string formated to a price:
> 
> ```ts
> const NumberCurrency = ({ price, currency }) => {
>   return (
>     <NumberFormat
>       value={price}
>       displayType={"text"}
>       isNumericString={true}
>       fixedDecimalScale={true}
>       decimalScale={2}
>       suffix={` ${currency}`}
>       renderText={(value: string) => <Text>{value}</Text>}
>     />
>   );
> };
> 
> export default NumberCurrency;
> ```
> 
> If your problem is solved can you please close the issue? It sparks joy for maintainers ✨

Thanks @flexbox 


it solved the issue
