### ISSUE TITLE
Using German setup and pass in Number as value does not work

### ISSUE THREAD

**Issue by joergbirkhold** [s-yadav/react-number-format#58]
I created a pen here:
http://codepen.io/anon/pen/zwRWKg
**basically this setting:**

`getInitialState : function(){
    return {inout:3000.33};
  },`
`<NumberFormat value={this.state.inout}  thousandSeparator={'.'} suffix={' €'} decimalSeparator={','} decimalPrecision={true} />`

does produce:
**300.033,00 €**
but should be:
**3.000,33 €**

**Comment by s-yadav** [comment]
Fixed in 2.0.0 alpha
