### ISSUE TITLE
In version 4.9.0 it's not possible to pass a style property to NumberFormat

### ISSUE THREAD

**Issue by AndreiTS** [s-yadav/react-number-format#603]
#### Describe the issue and the actual behavior
In the new version, style is not a valid property anymore, trying to use it in typescript will cause an error:
![image](https://user-images.githubusercontent.com/13489837/147280874-ec0f2fb0-679d-433c-a8d5-a20af09f5ca8.png)

#### Describe the expected behavior
In older versions this would not cause an error.

I believe this is happening because of this: https://github.com/s-yadav/react-number-format/commit/1b6d2f39817cd2a8995980bec7a4caad1b6322b2

**Comment by onionhammer** [comment]
Similar issue for me - i dont think it's just style though, it's all Input properties ('maxLength' etc)

**Comment by s-yadav** [comment]
Ohh, will push a fix.

**Comment by s-yadav** [comment]
Fixed it on v4.9.1. Let me know if the issue still persists.

**Comment by AndreiTS** [comment]
Ok
