### ISSUE TITLE
remove symbol after paste number in input

### ISSUE THREAD

**Issue by Slonevskyi08** [s-yadav/react-number-format#605]
Hello! First of all thanks for this great library!

I have issue, when I use `allowedDecimalSeparators={[",", "."]}` and user paste for example the following number: "1234,42" I have the next value in Input after paste: "123442", but if the user paste "1234.42", then everything is fine. 
I expect that the user will be able to insert numbers with both periods and commas.
How can I fix this? I tried to intercept the initial value before formatting, but it comes to me without a comma(

Thanks so much for your help!

**Comment by Toumash** [comment]
Is this something similiar to this issue? https://github.com/s-yadav/react-number-format/pull/556
If so, I've provided a simple solution to this

**Comment by Slonevskyi08** [comment]
@Toumash 
Yes, this is it. 
Thanks a lot!

**Comment by Toumash** [comment]
Cool, lets close the issue then 😎
