### ISSUE TITLE
No decimal place

### ISSUE THREAD

**Issue by saintego** [s-yadav/react-number-format#61]
I found just one way how to force component to use Integer not Decimal and it is to set `decimalSeparator=""`. I think it'll be more intuitive to use something like `decimalPrecision={0}`, but in that case I had `0.undefined` written in field. Is it possible to fix it, or explain some better way how to do it?

**Comment by s-yadav** [comment]
set decimalSeparator = {false}

**Comment by saintego** [comment]
Thanks, maybe it'll be good at least to describe it better in README.md, while you have also another similar issue here https://github.com/s-yadav/react-number-format/issues/39
But i thinks `0.undefined` is not something that is wanted

**Comment by s-yadav** [comment]
I guess it makes sense to use `decimalPrecision={0}` instead of `decimalSeparator=""` or `decimalSeparator= {false}` as having decimal numbers is related to decimalPrecision not decimalSeparator.

**Comment by ErwinLee10** [comment]
I have a problem for decimal as well.
In the case of Rupiah currency, the thousand separator is "." while the decimal separator is ",".

How can I disallow decimal on the input?

**Comment by s-yadav** [comment]
Hey already have done fixes for seperators issue. Will be adding v2.0.0-alpha tonight or tomorrow.

**Comment by ErwinLee10** [comment]
thanks @s-yadav, so to disallow decimal, we will still use `decimalSeparator= {false}` ?

**Comment by s-yadav** [comment]
No the apis are changing little bit. It will be decimalPrecision = 0

**Comment by s-yadav** [comment]
Fixed in v2.0.0 alpha

**Comment by crperezt** [comment]
Solution is now decimalScale=0 for those stumbling into this problem.
