### ISSUE TITLE
Changing suffix does not change the value

### ISSUE THREAD

**Issue by retireupragu** [s-yadav/react-number-format#62]
When the value is changed, in `componentWillReceiveProps` the display value is calculated
like [so](https://github.com/s-yadav/react-number-format/blob/830898ace443d9beabeb54dae6c65201ca7a1881/src/number_format.js#L51)

but the `formatInput` method uses the `this.props` instead of the `newProps` which is sent to the `componentWillReceiveProps`.

I was updating the `value` and `suffix` props, but the new `suffix` was not used, instead the older suffix gets used as it is referring to `this.props` instead of `newProps`.

The solution is to pass the props along to the `formatInput` and the other methods it invokes so `this.props` is never used from inside them. However once you remove the reference to this.props, these methods no longer need to be bound to the class, they could simply be functions outside of the class.

I am happy to do a PR, but need your direction on what you prefer, send props as an additional argument to `formatInput`, `getSeparators`, `getNumberRegex`, `formatWithPattern`

or

remove these functions out of the class and have them as pure functions which take in just the necessary input arguments

The suggested solution above fixes not only the suffix but also prefix and the whole list of props getting updated

**Comment by s-yadav** [comment]
This been fixed on 2.0.0 alpha. closing this
