### ISSUE TITLE
Backspace on a thousandSeparator does not remove a number, it just moves the cursor behind the separator

### ISSUE THREAD

**Issue by santiago-coastpay-com** [s-yadav/react-number-format#626]
#### Describe the issue and the actual behavior
Hitting backspace when my cursor is on the right side of a thousandSeparator just moves my cursor behind the separator.

#### Describe the expected behavior
My expectation is that if I hit backspace when my cursor is on the right side of thousandSeparator, the number to the left of the separator should be deleted. I'd argue that from the perspective of a user, the intent of hitting backspace in that scenario is always to delete a number. The fact that hitting backspace just moves the cursor around the thousandSeparator feels like undesired behavior.

#### Provide a CodeSandbox link illustrating the issue
Here is [a super basic CodeSandbox](https://codesandbox.io/s/react-number-format-backspace-on-separator-issue-5jbfkn) where you see the issue, but it is also easily testable on any of the demo examples that include a thousandSeparator.

#### Provide steps to reproduce this issue
**Given**: A NumericFormat component with a thousandSeparator prop,
**When**: I type a number in the input field that is 4 digits or more, then place my cursor to the right of any thousandSeparator and hit the backspace key
**Then**: My cursor moves to the other side of the thousandSeparator instead of deleting the number to the left of the thousandSeparator

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by igorsantos07** [comment]
From an UX perspective, it's essential to respect the behavior of common user interactions. There's no reason to change that because of formatting needs.

**Comment by jakemdunn** [comment]
Adjacent to this issue, if you use a PatternFormat with multiple characters in a separation, it doesn't even go back before a separator, it just stops allowing deletion via backspace. The following pattern is unworkable:

```
   <PatternFormat format="(###) ### - ####" />
```

**Comment by igorsantos07** [comment]
@s-yadav I'm not sure if you were able to check this out, but it's still a UX bummer on our interface - other than that, yours is the best package on the topic so far!

**Comment by s-yadav** [comment]
@igorsantos07 Have you tried on the latest version? Its already been fixed with v5.

**Comment by s-yadav** [comment]
@jakemdunn also looks like you are in the old version, This is working fine with the latest version. I would recommend upgrading.
https://codesandbox.io/s/react-number-format-backspace-on-separator-issue-forked-snr3rx

**Comment by jakemdunn** [comment]
Testing with the latest version and a simplified codebase, this issue is indeed fixed. Looks like there's something else causing issues in my project, I'll post a separate ticket if it's related to this library.
