### ISSUE TITLE
Custom component - onChange callback

### ISSUE THREAD

**Issue by Dima9473** [s-yadav/react-number-format#650]
Hi,
#### Describe the issue and the actual behavior
I faced a problem with customInput and onChange callback behaviour. The error "Cannot read properties of undefined (reading 'value') has occur when I set my component as the customInput, and onChange  callback has type (value: string | undefined) => void. I checked the code of your onChange event, and found that there have to be only SyntheticInputEvent as type
<img width="660" alt="Screenshot 2022-07-15 at 09 30 35" src="https://user-images.githubusercontent.com/5555342/179165036-964896b8-9d3c-4aae-9c93-fb749c6c28f6.png">

#### Describe the expected behavior
I would like to specify any onChange callback type in my custom component and use it with NumberFormat.
#### Provide a CodeSandbox link illustrating the issue
The example of the problem
https://codesandbox.io/s/customcomponent-onchange-pb7s9i?file=/src/App.tsx
#### Provide steps to reproduce this issue
To reproduce the issue try to type any number to red input. This will throw an error. Blue input works as expected
#### Please check the browsers where the issue is seen
- [x] Chrome
- [x] Chrome (Android)
- [x] Safari (OSX)
- [x] Safari (iOS)
- [x] Firefox
- [x] Firefox (Android)

**Comment by nikhil-varma** [comment]
@Dima9473 I have created a sandbox with some changes. Please let me know if that is the positive use-case you are expecting. 
https://codesandbox.io/s/customcomponent-onchange-forked-lwjfwn

If so, then I can explain the changes but most likely it's related to the parameter passed to `onChange`

Please have a look and we can take it forward then 🙂 Hope this helps

**Comment by Dima9473** [comment]
As I see you changed the onChange event type from onChange?: (value: string) => void to (event: FormEvent<HTMLInputElement>) => void
However, It is the issue. I now that it's work, but I would like to use the first case where onChange type is  onChange?: (value: string) => void
Is it possible to do?

**Comment by nikhil-varma** [comment]
I think it may not be possible that way since it might break some semantics. I hope this solution helps

**Comment by Dima9473** [comment]
I see.
Thank you
