### ISSUE TITLE
With format "1-###-###-#####", typed numbers "1" and "0" appear with incorrect order

### ISSUE THREAD

**Issue by madhanraja07** [s-yadav/react-number-format#652]
#### Describe the issue and the actual behavior

When using tab to focus, or selecting all content in the prefilled number field
And when there is a format provided
The number after typing the first number is before that number instead of after, resulting in wrong values typed in
For example:
Prefill the phone number field with "1-909-678-6876"
I select all the text/ using tab to focus
I type "12" (a "1", then a "2")
I type "01" (a "0", then a "1")
"21" and "10" is displayed instead

![Typed 12](https://user-images.githubusercontent.com/94130033/179969935-f3004613-d5e8-4947-b25d-6be653717c4c.png)

![Typed 01 ](https://user-images.githubusercontent.com/94130033/179969940-663df720-091c-44a0-b910-aef9207a24ab.png)

#### Describe the expected behavior

With the same actions, the typed number should display in the expected order
For example:
"1-909-678-6876" is shown in the input
I select all the text/ using tab to focus
I type "12" and "01"
"12" and "01" should be displayed, not "21" and "10"

#### Provide a CodeSandbox link illustrating the issue

https://codesandbox.io/s/mutable-https-2kby9i

#### Provide steps to reproduce this issue

Use basic setup with a format "1-###-###-#####".
Prefill the phone number field with "1-909-678-6876"
Select all, or tab to focus
Type "32" 
Displays "32" as expected
Number 3 is before 2 instead of after
Type "12" and "01"
Displays "21" and "10" instead of "12" and "01"

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by nikhil-varma** [comment]
Hi @madhanraja07! Thanks for reporting. Can you please provide a code sandbox link for this? It might just help us debug it slightly better 🙂

**Comment by madhanraja07** [comment]
> Hi @madhanraja07! Thanks for reporting. Can you please provide a code sandbox link for this? It might just help us debug it slightly better 🙂

Added the code sandbox link @nikhil-varma

**Comment by nikhil-varma** [comment]
@madhanraja07 Thank you! Much appreciated. We will get back to you soon with the details

**Comment by nikhil-varma** [comment]
@madhanraja07 Thanks! We will investigate this and get back to you with an update soon. Thank you for your patience and efforts!

**Comment by pstoica** [comment]
I'm experiencing a possibly related issue with v5. My pattern is `13###`. When I add a `mask`, it starts being included in `value`. I'm expecting a 3 digit value, yet sometimes see 4 characters (one extra mask character).

![image](https://user-images.githubusercontent.com/1060689/195714417-a707c9da-ec8d-4f06-a609-4f4930813355.png)

If I don't specify a mask, it defaults to a space which conveniently works out, but is still a potential bug IMO.
![image](https://user-images.githubusercontent.com/1060689/195714610-1ab50c09-d2bb-4e44-8410-4f067a7cf6d6.png)

If I don't use numbers in my format, this issue goes away completely.

**Comment by s-yadav** [comment]
Seems like a bug. Mask characters shouldn’t come in value property.

**Comment by s-yadav** [comment]
The Mask character coming in value issue is fixed on v5.1.0
