### ISSUE TITLE
Demo implementations are broken links

### ISSUE THREAD

**Issue by jwinskill-MA** [s-yadav/react-number-format#658]
#### Actual behavior
links are broken when looking at examples (see [Jinno live demo](https://jinno.io/app/24?source=react-number-format))

#### Expected behavior
Links and examples work

It looks like the site hosting these examples may have gone under - https://jinno.io appears to be for sale as a domain.

**Comment by nikhil-varma** [comment]
Apologies for the inconvenience . Please use https://codepen.io/s-yadav/pen/bpKNMa to play around with the demos until we fix this issue.

P S: We are working on a completely new and easy to use documentation system and it'll be ready soon with all the CodeSandbox demos 🙂
