### ISSUE TITLE
decimalPrecision={true} will show only 1 decimal precision

### ISSUE THREAD

**Issue by HadiAkmal** [s-yadav/react-number-format#66]
I'm using version `2.0.0-alpha2`. Here is my code where `decimalPrecision` is set to `true` :

`<NumberFormat thousandSeparator value={data.price} decimalPrecision={true} displayType={'text'} prefix={'RM '} />`

It will show only 1 decimal place:

![image](https://cloud.githubusercontent.com/assets/14165645/26662387/1df44400-46b6-11e7-8c26-c0acc9fc4549.png)

Isn't it should show 2 decimal places because default for `true` is 2 decimal places? That's what I get from the documentation.

![image](https://cloud.githubusercontent.com/assets/14165645/26662436/67104daa-46b6-11e7-8e71-6768a0642fd6.png)

Changing to `decimalPrecision={2}` will solve the problem.

**Comment by s-yadav** [comment]
Doc has not been updated yet. See release notes
Decimal precision only accepts numeric input. You have to sprcify two if you want two decimals
