### ISSUE TITLE
Remove phone prefix `+1` on paste of `+1 (###) ###-####`

### ISSUE THREAD

**Issue by akhmadullin** [s-yadav/react-number-format#661]
Hi! First of all thanks for this great library!

#### Describe the issue and the actual behavior
I want to use `react-number-format` to create phone input.

I use `format="+7 (###) ###-####"` and it works great for keyboard input.

When I try to paste phone value `(###) ###-####` without `+7` it also works correctly. 

But very often users copy the whole number `+7 (###) ###-####` and they expect, that `+7` will be removed before pasting the value.

Unfortunately, I did not find a way to implement number formatting before pasting.

Of course, I can use `onPaste` prop to implement my logic, but some mobile devices provide labels above keyboard for pasting and value will be added via onInput/onChange props in this case.

<img width="232" alt="Снимок экрана 2022-08-22 в 13 09 10" src="https://user-images.githubusercontent.com/37641303/185831339-26b085c6-2e86-482f-b7aa-e565454fee30.png">

#### Provide a CodeSandbox link illustrating the issue
https://codepen.io/s-yadav/pen/bpKNMa

#### Provide steps to reproduce this issue
1. Open codepen demo
2. Find `Show mask on empty input` example
3. Paste `+1 (999) 555-3344`

You will see `+1 (199) 955-5334` in input, but expected value is `+1 (999) 555-3344`.

#### Please check the browsers where the issue is seen
- [x] Chrome
- [x] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

#### Possible solution
Mb we can add some `customInputValueCorrector` prop, that will be a function in which we can make some formatting before `react-number-format` formatting?

For example, it can be a function with the same signature as [`correctInputValue` method](https://github.com/s-yadav/react-number-format/blob/master/src/number_format.js#L632) and we can call it right before [calling of `correctInputValue` method](https://github.com/s-yadav/react-number-format/blob/master/src/number_format.js#L796):

```js
// src/number_format.js
...
  onChange(e: SyntheticInputEvent) {
    const el = e.target;
    let inputValue = el.value;
    const { state, props } = this;
    const { isAllowed, customInputValueCorrector } = props;
    const lastValue = state.value || '';

    const currentCaretPosition = getCurrentCaretPosition(el);
    
    // my suggestion start
    // here we can add some custom value formatting
    if (customInputValueCorrector) {
      inputValue = customInputValueCorrector(currentCaretPosition, lastValue, inputValue);
    }
    // my suggestion end 
    
    inputValue = this.correctInputValue(currentCaretPosition, lastValue, inputValue);
...  
```

Usage example
```tsx
 <NumberFormat 
     format="+7 (###) ###-####"
     mask="_"
     allowEmptyFormatting
     customInputValueCorrector={
         (currentCaretPosition, lastValue, inputValue) => {
              const value = inputValue.replace(/^\+7/).replace(/\D/g, '');
              
              // also we can add some checks on currentCaretPosition and lastValue
              if (value.length > 10 && v[0] === '7' || v[0] === '8') {
                return v.slice(1);
              }

              return inputValue;
        }
    } />
```

Mb you see another ways to implement phone prefix removing on value pasting?

**Comment by coulgreer** [comment]
I'm kind of curious if this is truly an issue with the library itself or just the use case in the example. Is there a need to always have the prefix `+1`? If so, should that be assumed on submission of the form and then added to the value after the fact?

I want to say that this issue can also be avoided if the format is changed from `+1 (###) ###-####` to `+# (###) ###-####`. Oddly enough, I believe that the formatting is actually putting a `+1` in the field, but on submission the `1` gets omitted. For example `+1 (555) 555-1234` would turn into `5555551234`, instead of, the desired `15555551234` because we as the programmer display that value to decorate what the end user actually types or pastes.

Regardless of the prior mentioned curios, would it be possible to truncate the first digit of input with 11 digits? That is, if we assume the user pastes the full number.

Ultimately, I believe that `NumberFormatter` works as intended. I believe the issue may stem from the assumption of the country code.

**Comment by sezov** [comment]
Same problem :(

**Comment by nikhil-varma** [comment]
@akhmadullin Based on my initial understanding, maybe our new version of the library can help you. We have release a new version which exposes a custom formatter function and many more useful features which you can use to handle such cases. Please refer http://s-yadav.github.io/react-number-format/docs/customization


Also, it should be fairly simple to migration from v4 to v5 and to help you with this, we have a migration guide in place http://s-yadav.github.io/react-number-format/docs/migration

We have also revamped the documentation to provide demos for every props and samples for customizations.

I hope this can help address the concern. Please feel free to continue this thread in case of any questions or queries.

**Comment by dmitryshelomanov** [comment]
@akhmadullin Do you have any solution ?

**Comment by akhmadullin** [comment]
@dmitryshelomanov, I added onPaste and onInput event listeners to achieve desired behavior.

onPaste callback is needed to handle values, that user pastes via "copy + paste" (desktop and mobile).

onInput callback - to handle values, that user pastes via browser autocomplete (desktop and mobile) and phone suggestion, that is shown under keyboard on mobile devices ([like this](https://user-images.githubusercontent.com/37641303/185831339-26b085c6-2e86-482f-b7aa-e565454fee30.png)).
