### ISSUE TITLE
Demo links are redirecting to a not owned site.

### ISSUE THREAD

**Issue by MichaelDimmitt** [s-yadav/react-number-format#664]
https://jinno.io/app/24?source=react-number-format

is redirecting to here:
http://ww3.jinno.io/?sub1=b59646c6-2aec-11ed-90df-84edbe455efe

**Comment by s-yadav** [comment]
Ohhh wow. Let me quickly remove those.

**Comment by s-yadav** [comment]
Fixed on v4.9.4
