### ISSUE TITLE
Type definitions are missing from v5 package distribution

### ISSUE THREAD

**Issue by devunt** [s-yadav/react-number-format#667]
I just upgraded react-number-format to v5.0.0-beta.2 from v4.9.4, and I am not able to import the package from typescript project since type definitions aren't shipped within package anymore.

Error:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/337728/189008567-78f90851-0d92-4d72-a22f-1027243a2550.png">

v5 package structure:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/337728/189008300-ae54fecc-c52a-4fb9-896e-51ab73b388b7.png">

v4.9.4 package structure:
<img width="278" alt="image" src="https://user-images.githubusercontent.com/337728/189008384-26b72c35-ada8-477c-930a-bf2ca0e0109d.png">

(Note that `d.ts` file is missing)

**Comment by s-yadav** [comment]
Aah, looks like packaging issue. Fixing it.

**Comment by s-yadav** [comment]
Fixed in v5.0.0-beta.4. Let me know if you find any other issue.
