### ISSUE TITLE
Can not handle customInput.

### ISSUE THREAD

**Issue by YozhEzhi** [s-yadav/react-number-format#67]
[Demo](https://codepen.io/YozhEzhi/pen/EXYYKx?editors=0010).

I'm trying to use `react-number-format` with my own components and `thousandSeparator`.
I need my input component to have `defaultValue`.
Am I doing something wrong?

**Comment by Princezhm** [comment]
here you have:
[Demo.](https://codepen.io/anon/pen/KqMrvW)
you have to pass the value through the NumberFormat to then receive a formated value on your customInput

**Comment by YozhEzhi** [comment]
Hi, @Princezhm! Try to change value in the focused input. :)

**Comment by Princezhm** [comment]
Hello @YozhEzhi ... sorry for that, Here you have a better version, you just have to send the onChange function in order to make it work.
also I added an state in order to show all the changes.
[Final Demo 🥇 ](https://codepen.io/anon/pen/KqMrvW)

**Comment by YozhEzhi** [comment]
Thanks, @Princezhm! Got it!
