### ISSUE TITLE
5.0.0-beta.4: bug - values returned by NumericFormat is multiplied when we use fixedDecimalScale

### ISSUE THREAD

**Issue by WrobelAndrzej** [s-yadav/react-number-format#670]
#### Describe the issue and the actual behavior
On latest beta version 5.0.0-beta.4 there is bug with multiply number without decimals when we pass fixedDecimalScale and decimalScale props. Check CodeSandbox for examples

#### Describe the expected behavior
Passing decimal scale = 2, fixedDecimalScale as true and value number 12 should display 12 not 1200.00

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/embed/charming-cookies-fxhpet

#### Provide steps to reproduce this issue
1. use NumericFormat from react-number-format
2. pass props with decimalScale set to 2 or 3
3. pass props fixedDecimalScale
4. Check differences between passing value as number and string

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
Thanks for reporting, fixed on v5.0.0-beta.5
