### ISSUE TITLE
Do not publish beta versions with `latest` tag

### ISSUE THREAD

**Issue by Spielboerg** [s-yadav/react-number-format#672]
#### Describe the issue and the actual behavior
If you run `npm i react-number-format` the `5.0.0-beta.5` version is installed.

#### Describe the expected behavior
If `npm i react-number-format` is run without a tag, the latest stable version should be installed. It would be better if the beta versions were released with a `beta` tag: https://docs.npmjs.com/cli/v8/commands/npm-publish#tag. This allows beta versions to be installed with `npm i react-number-format@beta`.
Please re-publish the state of 4.9.4 under a newer version so that it is installed instead of the beta version if no tag is specified.

**Comment by s-yadav** [comment]
Ohh that's intentional, as v5 is closer to releasing, people installing RNF first time should start with the upcoming version, so that they don't need to migrate later.

**Comment by Spielboerg** [comment]
But if the beta version is already stable and should be installed, why not just release v5 without any tags and release future changes/fixes under 5.x.x versions?
By RC tag do you mean only changing the version to `5.0.0-rc.1` or also releasing with the `next` tag?

**Comment by s-yadav** [comment]
Actually have release v5.0.0 now. :)
