### ISSUE TITLE
Using a custom format and getting an empty object

### ISSUE THREAD

**Issue by sezov** [s-yadav/react-number-format#675]
#### Describe the issue and the actual behavior

When I use that example for the phone, the event returns an empty object.

https://s-yadav.github.io/react-number-format/docs/customization#card-expiry-field-with-usepatternformat

onValueChange={v => console.log(v)}

console => {}

#### Describe the expected behavior
Maybe I misunderstood the work of format, but value should change and return to onValueChange

#### Provide a CodeSandbox link illustrating the issue

https://codesandbox.io/s/card-expiry-field-pattern-format-forked-7k9l06

**Comment by nikhil-varma** [comment]
Hi @sezov 

Thank you for pointing this out. Looks like a small bug in the codesandbox demo and we will release a quick fix to the documentation soon.

Here is the link to the working solution: 
https://codesandbox.io/embed/card-expiry-field-pattern-format-3yzksf?

I have created a PR for fixing this. Thanks again for pointing it out
