### ISSUE TITLE
V5 - Cannot import `OnValueChange` Typescript interface and members

### ISSUE THREAD

**Issue by Treycos** [s-yadav/react-number-format#678]
We're trying to pass our custom event handler to the `onValueChange` prop of  `NumericFormat`

Since V5, the typings for `OnValueChange`, `SourceInfo` and `NumberFormatValues` seem to be inaccessible

TS Error:

`Module '"react-number-format"' has no exported member 'SourceInfo'.ts(2305)`

Example handler :

` const handleValueChange = (values: NumberFormatValues, sourceInfo: SourceInfo) => {
    // Some stuff
};`

**Comment by s-yadav** [comment]
Will export it.

**Comment by s-yadav** [comment]
fixed on v5.0.1

**Comment by YuliyaNovik** [comment]
hey @s-yadav! what about SyntheticInputEvent?
