### ISSUE TITLE
V5 - Prefix or Suffix disappears if input value deleted

### ISSUE THREAD

**Issue by Pekxy** [s-yadav/react-number-format#685]
#### Describe the issue and the actual behavior

In NumericFormat, if input value is deleted, suffix or prefix disappears as well (appears again when input is entered).

#### Describe the expected behavior

Suffix and prefix should always be present and visible, even if input value is empty.

#### Provide a CodeSandbox link illustrating the issue

See prefix and suffix demo in your [documentation](https://s-yadav.github.io/react-number-format/docs/numeric_format).

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [x] Safari (OSX)
- [ ] Safari (iOS)
- [x] Firefox
- [ ] Firefox (Android)

**Comment by altyntsevlexus** [comment]
Any updates on this issue? Really need this to be fixed :)

**Comment by nikhil-varma** [comment]
Hi @Pekxy 
That is the expected behaviour of the library. To accommodate this use-case, please consider using the `format` hook that is provided in the new library.  

Reference for customised behvaiour: http://s-yadav.github.io/react-number-format/docs/customization

Please let me know if you need any further help 🙂 

Thanks! Hope this helps

**Comment by altyntsevlexus** [comment]
@nikhil-varma Okay, but what if I need to use NumericFormatProps like thousandSeparator and I need to store value as "unformatted"? Previously I could just pass unformatted value (123) without suffix/prefix and it would add it and then just `onValueChange(({value}) => setValue(value))` and it would set 123 without prefix and worked well.

**Comment by nikhil-varma** [comment]
@altyntsevlexus Thanks for getting back. If I may ask, can you please provide a code sandbox for your use-case? I can then assist you with the solution. 

I would also recommend upgrading to the latest version of the library 🙂 
Also, in the meantime, maybe this can help? : http://s-yadav.github.io/react-number-format/docs/props#onvaluechange-values-sourceinfo--

**Comment by ms-tng** [comment]
Just for your information, I could solve the problem originally described by @Pekxy as suggested by @nikhil-varma by replacing the `NumericFormat` component with a custom version like this:
```
import { InputAttributes, NumericFormatProps } from 'react-number-format/types/types';
import { NumberFormatBase, useNumericFormat } from 'react-number-format';
import React from 'react';

const NumericFormat = <BaseType extends any = InputAttributes>(props: NumericFormatProps<BaseType>) => {
    const numericFormatProps = useNumericFormat(props);

    return (
        <NumberFormatBase
            {...numericFormatProps}
            format={numStr =>
                (numStr === '' || numStr === '-') && props.suffix !== undefined
                    ? `${numStr}${props.suffix}`
                    : numericFormatProps.format(numStr)
            }
        />
    );
};
```
Of course, don't forget to treat prefixes in a similar way in case you need to support them, too.

**Comment by altyntsevlexus** [comment]
> http://s-yadav.github.io/react-number-format/docs/props#onvaluechange-values-sourceinfo--

Here is the link:
https://codesandbox.io/s/onvaluechange-demo-forked-ng4g3u

Again, previously, when you type in input and set value as unformatted, it will still shown in input with suffix and prefix and it was useful and easy to handle.

**Comment by altyntsevlexus** [comment]
@nikhil-varma W8ing for your reply!

**Comment by nikhil-varma** [comment]
@altyntsevlexus Apologies for the late response. I have modified your Codesandbox link to accommodate your request. Here's the link: https://codesandbox.io/s/onvaluechange-demo-forked-ek9tx3

Please let me know if that is what you were looking for. The update logic that you wrote was creating this issue. Hope this hleps. Please reach out in case you have any further queries. Thanks!

**Comment by altyntsevlexus** [comment]
@nikhil-varma But what about button "million"? In input it is shown as formatted but `formattedValue` sets without prefix. 
 I mean when we click on "Million" button, result should be `User money: $1000000` but it is `User money: 1000000`

**Comment by nikhil-varma** [comment]
@altyntsevlexus Investigating it. Will keep you posted of my findings soon.

**Comment by s-yadav** [comment]
@altyntsevlexus looks like you missed adding valueIsNumericString prop. It is required when you are using values.value in onValueChange. Maybe we can fix document to make this case more prominent.
Also, on that codesandbox I see old version of numeric format is used.

Here is the working demo: https://codesandbox.io/s/onvaluechange-demo-forked-q7p7lz?file=/src/App.js

**Comment by s-yadav** [comment]
updated the doc.

**Comment by altyntsevlexus** [comment]
@s-yadav @nikhil-varma Thanks 👍
