### ISSUE TITLE
Prefix/Suffix blocking input when set to a number

### ISSUE THREAD

**Issue by amanda-patterson-ny** [s-yadav/react-number-format#691]
#### Describe the issue and the actual behavior
In NumericFormat, if the prefix or suffix is set to a number, that number is blocked from being input as the first input.
Ex. If prefix is set to '1', and the user types '1' as their input, nothing is shown. However, if the user types '2' as their input, '12' is shown, which is correct.

#### Describe the expected behavior
If the prefix is set to '1' and '1' is typed as input, what should be shown is '11'. 

#### Provide a CodeSandbox link illustrating the issue
Issue is present in the demo in official documentation. 
https://s-yadav.github.io/react-number-format/docs/numeric_format/#prefix-string
https://codesandbox.io/s/prefix-demo-6ibo72?from-embed=&file=/src/App.js

#### Provide steps to reproduce this issue
1. Set prefix to '1' 
2. Type '1' as input 
3. Confirm that '1' is blocked from being input

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

Have only tested in chrome.

**Comment by s-yadav** [comment]
Seems like a bug. Will fix this.

**Comment by sergey-gorchichko** [comment]
@s-yadav any plans to fix it in nearest releases?

**Comment by s-yadav** [comment]
Fixed on v5.1.4
