### ISSUE TITLE
Cursor jumps after decimal separator if thousand separator should disappear

### ISSUE THREAD

**Issue by rene-stesl** [s-yadav/react-number-format#695]
#### Describe the issue and the actual behavior
Starting point is a NumericFormat which has multiple thousandSeparators and a decimalSeparator.
If the cursor is placed right in front of the decimal separator and backspace is pressed, the cursor jumps after the decimal separator if a thousand separator should disappear.

#### Describe the expected behavior
Cursor shouldn't jump after the comma separator.

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/s/thousandsgroupstyle-demo-forked-wir1uo?file=/src/App.js

#### Provide steps to reproduce this issue
1. Open CodeSandbox
2. Place cursor behind the 6 but before the comma separator ","
3. Press Backspace
4. Cursor now is after the comma separator instead of in front

#### Please check the browsers where the issue is seen
- [ x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ x] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
Looking into it.

**Comment by s-yadav** [comment]
Fixed on v5.1.0

**Comment by rene-stesl** [comment]
Thanks, works like a charm!
