### ISSUE TITLE
typo in export of patterFormatter should be patternFormatter

### ISSUE THREAD

**Issue by Stas-Buzunko** [s-yadav/react-number-format#698]
<img width="648" alt="Screen Shot 2022-10-26 at 5 54 47 PM" src="https://user-images.githubusercontent.com/12331100/198160165-94abab37-e315-4fe4-9436-af50a62b0fc2.png">

**Comment by s-yadav** [comment]
Aaah, typo. Will fix that.

**Comment by s-yadav** [comment]
Fixed in v5.1.1
