### ISSUE TITLE
isAllowed returning false puts the cursor to the end of the input

### ISSUE THREAD

**Issue by rene-stesl** [s-yadav/react-number-format#699]
#### Describe the issue and the actual behavior
If a NumericFormat has an isAllowed function which restricts the Value e.g. to a max limit, the cursor is set to the end of the input if isAllowed returns false. This can be problematic if there is an existing value in the input which allows for additional decimal numbers.
E.g. the input already contains 123.56 and you want to change it to 123**4**.56 but the value is caped by a max of 1000, the Value won't change if 4 is pressed but the cursor moves to the end of the Input. If you press the 4 again you will get 123.56**4**.

#### Describe the expected behavior
The cursor should stay where it is and nothing should change in the Input

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/s/isallowedcursorpos-0rhzix?file=/src/App.js

#### Provide steps to reproduce this issue
In the provided CodeSandbox put the cursor in front of the comma separator and try to add a number.
The cursor will jump to the end of the input, if you enter a number again it will be added to the decimal places instead of telling the user that he can't input more numbers.

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [x] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
Fixed in v5.1.1
