### ISSUE TITLE
Disable '-' symbol in manual input

### ISSUE THREAD

**Issue by Aliaksandr-Yanushkevich** [s-yadav/react-number-format#704]
#### Describe the issue and the actual behavior
I want to ban manual input of negatives values by user. Simultaniously I want to have negative values in inputs if it is result of calculation from API. Using "allowNegative" = {false} affects restrict manual input but also remove '-' symbol in result from API.
#### Describe the expected behavior
I want to ban '-' symbol onlly in manual input and have this symbol when I set input value programmaticaly.
#### Provide a CodeSandbox link illustrating the issue
I can't understand why, but "allowNegative" = {false} doesn't work on CodeSandbox. Looks like it is the additional issue. In my project I have behaviour described above.
https://codesandbox.io/s/pedantic-cartwright-5n4lly?file=/src/App.js
#### Provide steps to reproduce this issue

case 1
1. click 'Disable negatives' button
2. type negative number in the input
3. actual result: there is '-' symbol in the input (bug, environment - CodeSandBox), there is no '-' (expected behaviour, environment - project)

case 2
1. click 'Disable negatives' button
2. click 'Set the value programmatically' button
3. actual result: there is '-' symbol in the input (bug, environment - CodeSandBox), there is no '-' (not expected behaviour, would like to have all numbers, with negatives included, environment - project)

#### Please check the browsers where the issue is seen
- [x] Chrome
- [x] Chrome (Android)
- [x] Safari (OSX)
- [ ] Safari (iOS)
- [x] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
This can be implemented outside of the library using a custom keyDown event and checking for the key press, and preventing default.

```js
          <NumericFormat
            value={value}
            onChange={(e) => console.log(e.target.value)}
            onKeyDown={(e) => if (e.key === '-') e.preventDefault()}
          />
          
```
