### ISSUE TITLE
don't run `e.persist()` in `_onFocus()` when customInput doesn't have attribute `.persist()`

### ISSUE THREAD

**Issue by corsin-ragettli** [s-yadav/react-number-format#706]
#### Describe the issue and the actual behavior
I have a type issue when I input a custom component in NumericFormat because `e.persist()` doesn't exist on my component when onFocus is called.

#### Describe the expected behavior
NumericFormat doesn't call `e.persist()` when component is focused

#### Please check the browsers where the issue is seen
- [X] Chrome
- [X] Chrome (Android)
- [X] Safari (OSX)
- [X] Safari (iOS)
- [X] Firefox
- [X] Firefox (Android)

**Comment by s-yadav** [comment]
Fixed on v5.1.2
