### ISSUE TITLE
`decimalScale` does not limit decimal scale.

### ISSUE THREAD

**Issue by MeanMangosteen** [s-yadav/react-number-format#707]
#### Describe the issue and the actual behavior
I have a `text` number input 

```
<NumericFormat
    displayType="text"
    thousandSeparator=","
    value={value}
    decimalScale={8}
    renderText={(val) => (
      <ValueText>
        ${val}
      </ValueText>
    )}
  />
  ```
But the `val` that comes through at times isn't capped at the decimal scale specified. It outputs the input value as is. But when I statically set the input value as the breaking value (e.g. "0.99712...."), the decimal scale works fine.

![Screen Shot 2022-11-16 at 4 31 13 pm](https://user-images.githubusercontent.com/22215545/202095475-8179ed97-5e0c-488b-8497-615175587b84.png)

![Screen Shot 2022-11-16 at 4 37 01 pm](https://user-images.githubusercontent.com/22215545/202095507-8f1567f2-618d-4d03-90e2-a38b5af50ef2.png)

If the input value eventually changes then the output value will snaps back to the decimalScale. 

version: 5.1.1
#### Describe the expected behavior
It should always cap the output value at the specified decimal scale.

#### Provide steps to reproduce this issue
I haven't figured out a way to deterministically reproduce this, unfortunately.

#### Please check the browsers where the issue is seen
- [ ] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by MeanMangosteen** [comment]
I can actually see similar behaviour on a code sandbox with a static value:

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/22215545/202115140-c03dc243-0c08-4780-8f36-ffc9be9cac3e.png">


https://codesandbox.io/s/pedantic-sound-vo4gsn?file=/src/App.js.



If I refresh the page, it renders correctly but if you play around with the numbers i can get it to break.

https://user-images.githubusercontent.com/22215545/202116288-e78c41fd-9357-424d-a416-2eb1ab7228a2.mp4

**Comment by s-yadav** [comment]
Seems like a bug, checking it.

**Comment by s-yadav** [comment]
From both examples, it looks like string value is provided in the NumericFormat. In this case, `valueIsNumericString` need to be set as true, so that the number format can distinguish it from a formatted string.
https://s-yadav.github.io/react-number-format/docs/props#valueisnumericstring-boolean
