### ISSUE TITLE
Get non formated number value

### ISSUE THREAD

**Issue by Tommy10802** [s-yadav/react-number-format#71]
It is possible to return non formatted value as number or float when inputed value is eg "1,12" with decimalSeparator=',' and string when inputed value is not number. Because now non formatted value is still string even input value is number or float.

Thanks

**Comment by s-yadav** [comment]
The api has been changed little. The onChange callback will get a values object as the second parameter
```js
{
  formattedValue: '$23,234,235.56', //value after applying formatting
  value: '23234235.56', //non formatted value as string, but it maintains the decimalSeparator provided, so if , is decimal separator then value will be 23234235,56
  floatValue: 23234235.56 //floating point representation. For big numbers it can have exponential syntax
}
```

**Comment by s-yadav** [comment]
Closing this issue as this will serve your purpose

**Comment by Tommy10802** [comment]
Thank you a lot. This feature help me decided to use your plugin insted of cleave js. Thanks again :)
