### ISSUE TITLE
Extra character added if you start typing from start of the input while input is fully filled

### ISSUE THREAD

**Issue by PrimulaX** [s-yadav/react-number-format#712]
#### Describe the issue and the actual behavior
If formatted input is fully filled and you jump to the start of the string and type something you will get the extra character in your value

#### Describe the expected behavior
value length shouldn’t change

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/s/format-demo-forked-urih6q

#### Provide steps to reproduce this issue
1. Enter every character for the pattern
2. Add any number at the start of the value in the input
3. Your pattern will be exceeded with one character 

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [x] Safari (OSX)
- [ ] Safari (iOS)
- [x] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
Seems like a bug. Will fix this. Thanks for reporting.

**Comment by PrimulaX** [comment]
@s-yadav Thanks

**Comment by s-yadav** [comment]
Fix is available on 5.1.3
