### ISSUE TITLE
Focus via keyboard does not behave as expected

### ISSUE THREAD

**Issue by akhmadullin** [s-yadav/react-number-format#714]
#### Describe the issue and the actual behavior
When I focus to the PatternFormat input via mouse, everything works ok: I can see caret position.

https://user-images.githubusercontent.com/37641303/208830908-5e123d15-1af7-499d-84c7-41df2ca7f4bc.mov

But when I focus to the PatternFormat input via keyboard (tab navigation), input's content becomes selected and I don't see caret position.

https://user-images.githubusercontent.com/37641303/208831692-68eaad5c-c6c6-4278-8536-356fc1051462.mov

#### Describe the expected behavior
Focus via keyboard works the same as focus via mouse.

#### Provide a CodeSandbox link illustrating the issue
The problem can be reproduced on any example from the docs.

For example, this [one](https://codesandbox.io/s/allow-empty-formatting-demo-kjs0lz?from-embed).

#### Provide steps to reproduce this issue
1. Open [example](https://codesandbox.io/s/allow-empty-formatting-demo-kjs0lz?from-embed)
2. Try to focus via keyboard (tab navigation).

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [x] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
That's the normal behaviour of any input.
