### ISSUE TITLE
My project doesn't recognize NumberFormat

### ISSUE THREAD

**Issue by manaka02** [s-yadav/react-number-format#72]
Hello,
I'm new in React-native and I use react@16.0.0-alpha.12
I'd like to use this library so, I got it. When I import it, there is no problem but when I try to use, 
It always says.
       [ expected a component class got object object ]
when I do ctrl+clic into the NumberFormat import, it redirects me to number-format.js , I think that, my import is not the problem but other.
Can anyone help me

**Comment by s-yadav** [comment]
Currently it does not support react native. It relies on Dom elements.

**Comment by manaka02** [comment]
thanks for you speed reply
If I understand,you mean it works only for react.js

**Comment by s-yadav** [comment]
Yes

**Comment by manaka02** [comment]
ah !  I spent many days to debug it for my project :D 😄 
 but thanks you very much. 
Can you suggest me another librairy which can do the same in React-native?

**Comment by s-yadav** [comment]
Will keep this thread open in #17
