### ISSUE TITLE
Duplicate prop

### ISSUE THREAD

**Issue by denismilosavljevic95** [s-yadav/react-number-format#720]
#### Describe the issue and the actual behavior
In the file `documentation/v5/docs/props.md` on lines 169 and 174 there is two same prop
#### Please check the browsers where the issue is seen
- [ ] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
fixed, Thanks
