### ISSUE TITLE
Input selection delselects on rerender.

### ISSUE THREAD

**Issue by MeanMangosteen** [s-yadav/react-number-format#723]
#### Describe the issue and the actual behavior
When a react-number-format input is a child and it's parent rerenders, then whatever was selected in the input get deselected.

https://user-images.githubusercontent.com/22215545/214467888-112ea5cd-885b-4aa4-a384-5a15a7d4c6d1.mp4

Using a native input, this behavior doesn't occur. Interestingly, this issue also does not occur if it's not a child (the rerender occurs within it's own component).

#### Describe the expected behavior

Input selection should stay selected.

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/s/peaceful-dream-itf0yh?file=/src/App.js

#### Provide steps to reproduce this issue

See codesandbox.

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [x] Firefox
- [ ] Firefox (Android)

**Comment by MeanMangosteen** [comment]
Any thoughts on this one @s-yadav? 

Cheers 😃.

**Comment by sonnh58** [comment]
Same issue, i have to downgrade to v4.9.4

**Comment by MeanMangosteen** [comment]
Ah interesting, @sonnh58. I might try giving that a go.

**Comment by mara-vodvarka** [comment]
Hello, same here, macos Microsoft Edge Version 110.0.1587.41 (Official build) (arm64), the downgrade worked, but that version doesn't move cursor to the end of pasted text (possible workaround)

**Comment by nishatadapt** [comment]
I'm noticing this issue as well

**Comment by s-yadav** [comment]
This seems to be fixed on latest version along with a fix around rerendering. Here's the updated sandbox.
https://codesandbox.io/s/dazzling-firefly-xn2w5v
