### ISSUE TITLE
Prefix '-' does not allow to remove first number

### ISSUE THREAD

**Issue by kkhorshu** [s-yadav/react-number-format#729]
#### Describe the issue and the actual behavior
If input contains prefix '-', then it is not possible to remove first number. The one number always remains as value

#### Describe the expected behavior
If input contains prefix '-', then it should be possible to remove all entered numbers

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/s/prefix-demo-forked-92816r

#### Provide steps to reproduce this issue
1. Enter any number in input
2. Press backspace until only 1 number is in input
3. Press backspace one more time

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [x] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by Mudbill** [comment]
I just encountered this as well, very strange.

**Comment by s-yadav** [comment]
This should be fixed on v5.1.4
