### ISSUE TITLE
Decimal prefix

### ISSUE THREAD

**Issue by Fi1osof** [s-yadav/react-number-format#73]
Hi!

Can i set format="+7 ####" ?
Result now return value with 7;

**Comment by s-yadav** [comment]
I can reproduce this. Using number as prefix do have bugs. For now, you can use custom format method. I will fix this.

**Comment by Fi1osof** [comment]
@s-yadav i did.

**Comment by s-yadav** [comment]
Fixed in v3 alpha

**Comment by Fi1osof** [comment]
Many thanks!
