### ISSUE TITLE
fixedDecimalScale is not documented

### ISSUE THREAD

**Issue by arminbashizade** [s-yadav/react-number-format#734]
#### Describe the issue and the actual behavior
`fixedDecimalScale` is not documented [here](https://s-yadav.github.io/react-number-format/docs/numeric_format)
I spent some time trying to create that functionality with `useNumericFormat` and along the way found `fixedDecimalScale` in the source code

#### Describe the expected behavior
all props must be documented

#### Provide a CodeSandbox link illustrating the issue
N/A

#### Provide steps to reproduce this issue
N/A

#### Please check the browsers where the issue is seen
- [ ] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by darrenbarklie** [comment]
So glad you opened this issue, came looking for exactly this functionality/property.
