### ISSUE TITLE
Cursor position resetting with a conditional prefix

### ISSUE THREAD

**Issue by Treycos** [s-yadav/react-number-format#742]
When using `NumericFormat` with a conditional prefix, the cursor position is reset to the left of the input after the prefix changes

In v4, it maintained the usual behavior, the cursor doesn't move when a prefix is added midway through typing

Code Sandbox: [https://codesandbox.io/s/react-number-format-forked-654ycv?file=/src/index.js](url)

To reproduce:

- Clear the left input
- Type a number
- Cursor is reset at the end
- Clear the right input
- Type a number
- Cursor is where it should be

- [x] Chrome
- [x] Firefox

**Comment by sormpe** [comment]
I think #725  is related

**Comment by s-yadav** [comment]
This is fixed on v5.2.0

**Comment by akhmadullin** [comment]
Hi

c0157ea broke cursor position in another case

I have phone input. When input is focused and empty - short mask (`+7 (`) is shown
<img width="339" alt="short mask" src="https://github.com/s-yadav/react-number-format/assets/37641303/0dcf307e-3741-46d0-bb79-fda88e427075">

when input is not empty - full-format mask (`+7 (###) ###-####`) is shown
<img width="339" alt="long mask" src="https://github.com/s-yadav/react-number-format/assets/37641303/fec18219-c175-4921-bbcc-f9c6097f4b8d">

c0157ea affects copy+paste process

Previously, before c0157ea, after applying copy+paste cursor was after last inserted symbol in input

https://github.com/s-yadav/react-number-format/assets/37641303/4ed45467-cdeb-4444-8229-1bf77a78be01

Now (commit c0157ea) after applying copy+paste cursor is stayed on the same place, where is was before pasting

https://github.com/s-yadav/react-number-format/assets/37641303/22cf7a36-1171-43ca-a0e0-503b439d8a56

Is it possible to fix this issue?

**Comment by s-yadav** [comment]
Sure @akhmadullin, will take a look. Can you create a sandbox with this bug, it will help debugging.

**Comment by akhmadullin** [comment]
@s-yadav, ok

I created separate issue - https://github.com/s-yadav/react-number-format/issues/772, where I described problem and provided links to sandbox with examples
