### ISSUE TITLE
Prevent number push to right side when replace the number

### ISSUE THREAD

**Issue by ngocducdim** [s-yadav/react-number-format#746]
Hi, can I ask whenever I edit the input, the number will push to right side, for example can take a look the video below, current input it **00:03.55**, I want change to **00:04.55**, but when I try replace the **3**, this **3** push to the right side and become **00:04.35** instead **00:04.55**, how can I prevent it push to right side? Thanks

https://user-images.githubusercontent.com/97713182/225251913-1ccda4e9-96da-4701-82bf-bca8f58636ce.mp4

**Comment by ngocducdim** [comment]
Sorry my mistake, have to select the **3** and then replace it
![image](https://user-images.githubusercontent.com/97713182/225252343-2001cc24-d63f-4391-aa36-1c981c29b65e.png)

**Comment by s-yadav** [comment]
Yes this is expected. Basically, all numbers are part of the same input, so as you put a new number character it will be spread over formatting. You can write custom behavior however with customization. https://s-yadav.github.io/react-number-format/docs/customization
