### ISSUE TITLE
Documentation discrepancy for installing package 

### ISSUE THREAD

**Issue by Zaris47** [s-yadav/react-number-format#754]
#### Installing package from the instruction of ES6 in docs causes error

when running the command, as per docs
`import NumberFormat from 'react-number-format';`

it results in an error _does not contain a default export (imported as 'NumberFormat')._

The working format is there is ReadMe.md 
`import { NumericFormat } from 'react-number-format';`

It is a minor documentation issue

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
Can you share the link to where do you find this snippet?
Tried looking over it, but seems correct to me.

https://s-yadav.github.io/react-number-format/docs/intro

**Comment by Zaris47** [comment]
hey sorry about that! 

I just checked and it was the old doc v4

https://github.com/s-yadav/react-number-format/blob/master/documentation/v4.md

I checked my package.json and realized I was using version 5.x

Still new to GitHub, libraries and coding in general so figuring it out
