### ISSUE TITLE
Is there any way to pass props to a customInput?

### ISSUE THREAD

**Issue by gustavo-maurina** [s-yadav/react-number-format#755]
#### Describe the issue and the actual behavior
I want to render a custom input (Chakra Input), which needs some styling props. I can't seem to be able to do it.

For example, the code below doesn't work:
```typescript
 <StyledInput
      onChange={(event) => field.onChange(event)}
      value={isNumEmpty(field.value) ? '' : field.value}
      getInputRef={ref}
      customInput={(inputProps: any) => {
         return (
            <Input
                {...inputProps}
                background={isInputOnForeground ? 'transparent' : undefined}
                position={isInputOnForeground ? 'relative' : undefined}
                zIndex={isInputOnForeground ? 3 : undefined}
            />
       );
    }}
 />
```
It styles as I wish, but when I try to enter values on the field, it inserts the first character and then the cursor gets lost. If I don't spread `inputProps` it doesn't fire my `onChange` nor recognizes my `value`. I have also experimented with using `ref` and `getInputRef`in a few ways as well.

While the code below works perfectly in terms of functionality, but I can't apply my styling:
```typescript
<StyledInput
     onChange={(event) => field.onChange(event)}
     value={isNumEmpty(field.value) ? '' : field.value}
     getInputRef={ref}
     customInput={Input}
 />
```

#### Describe the expected behavior
I wish I could pass a function returning my JSX element, with it's needed props. But looking at how it is implemented, I feel like a `customInputProps` could solve the issue 

#### Please check the browsers where the issue is seen
- [x] Chrome
- [x] Firefox

**Comment by s-yadav** [comment]
This is because you are passing inline function on customInput, so on every render the component reference is changing breaking the react reconciliation. 

You can move the customInput component outside of component render and pass the reference here.
```js
const CustomInput = (inputProps: any) => {
         return (
            <Input
                {...inputProps}
                background={isInputOnForeground ? 'transparent' : undefined}
                position={isInputOnForeground ? 'relative' : undefined}
                zIndex={isInputOnForeground ? 3 : undefined}
            />
       );
    }
    
 function MyComponent(){
   return (
     <StyledInput
      onChange={(event) => field.onChange(event)}
      value={isNumEmpty(field.value) ? '' : field.value}
      getInputRef={ref}
      customInput={CustomInput}
     />
   )
 }   
```

Also, all the props which are not specific to rnf, are forward to the customInput. So you can just do.
```js
<StyledInput
     onChange={(event) => field.onChange(event)}
     value={isNumEmpty(field.value) ? '' : field.value}
     getInputRef={ref}
     customInput={Input}
      background={isInputOnForeground ? 'transparent' : undefined}
      position={isInputOnForeground ? 'relative' : undefined}
      zIndex={isInputOnForeground ? 3 : undefined}
 />
 ```

here background, position, zIndex will be forward to `Input`

**Comment by owenn2106** [comment]
How about in Typescript? I know that they will get forwarded to the `customInput`, but I'm getting an error where the props doesn't exist in the specified prop types.
```
Property 'intent' does not exist on type 'IntrinsicAttributes & InternalNumberFormatBase & { thousandSeparator?: string | boolean | undefined; decimalSeparator?: string | undefined; ... 7 more ...; prefix?: string | undefined; } & Omit<...> & Omit<...> & { ...; }'.
```

I pass the `intent` prop as such:
```javascript
<NumericFormat
          customInput={InputGroup}
          thousandSeparator={false}
          decimalScale={2}
          intent={intent} -> This throws an error
          inputRef={quantityRef} -> This throws an error as well
          {...props}
/>
```

**Comment by s-yadav** [comment]
@owenn2106 that already works, which version you are in? Also I am assuming intent prop is defined in InputGrpup. 
https://github.com/s-yadav/react-number-format/blob/master/test/types/number_format.spec.tsx#L58

**Comment by simonlc** [comment]
In case anyone ends up here too, I passed the type to the component as such:

```
<PatternFormat<MyInputProps>
    //...
    customInput={MyInput}
    ghost={ghost}
/>
```

If there's a way to get them picked up automatically, I'd love to know!
