### ISSUE TITLE
Value of the field does not render when using 5.2.1

### ISSUE THREAD

**Issue by rotherfordm** [s-yadav/react-number-format#757]
#### Describe the issue and the actual behavior
Value of the field does not render when using react-number-format@5.2.1, react-hook-forms, and materialui  
![bug](https://github.com/s-yadav/react-number-format/assets/22748659/a4cdb31d-6ef4-44b2-9f86-0c093c9da1a1)

#### Describe the expected behavior
After clicking a materialui dialog with the form as content it will not render the value passed as props.

#### Provide a CodeSandbox link illustrating the issue
My local environment project is similar to the CodeSandbox project.
Currently the CodeSandbox uses the 5.1.4 version of react-number-format and it does not have the bug and works with that version.
[Codesandbox](https://codesandbox.io/s/rhf-forms-money-number-test-1s1s0s?file=/src/App.js)

Waiting for CodeSandbox to show a 5.2.1 version option of react-number-format to further check.

#### Provide steps to reproduce this issue
Shown similarly to the CodeSandbox project.

#### Please check the browsers where the issue is seen
- [x ] Chrome
- [x ] Firefox

**Comment by pr1tkin** [comment]
` 5.2.0` is also affected

**Comment by Semkoo** [comment]
I reverted to `5.1.1` and its working but yes it fails for me too

**Comment by s-yadav** [comment]
Is your app running on StrictMode. StrictMode have some problems.

**Comment by s-yadav** [comment]
This is fixed on v5.2.2
