### ISSUE TITLE
Can't type decimals after erase them when maxLength and fixedDecimalScale is provided

### ISSUE THREAD

**Issue by neeco90** [s-yadav/react-number-format#758]
#### Describe the issue and the actual behavior
Setting a NumericFormat with fixedDecimalScale and a maxLength value if you type a value with decimals, erase decimals recently typed and then try to type another decimals, nothing happens. The new decimals can't be typed

#### Describe the expected behavior
Can be able to replace the decimal values typed

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/s/magical-sid-l65u8t?file=/src/App.js

#### Provide steps to reproduce this issue
Try to replace the "4" with another number

#### Please check the browsers where the issue is seen
- [ ✔️] Chrome
- [ ✔️] Chrome (Android)
- [ ✔️] Safari (OSX)
- [ ✔️] Safari (iOS)
- [ ✔️] Firefox
- [ ✔️] Firefox (Android)

**Comment by s-yadav** [comment]
While this is valid case, it can't be fixed. As formatting happens post the number is typed. In this case maxLength doesn't allow to type at all, if the number of characters is over the defined length, so rnf can't do anything in this case.

To fix this you can use isAllowed prop. Updated sandbox.
https://codesandbox.io/s/bug-react-number-format-forked-6w93jr

**Comment by s-yadav** [comment]
I will also mention this on document, for future reference.
