### ISSUE TITLE
NumericFormat adding 2 decimal points to some values

### ISSUE THREAD

**Issue by alejandrocortes3112** [s-yadav/react-number-format#759]
#### Describe the issue and the actual behavior
NumericFormat with a suffix of "%" is adding 2 decimal points to some values when typing. For example typing "7" automatically converts to "7.00%", which does not happen when I type other numbers.

I'm setting `decimalScale = {2}`, but I did not add `fixedDecimalScale`

I'm using react-number-format 5.1.2

#### Describe the expected behavior

Behavior should be equal for all numbers. If you type "7" should display as "7%"

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/s/dry-pine-vtyr2d?file=/src/App.js

#### Provide steps to reproduce this issue
Just type "7" or "55" and type any other number to compare the behavior.

#### Please check the browsers where the issue is seen
- [ x] Chrome
- [ ] Chrome (Android)
- [ x] Safari (OSX)
- [ ] Safari (iOS)
- [x ] Firefox
- [ ] Firefox (Android)

Thank you very much

**Comment by s-yadav** [comment]
This is not NumberFormat issue, instead how float precisions are handled in javascript.
try running this on console `(7 / 100) * 100`. It will give `7.000000000000001` which is causing this issue. 
You can use this trick to pass back the value.
```
value={parseFloat(value.toFixed(2))} // 2 is your decimal scale.
```
