### ISSUE TITLE
Using useLayoutEffect causes a warning with SSR

### ISSUE THREAD

**Issue by bryanbarrios** [s-yadav/react-number-format#760]
#### Describe the issue and the actual behavior

It isn't possible to use [useLayoutEffect](https://github.com/s-yadav/react-number-format/blob/49a00037649f72d9d96af57d16524cd80d9b7a47/src/number_format_base.tsx#L232) with SSR because it doesn't run on the server, only on the client.

` Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.`

I'm using Next.js 13 with page router.

#### Describe the expected behavior

Instead of using useLayoutEffect, use useEffect to avoid the warning as described [here](https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85).

#### Provide a CodeSandbox link illustrating the issue

https://codesandbox.io/p/sandbox/optimistic-dew-65g2fb

#### Provide steps to reproduce this issue

See the terminal output.

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by NicolasMontone** [comment]
Hey @bryanbarrios, how are you? 
I already send a PR fixing the issue, if you want a workaround to prevent the warning, you can import the component using `[next/dynamic](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#nextdynamic)`! 
like -> 
```typescript 
import dynamic from 'next/dynamic'
const NumericFormat = dynamic(
  () => import('react-number-format').then((mod) => mod.NumericFormat),
  {
    ssr: false,
  },
)
```

**Comment by NicolasMontone** [comment]
> Hey @NicolasMontone! Thanks for your answer. I'm building a Design System under a monorepo architecture, so I prefer to keep implementation/solution agnostic to the framework or library.

Oh, no problem! The problem should be solved when [this PR](https://github.com/s-yadav/react-number-format/pull/761) is merged 😄
