### ISSUE TITLE
Bug with cursor position during copy+paste into input with dynamic (changing) mask (format)

### ISSUE THREAD

**Issue by akhmadullin** [s-yadav/react-number-format#772]
#### Describe the issue and the actual behavior

c0157ea broke cursor position during copy+paste into input with dynamic mask

I have phone input. When input is focused and empty - short mask (`+7 (`) is shown
<img width="339" alt="short mask" src="https://github.com/s-yadav/react-number-format/assets/37641303/0dcf307e-3741-46d0-bb79-fda88e427075">

when input is not empty - full-format mask (`+7 (###) ###-####`) is shown
<img width="339" alt="long mask" src="https://github.com/s-yadav/react-number-format/assets/37641303/fec18219-c175-4921-bbcc-f9c6097f4b8d">

c0157ea affects copy+paste process

Previously, before c0157ea, after applying copy+paste cursor was after last inserted symbol in input

https://github.com/s-yadav/react-number-format/assets/37641303/4ed45467-cdeb-4444-8229-1bf77a78be01

Now (commit c0157ea) after applying copy+paste cursor is stayed on the same place, where is was before pasting

https://github.com/s-yadav/react-number-format/assets/37641303/22cf7a36-1171-43ca-a0e0-503b439d8a56

#### Describe the expected behavior
Expected behavior - after pasting cursor is moved to the end of the inserted text, as it was before c0157ea 

https://github.com/s-yadav/react-number-format/assets/37641303/4ed45467-cdeb-4444-8229-1bf77a78be01

#### Provide a CodeSandbox link illustrating the issue
[Demo for v5.1.4](https://codesandbox.io/p/github/akhmadullin/rnf-v5.1.4-dynamic-mask-copy-paste-working-demo/main) - after copy+paste cursor is moving to the end of text

[Demo for v5.2.2](https://codesandbox.io/p/github/akhmadullin/rnf-v5.2.2-dynamic-mask-copy-paste-broken-demo/main) - after copy+paste cursor is staying at the same position, where it was before pasting

#### Provide steps to reproduce this issue
1. Open demo
2. Copy phone number and paste it into the input

#### Please check the browsers where the issue is seen
- [x] Chrome
- [x] Safari (OSX)

#### Solution
Is it possible to fix this issue?

**Comment by s-yadav** [comment]
@akhmadullin looks like you have `event.preventDefault` added on paste event which hampers with selection. Earlier there used to be double rendering issue, due to side-effect of which even.preventDefault was not impacting the caret position. But that being fixed now event.preventDefault coming into picture.

Just remove that and it should work. Here's an updated sandbox.
https://codesandbox.io/p/github/akhmadullin/rnf-v5.2.2-dynamic-mask-copy-paste-broken-demo/csb-dfjqf5/draft/strange-rgb?file=/src/phone-input.tsx:39,17

**Comment by akhmadullin** [comment]
@s-yadav, yes, it works

thanks for help
