### ISSUE TITLE
thousandSeperator is not working

### ISSUE THREAD

**Issue by yograf** [s-yadav/react-number-format#78]
https://codepen.io/s-yadav/pen/bpKNMa

**Comment by s-yadav** [comment]
Its working. Can you explain more what exactly is not working? 
Also, the browser/device where you tested?

**Comment by yograf** [comment]
@s-yadav Thanks for your replay :)
Isn't <NumberFormat value={2456981} displayType={'text'} thousandSeperator={true} prefix={'$'} /> should render the 2456981 with thousand seperator?
![screenshot84](https://user-images.githubusercontent.com/5279133/29012055-1e0590f6-7b41-11e7-9f04-2608ca74be4f.png)

**Comment by yograf** [comment]
Found it. it's a typo on the example pen.
Opened new issue...

**Comment by s-yadav** [comment]
Ohhh that was a typo mistake on thousandSeparator
