### ISSUE TITLE
Jumping caret

### ISSUE THREAD

**Issue by clickjamper** [s-yadav/react-number-format#780]
I tryied to find any information about situation^
When you use format and double click on empty input and next click on his center, the caret set on center input.

Expected that caret will set on input start or last character entered.

It can see in doc demo, example: https://s-yadav.github.io/react-number-format/docs/pattern_format/

Could this be the correct behaviour?

**Comment by clickjamper** [comment]
Can it be because format is a string, which set to input, and we can set the caret to any on input like base behavior?

**Comment by s-yadav** [comment]
Yes, the expectation is that the caret moves after the last entered character. on normal click its handle, but the case you mentioned click after selection is not handled.
Will fix this but keeping it as low priority as soon as you type or click again, it will go to the right caret position.

**Comment by arturjackowiak** [comment]
Hi @s-yadav , any updates?

**Comment by s-yadav** [comment]
Hey @arturjackowiak, pushed fix for this on 5.3.4
