### ISSUE TITLE
Infinite loop encountered when using onValueChange without setting valueIsNumericString prop

### ISSUE THREAD

**Issue by muradsofi** [s-yadav/react-number-format#786]
#### Describe the issue and the actual behavior

I've encountered an issue when using the onValueChange callback with the `NumericFormat` component. Specifically, if I don't set the `valueIsNumericString` prop, my app enters an infinite loop. This seems to be directly related to how I set the value

#### Describe the expected behavior

The NumericFormat component should handle the `onValueChange` callback seamlessly, even when the `valueIsNumericString` prop isn't set, without causing any infinite loops.

If the `valueIsNumericString` prop is required, in that case, we need to inform the developer via `console.error`

#### Provide a CodeSandbox link illustrating the issue

https://codesandbox.io/s/isnumericstring-demo-forked-jnkhk3?file=/src/App.js:0-645

**Comment by s-yadav** [comment]
Humm, it seems like a bug. Looking into it.

**Comment by s-yadav** [comment]
Though I will add more checks, to identify what type of value is passed for numeric format. Basically, if a thousand separator is not `.` then lib can identify whether it is a numeric string or not. So will handle that case.

**Comment by s-yadav** [comment]
The reported issue is fixed on v5.3.1. Also update the doc for https://s-yadav.github.io/react-number-format/docs/props/#valueisnumericstring-boolean
