### ISSUE TITLE
Does this work with MUI5?

### ISSUE THREAD

**Issue by rwb196884** [s-yadav/react-number-format#800]
I had this working with MUI4 and am trying to upgrade to 5 but it seems to be completely broken.
All the examples are for MUI4.
Does it not work with MUI5?

I have
```
<TextField
inputComponent: numberType === 'currency' ? (NumberFormatCustom as any) : undefined,
```
but MUI5 has errors:
* `Failed prop type: Invalid prop inputComponent supplied to ForwardRef(InputBase2)`
* `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

**Comment by ArturKustyaev** [comment]
use cusromInput https://s-yadav.github.io/react-number-format/docs/props

**Comment by s-yadav** [comment]
Closing this as it can be solved using customInput prop as mentioned by @ArturKustyaev .
