### ISSUE TITLE
`allowLeadingZeroes` prop doesn't work

### ISSUE THREAD

**Issue by pmwals09** [s-yadav/react-number-format#804]
#### Describe the issue and the actual behavior

The `allowLeadingZeroes` property does not appear to be making any difference in the behavior of a `<NumericFormat />` component.

#### Describe the expected behavior

I expect that leaving `allowLeadingZeroes` out of the component props, or explicitly setting it to `false`, would strip any leading zeroes from a number on blur.

#### Provide a CodeSandbox link illustrating the issue

[See here](https://codesandbox.io/s/allowleadingzeros-demo-ji97mv?from-embed=&file=/src/App.js). FYI, this is the CodeSandbox that is used in the documentation [here](https://s-yadav.github.io/react-number-format/docs/numeric_format).

#### Provide steps to reproduce this issue

- Insert a NumericFormat component without the `allowLeadingZeroes` property, or set the property to false
- Type in a string of 0s, followed by a number
- Tab or click out of the input to remove focus

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
This was issue on 5.2.0, and have been fixed with the newer release. 
Thanks for pointing out, looks like documentation was not updated. Update the codesandbox to use the latest version `5.3.1`. 
https://codesandbox.io/s/allowleadingzeros-demo-ji97mv
