### ISSUE TITLE
I only want to see number only?

### ISSUE THREAD

**Issue by dotku** [s-yadav/react-number-format#809]
#### Describe the issue and the actual behavior

I don't need the input box, just need the number formatter, any replacement?

**Comment by JanderSilv** [comment]
Use the `displayType="text"` property.

```tsx
<NumericFormat displayType="text" value={110} />
```

https://s-yadav.github.io/react-number-format/docs/props#displaytype-text--input

**Comment by dotku** [comment]
Thanks, that is expected.
I just fork and created a demo: https://codesandbox.io/s/displaytype-demo-forked-467lrz

Resolved :)

**Comment by dotku** [comment]
closed
