### ISSUE TITLE
5.3.1 Regression: Typing "." leads to "^0.00" where "^" is location of caret

### ISSUE THREAD

**Issue by Stan-Stani** [s-yadav/react-number-format#817]
#### Describe the issue and the actual behavior
Typing "." then "5" in an empty input leads to "50.00" with a controlled input in version 5.3.1 but not 5.3.0

![glitchNumberInput](https://github.com/s-yadav/react-number-format/assets/14880397/bf792c9e-5e25-41a2-9015-3151ff4e3cf9)

```ts
<NumericFormat
          // defaultValue={"0.00"}
          autoComplete="off"
          fixedDecimalScale
          decimalScale={2}
          onValueChange={(obj, objtwo) => {
            console.log(obj);
            setValue(obj.value);
          }}
          value={value}
          allowNegative={false}
          allowLeadingZeros={false}
        />
```
#### Describe the expected behavior
Above input should lead to "0.50" or ".50"

*Using defaultValue for my case is not preferred because it's easier to just click in an empty input
than to position the cursor at the beginning of the default value.*

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/p/sandbox/value-demo-forked-8jrtyg?file=%2Fsrc%2FApp.js%3A18%2C29

#### Provide steps to reproduce this issue
See above description

#### Please check the browsers where the issue is seen
- [x] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [x] Firefox
- [ ] Firefox (Android)

**Edit:** Also note that if the version is pinned to 5.3.0 and `valueIsNumericString` is present, then the same issue presents itself.

**Comment by s-yadav** [comment]
This is fixed on 5.3.2
