### ISSUE TITLE
Support IME japanese keyboard

### ISSUE THREAD

**Issue by Inshiku-Han** [s-yadav/react-number-format#823]
#### Describe the issue and the actual behavior

Enable input １２３４５６７８９０(It's different to 1234567890)

#### Describe the expected behavior

Can't input １２３４５６７８９０

#### Please check the browsers where the issue is seen
- [ ] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
@Inshiku-Han  Please check if this example of custom numeral helps.
https://s-yadav.github.io/react-number-format/docs/customization#custom-numeral-example

**Comment by Inshiku-Han** [comment]
> @Inshiku-Han Please check if this example of custom numeral helps. https://s-yadav.github.io/react-number-format/docs/customization#custom-numeral-example

コメントありがとうございます。あなたの提案を試してみます。一旦このイシューはクローズさせていただきます。
