### ISSUE TITLE
Dynamic masking

### ISSUE THREAD

**Issue by pudgereyem** [s-yadav/react-number-format#83]
This is just a thought, I think this could be useful in some cases.

## Background / My use case
I'm creating an input where the user should enter their social identification number.
In the nordic countries (where I'm from) they could be like: `YYMMDD-XXXX`.

The mask property is currently a string. Which is fine for many scenarios, but I'd like to have the option to have have different mask "string" for different parts of the formatting.

### Current masking example
- `format="######-####"`
- `mask="_"`

..it would render into: 19____-____

### Dynamic masking example
- `format="######-####"`
- `mask=['Y','Y','M','M','D','D','X','X','X','X']`

..it would render into: 19MMDD-XXXX

## Why?
I think this could be good, to remind the user in what specific format they should enter something.

## Possible solution
Make it so that mask property also accepts an array as a value, which would then map to the format value. So we could have:

- `format="######-####"`
- `mask=['Y','Y','M','M','D','D','X','X','X','X']`

And we could then check if `mask` is a String or Array. 

---

Thoughts on this @s-yadav? I could fix this and make a PR if so.

**Comment by s-yadav** [comment]
It can be added. With the constraint of a mask to be non-numeric characters or array of non-numeric characters.
This is something I am not very sure how many people will be using and also can be achieved some what by giving placeholder. 
But yes this is one nice little feature and can be implemented with the small addition of code. 

On the PR can you incorporate (if not already thought of)
1. Have a check for non-numeric character in the mask and throw an error if it contains a number.
2. Test cases

**Comment by s-yadav** [comment]
Also mask can not be `#`

**Comment by pudgereyem** [comment]
@s-yadav Yeah, I don't know how many would use this. Let's keep this issue open and see if anyone else needs this. I can make a PR, but at the moment I'm thinking of the implications this would have in relation to https://github.com/s-yadav/react-number-format/issues/84 – which is a feature I think is more "needed". Thanks.

**Comment by s-yadav** [comment]
Added support for dynamic masking in v3 alpha
