### ISSUE TITLE
Caret focus in empty place with format value

### ISSUE THREAD

**Issue by jerryk1925** [s-yadav/react-number-format#839]
Hi. i have problem with caret. When i focus in empty place in input with pattern format value, i can focus in empty place
I have video with this problem
[Запис з 26.04.24 09:28:01.webm](https://github.com/s-yadav/react-number-format/assets/33548374/38c06487-d901-4721-a7b6-639eeefe7b18)

#### Provide steps to reproduce this issue
example code
<PatternFormat autoFocus allowEmptyFormatting format="+38 0## ### ## ##" />

#### Please check the browsers where the issue is seen
- [ x] Chrome

**Comment by quocvuong2000** [comment]
any update ?

**Comment by s-yadav** [comment]
So there is actually some whitespace, we try to move cursor to non masked area. But looks like after selection if I move through arrow keys, the cursor position is not corrected.

**Comment by s-yadav** [comment]
this is fixed on v5.4.0
