### ISSUE TITLE
onValueChange function changes entered digit to 0 after 16th digits

### ISSUE THREAD

**Issue by SmokeGuap** [s-yadav/react-number-format#846]
#### Describe the issue and the actual behavior
```
 onValueChange={({floatValue}: NumberFormatValues) => {
          if (floatValue) {
            onChange(floatValue);
          }
        }}
```
After entering 16th digits, the next digit is converted to zero.

Example: 
Enter 16 digits: 5 555 555 555 555 555
Enter next one 5: 55 555 555 555 555 550
#### Describe the expected behavior
Example: 
Enter 16 digits: 5 555 555 555 555 555
Enter next one 5: 55 555 555 555 555 555
#### Provide a CodeSandbox link illustrating the issue
[codesandbox](https://codesandbox.io/p/sandbox/mystifying-perlman-3tkzf5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxkbv2oi0006356rarxb1lfv%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxkbv2oi0002356rr5lbqeax%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxkbv2oi0003356rzzo910jf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxkbv2oi0005356r8o2jlled%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxkbv2oi0002356rr5lbqeax%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxkbv2oi0001356rz8dp8epd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxkbwf7o005g356r9lmone40%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A7%252C%2522startColumn%2522%253A55%252C%2522endLineNumber%2522%253A7%252C%2522endColumn%2522%253A55%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxkbv2oi0002356rr5lbqeax%2522%252C%2522activeTabId%2522%253A%2522clxkbwf7o005g356r9lmone40%2522%257D%252C%2522clxkbv2oi0005356r8o2jlled%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxkbv2oi0004356rc3yejydl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxkbv2oi0005356r8o2jlled%2522%252C%2522activeTabId%2522%253A%2522clxkbv2oi0004356rc3yejydl%2522%257D%252C%2522clxkbv2oi0003356rzzo910jf%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxkbv2oi0003356rzzo910jf%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
#### Please check the browsers where the issue is seen
- [X] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [ ] Firefox
- [ ] Firefox (Android)

**Comment by Spielboerg** [comment]
I think this has to do with the [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) (`9007 1992 5474 0991` < 17th digit number).

Just try `console.log(Number(55555555555555555))` and you will get the same result.

**Comment by s-yadav** [comment]
For long integers, using string representation of those numbers is better. You can use value from `NumberFormatValues`
