### ISSUE TITLE
Consider removing prop-types dependency

### ISSUE THREAD

**Issue by vorant94** [s-yadav/react-number-format#849]
#### Describe the issue and the actual behavior

`prop-types` are marked as deprecated as of 2017 and in the upcoming React 19 validation failure will start to be silently ignored. Official React docs suggest replacing it with TypeScript interface to still benefit from build-time checks and reduce the overall bundle size. 

https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops

#### Describe the expected behavior

Please consider removing this lib from the list of dependencies. If you are OK with it, I'll be glad to contribute the fix

**Comment by s-yadav** [comment]
Actually we can remove it as internall we are no longer using it.

**Comment by s-yadav** [comment]
Fixed on 5.4.1
