### ISSUE TITLE
isCharacterSame is not called on NumericFormat

### ISSUE THREAD

**Issue by raDiesle** [s-yadav/react-number-format#850]
#### Describe the issue and the actual behavior
isCharacterSame is not called on NumericFormat  (v5.4.0) ,
but TypeScript types tell me the prop exists

#### Describe the expected behavior
NumericFormat allows me to specifiy isCharacterSame, but its not called.
When defined on NumberFormatBase, it is called

#### Provide a CodeSandbox link illustrating the issue
https://codesandbox.io/s/alloweddecimalseparators-demo-forked-4z33vm?file=/src/App.js

#### Provide steps to reproduce this issue
The use case: 
The form stores type of number, but react-number-format stores in string.
When I enter "." on decimalScale , the cursor jumps to the beginnig, because ".00" is not the same as "0"
So I want the cursor to start right next to the "." as its working in the demos

#### Please check the browsers where the issue is seen
- [x] Chrome

**Comment by s-yadav** [comment]
This is expected, isCharacterSame is prop for NumberFormatBase and internally used in NumericFormat to handle certain cases.

In case you want to override you can use useNumericFormat hook with NumberFormatBase, and then can pass monkeyPatch `isCharacterSame` coming from `useNumericFormat`. 

Looks like it's leaked on types of NumericFormat. Will fix that.

**Comment by s-yadav** [comment]
Removed type from NumericFormat and PatternFormat on 5.4.1
