### ISSUE TITLE
Caret jumping around when typing into PatternFormat

### ISSUE THREAD

**Issue by m-orsh** [s-yadav/react-number-format#852]
#### Describe the issue and the actual behavior
The caret goes to the very end of the field for a moment when typing, looking like the caret jumps around. It happens when I use `PatternFormat` using a string `format` prop of any kind. I am using the field in a controlled manner so changing the field triggers a rerender. If I use my own functional format prop with `NumberFormatBase` it does not happen.

#### Describe the expected behavior
Caret should remain in the typing position and not jump to the end of the mask for a moment with every input

#### Please check the browsers where the issue is seen
- [x] Chrome

**Comment by s-yadav** [comment]
Can you share some codesandbox illustrating the issue? Most likely you are passing an inline function on customInput, which is creating new component on every render, causing this issue.

**Comment by m-orsh** [comment]
After some further investigation, looks like it was caused by some code triggered within the onChange and onBlur functions passed into PatternFormat.

`
        if(unformat) {
            val = unformat(val);
            e.target.value = val;
        }
`

Due to writing to e.target.value, it unformatted the value, which was formatted again by PatternFormat, resulting in the flashing. (This wasn't actually needed, but I believe was only added since higher level functions were reading from e.target.value when they shouldn't be)
