### ISSUE TITLE
Weird behavior after clearing input

### ISSUE THREAD

**Issue by MartinWeb** [s-yadav/react-number-format#855]
#### Describe the issue and the actual behavior
When we clear a NumericFormat input, either with the Suppr button directly by testing, either with the clear function of the userEvent of testing-library, a weird behavior appears with the last version, the 5.4.1.
This didn't use to happen with the 5.4.0.

After clearing the input, when we start typing, the first number are set as floating numbers, not as "positive" numbers like it used to.

#### Provide steps to reproduce this issue
- Clear a input with the Delete button or a clear function inside a test environment (testing-library for example)
- Type inside the input
- Numbers appears as floating numbers

Here on the gif, i focused the input, Ctrl + A to select all, click Delete button, then type 3.21.
The 3 number appears, then disappear after clicking the .
![firefox_p4Mse8jbLQ](https://github.com/user-attachments/assets/5a6d5c18-a59a-4c72-95dd-ab3ba2d0cafd)

I have these properties set on the NumericFormat component 
`decimalScale="2"
decimalSeparator=","
fixedDecimalScale
allowNegative={false}`

#### Please check the browsers where the issue is seen
- [ ] Chrome
- [ ] Chrome (Android)
- [ ] Safari (OSX)
- [ ] Safari (iOS)
- [X] Firefox
- [ ] Firefox (Android)

**Comment by s-yadav** [comment]
This is fixed on 5.4.2.
