### ISSUE TITLE
broken decimal separator since 5.4.1

### ISSUE THREAD

**Issue by jwallet** [s-yadav/react-number-format#858]
https://github.com/s-yadav/react-number-format/releases/tag/v5.4.1 broke french support with 
> handle caret position when float numbers are used with decimals https://github.com/s-yadav/react-number-format/issues/851

probably related with using `'.'` char instead of var `decimalSeparator`

https://github.com/s-yadav/react-number-format/blob/a1fab6de57fd94d8ef05b05884b8427ee709fe9d/src/numeric_format.tsx#L525

https://github.com/user-attachments/assets/0a4b790a-d172-41cb-a1b1-a9970efd42f8

**Comment by jwallet** [comment]
duplicate of https://github.com/s-yadav/react-number-format/issues/855

**Comment by s-yadav** [comment]
This is fixed on 5.4.2
