### ISSUE TITLE
Allow specification of output tag via property

### ISSUE THREAD

**Issue by vsyc-sagax** [s-yadav/react-number-format#86]
You can't use react-number-format to create labels in SVG-based charts, for example, as in SVG text is rendered between `text` or `textspan` tags, not `span` tags. Could you allow the user to supply the wrapping element as a property, maybe by expanding the values accepted by `displayType`? Or add `none` to the values accepted by `displayType` to allow the user to wrap the output of the component in their own element manually?

**Comment by s-yadav** [comment]
Added renderText method
