### ISSUE TITLE
NumericFormat does not play nicely with number input.

### ISSUE THREAD

**Issue by DarryQueen** [s-yadav/react-number-format#860]
#### Describe the issue and the actual behavior

When backspacing through a decimal point in `<input type="number'>`, the cursor jumps to the beginning of the input.

#### Provide a CodeSandbox link illustrating the issue

Demo [here](https://codesandbox.io/p/sandbox/value-demo-forked-7l4gmp).

#### Provide steps to reproduce this issue

1. Type in "1.5" in the input box.
2. Hit backspace once.
3. Notice the focus is now at the _beginning_ of the input.

**Comment by s-yadav** [comment]
Yes, it does not, and it expected, as it applies formatting inline in the input, type="number" can't be supported.
