### ISSUE TITLE
Support exponential

### ISSUE THREAD

**Issue by aristidesfl** [s-yadav/react-number-format#89]
The input doesn't allow the letter `e` / `E` to be typed but it is a valid way to represent a javascript number.

```js
parseFloat('4e3') === 4000  // true
```

```js
(4000).toExponential() === '4e+3'  // true
```

**Comment by s-yadav** [comment]
Supporting exponential could give other use cases like making sure e is typed in the right place, supporting + as valid input, supporting 4e3/4e+3 format etc.  
For now, I will keep it as won't fix.

**Comment by ElamT** [comment]
is there some workaround for this problem?
