### ISSUE TITLE
How can I support masking for a cron tab format input?

### ISSUE THREAD

**Issue by viperfx** [s-yadav/react-number-format#92]
I need to be able to specify a mask like 
`# # # # #`

However, some of those inputs can be variable length. From 1 to 6 in length. To accept inputs like 

`1-3` or `1,2,3` - e.g. for the days of the week.

I need some help with how to approach this? Is it to use a custom validation function?

**Comment by s-yadav** [comment]
This is not supported right now. You can use custom format function for now.
