### ISSUE TITLE
Remove displayType and customInput props and use a render prop instead 

### ISSUE THREAD

**Issue by renanpvaz** [s-yadav/react-number-format#93]
I think that instead of rendering text, an input or a custom input a [render prop](https://cdb.reacttraining.com/use-a-render-prop-50de598f11ce) would make the component much more flexible and easy to reason about.

Examples: 

```javascript
<NumberFormat 
  value={4111111111111111} 
  render={value => <span>{value}</span>} 
  format="#### #### #### ####" 
/>

<NumberFormat 
  value={4111111111111111} 
  render={value => <CustomTextComponent bold italic>{value}</CustomTextComponent>} 
  format="#### #### #### ####" 
/>

<NumberFormat 
  value={4111111111111111} 
  render={value => <input type="number" value={value} />} 
  format="#### #### #### ####" 
/>
```

**Comment by s-yadav** [comment]
We need the control over rendered element as we do a lot with input events and caret position. Providing a render method for input can be a lot more tricky.
