### ISSUE TITLE
Set Focus

### ISSUE THREAD

**Issue by njaume** [s-yadav/react-number-format#94]
Hi, i need to know how can i set the focus on the component inside blur event of another component. 
It's possible?

**Comment by s-yadav** [comment]
You can try with giving tabIndex
Or if that does not work add a ref to NumberFormat 
```js
<NumberFormat ref={(numFormatInstance) => {this.numFormatInstance = numFormatInstance}/>
```
and use `ReactDOM.findDOMNode(this.numberFormatInst)` to get the element. You may need to traverse even deeper if using any custom input component. After getting element, you can call the focus method of it.

Note: Using findDOMNode, in general, is not a good practice. So avoid it in other places.

**Comment by mifas** [comment]
If you're using custom Input, There is an easy way without using `findDOMNode`
```js
customInput={props => <Input ref={el => {
   this.inputRefNew = el;
}} {...props} />}
```

https://codesandbox.io/s/n4pw697pr4
