### ISSUE TITLE
Limit value.

### ISSUE THREAD

**Issue by havantuan** [s-yadav/react-number-format#98]
I can't limit value ????????
event on Keydown, onKeyup .... I not found.
example : min : 5 or Max: 10000

**Comment by s-yadav** [comment]
Use isAllowed prop to validate input.  Something like
```jsx
<NumberFormat isAllowed={(values) => {
  const {floatValue} = values;
  return floatValue >= 5 &&  floatValue <= 10000;
}}/>
```

**Comment by havantuan** [comment]
thanks you very so much!

**Comment by joseabraham** [comment]
Same issue here as mglrahul, how did this get resolved?

**Comment by arnaslab** [comment]
`<NumberFormat isAllowed={(values) => {
    const { formattedValue, floatValue } = values;
    return formattedValue === "" || floatValue <= 10000;
}}/>`

**Comment by markcorrea** [comment]
The solution provided didn't work for me, at least when I implemented them `min` value. I set a minimum value of 5 and the input would block me from inserting any value starting with 1, 2, 3 or 4. Even when my intention was inserting `10` or `12`, I couldn't, because the first character is `1`, and `1` is lower than `5`. Here's my code: 

```
 isAllowed={values => {
        const {formattedValue, floatValue} = values
        return formattedValue === '' || (floatValue <= 15 && floatValue >= 5)
      }}
```

Has anyone gone through this and found a solution?

**Comment by sverag** [comment]
> The solution provided didn't work for me, at least when I implemented them `min` value. I set a minimum value of 5 and the input would block me from inserting any value starting with 1, 2, 3 or 4. Even when my intention was inserting `10` or `12`, I couldn't, because the first character is `1`, and `1` is lower than `5`. Here's my code:
> 
> ```
>  isAllowed={values => {
>         const {formattedValue, floatValue} = values
>         return formattedValue === '' || (floatValue <= 15 && floatValue >= 5)
>       }}
> ```
> 
> Has anyone gone through this and found a solution?

this works for me:

```
isAllowed={values => {
    const { formattedValue, floatValue } = values
    if (floatValue == null) {
        return formattedValue === ''
    } else {
        return (floatValue <= 15 && floatValue >= 5)
    }
}}
```

**Comment by said7388** [comment]
isAllowed={(values) => {
            const { floatValue , formattedValue} = values;
            return formattedValue === 0 || floatValue < 100000000;
          }}
